### ISSUE TITLE
catalog/_refworks_form.html.erb should move to blacklight_marc

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1031]
Along with Blacklight::UrlHelperBehavior#refworks_export_url

**Comment by jrochkind** [comment]
Might you not want to export to refworks even if you are not using MARC?

**Comment by jcoyne** [comment]
@jrochkind Yes, but our current implementation of refworks depends on having things indexed as marc: https://github.com/projectblacklight/blacklight-marc/blob/c5ec9c48b738c77140858ef3decb05abc11f5077/app/helpers/blacklight_marc_helper.rb#L7

**Comment by jrochkind** [comment]
It depends on being able to export the doc in a MARC format, it does not depend on things being indexed as MARC.  If a SolrDocument provides an `#export_as_refworks_marc_txt` method, then the current code will work with it to export to Refworks, it doesn't matter how the document was indexed.  Think of MARC in this case just as an interchange format that Refworks understands, that any document can be translated to.  But sure, it could be even better by also supporting other, less legacy bizarre, interchange formats that Refworks understands too.
