### ISSUE TITLE
Should the results_pagination be shown for 1 result?

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#1057]
Currently in https://github.com/projectblacklight/blacklight/blob/514a51c816116705218083e98fe8eda7d985a943/app/views/catalog/_results_pagination.html.erb#L1

It will only show the results pagination bar if greater than 1 result is present. 
```erb
+<% if show_pagination? and @response.total_pages > 1 %>
```

I feel like it should be shown for anything greater than 0. Is there something I am missing here on why it is only shown on greater than 1 result?

During user testing for EarthWorks we had this come up several times.

**Comment by jcoyne** [comment]
Google doesn't show a results bar for single results.

![screen shot 2015-01-14 at 4 10 07 pm](https://cloud.githubusercontent.com/assets/92044/5748738/f31cba56-9c07-11e4-99d3-64ba7e739cb1.png)

**Comment by jcoyne** [comment]
Perhaps move that conditional into a helper that you can override locally?

**Comment by mejackreed** [comment]
^^ That could work.

**Comment by cbeer** [comment]
@mejackreed want to do this? I'd like to cut a new release sometime this week if possible..

**Comment by mejackreed** [comment]
@cbeer I'll try to get to it this afternoon.

**Comment by mejackreed** [comment]
@cbeer Looking into this a bit closer I think really what I am looking for is something different than what I referenced above. Closing this ticket and will add a pull request seperately.
