### ISSUE TITLE
Database Table Dropped & Bookmark Issue

### ISSUE THREAD

**Issue by leeheeman** [projectblacklight/blacklight#1060]
So, the database I use for my Blacklight app keeps getting deleted.  Obviously, this breaks the app, and I really would not like that to happen.

The only thing I can think of is that the database is getting dropped when the app tries to write to the database yet is unable to.  The only tables that are written to constantly are "searches" and "bookmarks". Sure, "users" is also frequently written to, but I haven't had the same issues with that function like I have with bookmarks.

I'm thinking the issue is with bookmarks since that function is completely broken to begin with, on my app.

Also, if I click on the link for any entry in my Blacklight app, I get errors that you can see at this page: http://76.74.170.192:3000/catalog/3482

This is driving me nuts and it's very frustrating to all of my coworkers and their employees.

**Comment by leeheeman** [comment]
I should also add that when I look at my database tables for searches and bookmarks, the query_params, among other things, turns out to be null whenever it tries to write to them.

**Comment by jcoyne** [comment]
Sounds like there may be a bug in your RDBMS. I've never heard of such a
problem on a Rails project.

-Justin

**Comment by leeheeman** [comment]
My host says they can't find any issues. I have set up logs, so I will know what's going on if it happens again. I still think the issue is related the error page I linked above.

Even if the issue isn't related to that error page, I still need to resolve that. I have that exact same issue on 3 different servers. Two of the servers are a custom Blacklight app, while the 3rd is the one from the Quickstart guide (the one with Asian book entries). All of them have the exact same issue NoMethodError in CatalogController#show  and undefined method `with_indifferent_access' for nil:NilClass

**Comment by jrochkind** [comment]
When you say "the database keeps getting deleted" -- do you mean (1) all 
rows from the table are deleted, but the database and tables are still 
there?

Or do you really mean what you said, (2) the database itself, and/or all 
the tables in it are being deleted, the tables aren't even there anymore.

If (2), it should not even be possible for BL code to do this. But to be 
sure, you can edit the privileges for the MySQL account that BL is 
using, and make sure the account does not even have privileges to drop 
databases or tables. That should not effect BL at all. And will make you 
more sure that BL isn't doing that.

If (1), it's hypothetically possible for BL to do this, in that BL does 
delete rows from the bookmarks table, but isn't meant to delete ALL of 
them.  We haven't heard of any bug like this before though.  Are you 
running any nightly maintenance to delete old 'stale' Bookmarks? I'd 
guess that would be the most likely place for such a bug, although we 
haven't heard of it. I don't know if there's some logging/auditing you 
can turn on in MySQL to track all deletes.

But if it's (1), I doubt it's BL, and you should be able to verify that 
by adjusting MySQL db account permissions so the account BL is using 
isn't even permitted to do that.

Jonathan

**Comment by leeheeman** [comment]
Ok, let's assume I have database part licked. How do I fix the other issue I mentioned?

**Comment by jrochkind** [comment]
I don't understand the other problem, it's probably going to take some debugging. 

I think you've only described the other problem as:

> Also, if I click on the link for any entry in my Blacklight app, I get errors that you can see at this page: http://76.74.170.192:3000/catalog/3482

When I click on that link, all I get is a prompt to log into your system. So I still don't really know what sorts of problems you are getting. File a separate GitHub issue about that one, describing it clearly? What do you click on on what page, what happens when you click on it, how was that different from what you expected to happen? Include screenshots if you think they'll be helpful in explaining the problem.

**Comment by leeheeman** [comment]
Oh sorry. I will create a test account for you in a little bit, as well as give you more details

**Comment by jcoyne** [comment]
@leeheeman are you connecting to an RDBMS or just using sqlite? In your other ticket it looks like you're in development mode and the default database for Rails is sqlite.  But @jrochkind was talking about MySQL.

**Comment by cbeer** [comment]
Closed due to inactivity.
