### ISSUE TITLE
Custom solr_document_model and solr_response_model classes become anonymous after deep_copy

### ISSUE THREAD

**Issue by rwd** [projectblacklight/blacklight#1061]
If the intention is to allow custom classes for `solr_document_model` or `solr_response_model` to be configurable in a `configure_blacklight` block like:

```ruby
configure_blacklight do |config|
  config.solr_document_model = CustomSolrDocument
  config.solr_response_model = CustomSolrResponse
end
```

... then this behaviour is broken where deep copies of the configuration are used by, e.g. `Blacklight::SolrRespository`

When `Blacklight::Configurable#blacklight_config` creates a deep copy of the Blacklight configuration, the values of `solr_document_model` and `solr_response_model` will change from `CustomSolrDocument` and `CustomResponse` to an anonymous class:

```ruby
class CustomSolrDocument; end
CatalogController.blacklight_config.solr_document_model = CustomSolrDocument
CatalogController.blacklight_config.solr_document_model #=> CustomSolrDocument
CatalogController.blacklight_config.deep_copy.solr_document_model #=> #<Class:0x0000000553e490>
```

Observed using Blacklight 5.8.2 and Rails 4.2.0.

**Comment by cbeer** [comment]
In Rail 4.x, we're delegating to the Rails provided `:inheritable_copy`:

https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/configuration.rb#L240-248

I wonder if it's worth trying to pursue this upstream?

**Comment by rwd** [comment]
Testing against different versions of Blacklight and Rails, this issue appears to have been introduced in Blacklight version 5.8.0.

At version 5.7.2:
```ruby
CatalogController.blacklight_config.deep_copy.solr_document_class #=> CustomSolrDocument
```

**Comment by rwd** [comment]
Adjusting `Blacklight::Configuration` to always use its own `deep_copy` method, even in Rails 4.x, fixes this issue.

**Comment by cbeer** [comment]
Here is the error I was seeing with the Rails `dup` behavior. #1081 fixes it on our end, but it still seems like a Rails bug to me (or, we shouldn't use class instances directly, and force people to use strings that we `#constantize` later?)

```
ActionView::Template::Error (Class name cannot be blank. You need to supply a name argument when anonymous class given):
    11:          <span class="document-counter">
    12:          <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
    13:          </span>
    14:          <%= link_to_document document, document_show_link_field(document), :counter => counter %>
    15:         </h5>
    16: 
    17:         <% # bookmark functions for items/docs -%>
  app/views/channels/search-results.html.erb:10:in `_app_views_channels_search_results_html_erb__4407396360987356696_70255674350640'
  app/controllers/channels_controller.rb:22:in `block (2 levels) in show'
  app/controllers/channels_controller.rb:21:in `show'
  app/controllers/channels_controller.rb:6:in `index'
```
