### ISSUE TITLE
 NoMethodError in CatalogController#show 

### ISSUE THREAD

**Issue by leeheeman** [projectblacklight/blacklight#1062]
I have Blacklight set up on 3 different servers. Two of them are custom, while the third one is the straight from the Quickstart Guide.  When you click on an entry to see a single result, it's supposed to show you just that entry such as in the demo here: http://demo.projectblacklight.org/catalog/2009002583

On the demo, you can see just that one entry after you click the link for the entry in the search results.

On my Blacklight installs, when you click on a specific entry you get what you see in the following attached screen cap.

![screen shot 2015-01-26 at 12 38 55 pm](https://cloud.githubusercontent.com/assets/10160827/5905860/d8db3884-a558-11e4-9ea1-5ccb3d7927a5.png)

**Comment by jcoyne** [comment]
It looks like `current_search_session.query_params` is returning `nil` https://github.com/projectblacklight/blacklight/blob/1b0fd9f80efea73f5a4833e45092a5c10567a2b2/lib/blacklight/catalog/search_context.rb#L97

Could this be due to your database problems you described in the other ticket? What do you get when you go to the rails console and type: `Search.count`?

**Comment by leeheeman** [comment]
When I type that into rails console, it performs a query on my 'searches' table in my database. It returned the same value that is the number of rows in my table.

When I actually go into my 'searches' table in MySQL, I noticed that the query_params, user_id, and user_type fields all contain NULL. This is the same thing that's going on with my 'bookmarks' table. My app is writing NULL entries.

When I logged into rails console, it said 'development environment'. I am starting to think that I screwed up and did not load the app into production. I used rails s -b domainname.net -d.  I forgot to add in -e production, which might be the issue now that I think about it.

Are there any other reasons why the app might not properly writing to the database tables properly (devise is writing to the 'users' table properly)?

**Comment by jrochkind** [comment]
I would definitely not use SQLite in production. But I still would not expect doing so to result in any of the sorts of problems you are talking about. But still, do not use SQLite in production. Use MySQL or postgres.

**Comment by jrochkind** [comment]
I am not sure if our automated testing runs on SQLite, or if any BL developers do dev on SQLite. It's possible there's a bug in BL for SQLite.  Although I'd be surprised, it's possible.

**Comment by leeheeman** [comment]
I don't use SQLite at all. My database.yml points to my MySQL.  The app is writing to MySQL, even if improperly, it is making the entries where I asked it.

**Comment by leeheeman** [comment]
Putting it in production didn't solve the issue, so that's ruled out.  .gitignore has SQLite in there anyway

**Comment by leeheeman** [comment]
I checked my logs, and this is what it's doing right before the error.
Started POST "/catalog/3482/track?counter=1&search_id=400" for 70.115.129.58 at 2015-01-26 23:50:24 +0000
Processing by CatalogController#track as HTML
  Parameters: {"authenticity_token"=>"oqpJmIb4ZhWX/jlY1N18nhAb/MBKeFwSzFT5ahE60Os=", "redirect"=>"/catalog/3482", "counter"=>"1", "search_id"=>"400", "id"=>"3482"}
  ^[[1m^[[35mUser Load (0.3ms)^[[0m  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
Redirected to http://76.74.170.192:3000/catalog/3482
Completed 303 See Other in 7ms (ActiveRecord: 0.3ms)


Started GET "/catalog/3482" for 70.115.129.58 at 2015-01-26 23:50:24 +0000
Processing by CatalogController#show as HTML
  Parameters: {"id"=>"3482"}
  ^[[1m^[[36mUser Load (0.2ms)^[[0m  ^[[1mSELECT  `users`.* FROM `users`  WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1^[[0m
Solr query: {:qt=>"document", :fl=>"*", :rows=>1, :q=>"{!raw f=id v=$id}", :id=>"3482"}
Solr fetch (9.0ms)
  ^[[1m^[[35mSearch Load (0.7ms)^[[0m  SELECT  `searches`.* FROM `searches`  WHERE `searches`.`id` IN (400) AND `searches`.`id` = 400  ORDER BY updated_at desc 
LIMIT 1

**Comment by jrochkind** [comment]
nothing looks obviously wrong about those log lines you quote. 

I'm afraid it's just going to take some nuts and bolts debugging on your server to figure out what's going on. You might have to get your hands dirty with a ruby debugger and source code.

**Comment by leeheeman** [comment]
I also wonder if any depracated code in catalog_controller.rb would cause my issue as well, except I have the same issue with the standard Quickstart install. Yeah, I'm probably going to have to get a bit messy.

**Comment by leeheeman** [comment]
I just had a thought. I have always been warned not to do a rails install using root user. I should have a user that has sudo privileges. As an example, I remember I had a Wordpress install fail because root had ownership of the files, and it started working when I switched ownership to a user.

My Blacklight installs all used root for the entire installs. I am starting to think this is the issue.  If so, would I need to change ownership of the Blacklight folder only or that folder in addition to all of the ruby gem folders/files?

**Comment by jcoyne** [comment]
I've never tried that before. You may have better luck finding help on a more general Rails forum.

**Comment by jrochkind** [comment]
I think it's pretty unlikely that is the issue, but who knows. But I wouldn't think so. 

Ordinarily, not only should you not do a rails install as a root user, but there should be no need to use a user that has sudo privileges either.

**Comment by leeheeman** [comment]
Ok, in that case, I think it might be prudent to test by adding real data into those null entries. Since we know that one issue is because the query params are returning null, I'm thinking the issue lies with blacklight properly writing to the database. So, if I can get it to not return the above errors by allowing it to pull valid data, I think I can figure out why it's writing NULL entries into the searches and bookmark tables.

Could somebody give me an example of what should be there instead of NULL? I want to see if I can those table entries to work.

**Comment by leeheeman** [comment]
I wonder if the issue has to do with the following. You say go to a Rails forum, but this is happening with Blacklight specifically. Sure, I will do that, but the following is worth looking here.  Also, saved searches gives me an error about "can't convert Symbol into Integer" for line: <td><%= link_to_previous_search(search.query_params) %></td>

Anyway, the following is what I get when doing a search on my Blacklight app. I think the part about protected attributes is pertinent to my issue.

Processing by CatalogController#index as HTML
  Parameters: {"utf8"=>"✓", "search_field"=>"all_fields", "q"=>"nunya"}
  Search Load (0.8ms)  SELECT `searches`.* FROM `searches`  WHERE `searches`.`id` IN (413, 412, 411, 410, 409, 408, 407, 406, 405, 404, 403, 402, 401)  ORDER BY updated_at desc

WARNING: Can't mass-assign protected attributes for Search: query_params

   (0.2ms)  BEGIN
  SQL (0.4ms)  INSERT INTO `searches` (`created_at`, `query_params`, `updated_at`) VALUES ('2015-01-29 23:51:39', NULL, '2015-01-29 23:51:39')
   (9.2ms)  COMMIT

**Comment by leeheeman** [comment]
I think I have it fixed. Might not be the best way to do it, but it's doing what I want (other than the saved searches thing).

I added config.active_record.whitelist_attributes = false to the environment initializer, and also I changed the collation in the MySQL database. Not sure why the database migrate feature set the collation to anything other than utf8. 

Now, I can go to single view and bookmarks without any noticeable issues.

**Comment by jkeck** [comment]
@leeheeman you may be leaving yourself open to some pretty nasty attacks by setting `whitelist_attributes` to false like that.  YMMV.

Also, WRT the database collation, that's not something that Blacklight sets itself so must have been that way to begin with.  I believe MySQL's default collation is `latin1_swedish_ci`, which can cause issues.

**Comment by leeheeman** [comment]
I understand, but the app isn't open to the public anyway, so it will have to do until I figure out a proper whitelist.
