### ISSUE TITLE
MarcImporter complains about invalid Solr binary request handler

### ISSUE THREAD

**Issue by arafalov** [projectblacklight/blacklight#1070]
Following the Quickstart process the step 7 causes the following warning:

> $ rake solr:marc:index_test_data
> ...
> Warning: Specifying binary request handling from a Solr Server that doesn't support it. Enable it in the solrconfig file for that server.
> Solrversion UNKNOWN using xml response writer

**Comment by barmintor** [comment]
This is a blacklight-marc issue that appears to have been fixed sometime before v6.2.0.
