### ISSUE TITLE
facet labels break in odd places on Firefox

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1080]
Firefox
![screen shot 2015-02-16 at 9 26 41 am](https://cloud.githubusercontent.com/assets/92044/6214423/0f38d024-b5be-11e4-8c53-5756ccd91204.png)

Chrome
![screen shot 2015-02-16 at 9 26 30 am](https://cloud.githubusercontent.com/assets/92044/6214436/1f9b8c5e-b5be-11e4-8df2-7ab1c021cdd4.png)

**Comment by jcoyne** [comment]
I think this is due to:
```css
.facet_label {
  word-break: break-all;
}
```

**Comment by jrochkind** [comment]
I wonder if there was a reason/motivation for word-break:break-all? It does seem to be incorrect on a naive view, yes?

**Comment by cjcolvar** [comment]
We have a fix for this in Avalon and we'll work on it when we get a chance.  @bkeese could you take a look at making a PR?

**Comment by cbeer** [comment]
Fixed in #1263
