### ISSUE TITLE
Memoize search_builder

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1110]
I'd like to be able to do this in a method:

```ruby
      search_builder.collection = @collection
      # run the solr query to find the collections
      (@response, @member_docs) = search_results(solr_params, search_params_logic)
```

However, search_results is using it's own instance.

**Comment by jcoyne** [comment]
This is not possible due to `with` returning a new search_builder. We need a way to pass a search_builder into the search_results method.

**Comment by jcoyne** [comment]
I'm working around by overriding search_builder, but it seems awkward:

```ruby
    # Override blacklight to produce a search_builder that has the current collection in context
    def search_builder processor_chain = search_params_logic
      super.tap { |builder| builder.collection = @collection }
    end
```

**Comment by jcoyne** [comment]
It appears that the problem is that `solr_document_ids_params` (called by `fetch_many`) is making it's own search_builder.

**Comment by cbeer** [comment]
What if we had:

```
def search_builder
...
end

def default_search_builder
@default_search_builder ||= search_builder
end
```

and you could override `#default_search_builder` instead?

**Comment by jcoyne** [comment]
cbeer: I'm not sure how your proposed solution solves the problem unless `search_results` is modified to use default_search_behavior.  https://github.com/projectblacklight/blacklight/blob/ae5b46ca8f43b045a3a55d3a57b9c7c82e59de04/lib/blacklight/search_helper.rb#L101

**Comment by jcoyne** [comment]
I wonder if I can leverage `@scope` (e.g. `@scope.current_ability`) in order to solve the issue. I'll check that.

**Comment by jcoyne** [comment]
Yes, this will work:  https://github.com/projecthydra-labs/hydra-collections/commit/476609670587e536d468775667af178a4b6e81f5

**Comment by cbeer** [comment]
:+1: I think that's the best solution yet.
