### ISSUE TITLE
Can't set `:wt` in default params

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1129]
when you try to do:
```ruby
    config.default_solr_params = {
      wt: 'json',
    }
```
The request ends up as: 
`http://127.0.0.1:8983/solr/test/select?wt=ruby&qt=search&facet.field=active_fedora_model_ssi&facet.field=location_label_sim&facet.field=creator_label_sim&facet.field=lc_subject_label_sim&facet.field=publisher_sim&facet.field=year_iim&facet.field=form_of_work_label_sim&facet.field=collection_label_ssim&fq=has_model_ssim:("Image")&qf=title_tesim+lc_subject_label_tesim&wt=json`

both ruby and json are set

**Comment by cbeer** [comment]
keys vs symbols?

**Comment by jcoyne** [comment]
Fixed in RSolr
