### ISSUE TITLE
when facet.missing=true

### ISSUE THREAD

**Issue by whisere** [projectblacklight/blacklight#1130]
When facet field set as true in solr
The facet item shows as url instead of 'missing' on the facet bar
eg:
Event 100
http://localhost:3000/spotlight/default-exhibit/catalog?exhibit_id=default-exhibit&f%5Blocation%5D%5B%5D=&only_path=true 8

**Comment by jcoyne** [comment]
I'm not sure I understand the issue here. Do you have a problem with Blacklight or with Spotlight? Can you explain how to reproduce the issue or share a picture of the problem?

**Comment by cbeer** [comment]
I believe this is from the blacklight list. Blacklight does not support Solr's `facet.missing` option at all, and with the way Solr implements `facet.missing` (tacking on a `nil` => (hits) to the facet values), it breaks Rails routing is bad ways. It also seems fairly non-trivial to try add support for `facet.missing` given its serialization, so we'd have to bake-in support for it throughout the stack.

**Comment by whisere** [comment]
![screenshot at 2015-03-05 16 05 46](https://cloud.githubusercontent.com/assets/2360494/6499563/a672e600-c351-11e4-95a0-42792bace7b4.png)

**Comment by whisere** [comment]
I have attached a picture of the facet bar item when facet.missing is set to true. Thanks!

**Comment by jcoyne** [comment]
@whisere are you going to work on a fix for this?  I doubt that anyone else will be working on it.

**Comment by whisere** [comment]
I have tried but without success, any suggestions? I am a bit new to ruby on rails and Blacklight...

**Comment by whisere** [comment]
I found one solution to this, instead of fixing it at this end, I did some change at solr config: 1. disable facet.missing=true in solrconfig.xml; 2. change the content of the field from empty to 'missing' or other preferred value eg 'unknown' in data-config.xml 
But this may be more straightforward with JdbcDataSource 
Let me know if you find other solutions.
