### ISSUE TITLE
add attr_accessible if Rails version is less than 4 or Object.const_defined?('ProtectedAttributes')

### ISSUE THREAD

**Issue by jronallo** [projectblacklight/blacklight#1138]
I'm upgrading a large application from Rails 3 to Rails 4. To smooth the upgrade I'm using the protected_attributes gem and using attr_accessible to my models. This application includes a rather standard Blacklight within it which is now upgraded to latest 5.10. For the Blacklight upgrade some functionality like going to a show view with a current_session causes an error because the search is created but the query_params are not saved. Setting attr_accessible :query_params fixes this.

In app/models/search.rb:8 something like the following would fix this:

```ruby
if Rails::VERSION::MAJOR < 4 || Object.const_defined?('ProtectedAttributes')
  attr_accessible :query_params
end
if Rails::VERSION::MAJOR < 4
  scope :none, where(:id => nil).where("id IS NOT ?", nil)
end
```

Is this something that could be added? The alternative for me would be to override the Search model completely.

**Comment by cbeer** [comment]
Instead of checking the Rails versions, can we check if the class responds to those methods?

**Comment by jronallo** [comment]
@cbeer @jcoyne Thank you for fixing this. I can confirm that after updating blacklight to the latest release and removing my local patch that Blacklight now works fine with an application that uses protected_attributes.
