### ISSUE TITLE
Blacklight 5.8, blacklight-marc, librarian view

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#1181]
Hi, I'm trying to update my app to Blacklight 5.8.2, on the way to Blacklight 5.9, and probably eventually further, but one step at a time -- trying to get things working one version at a time, before dealing with the new SearchHelper deprecation stuff in BL 5.10. 

In my BL 5.8 app, I am having trouble with the MARC "librarian view", it's reporting "No MARC data found", instead of displaying MARC. It worked fine in BL 5.7. 

Trying to debug, I'm getting a bit confused. 

I am using blacklight-marc 5.5.0 -- the gemspec for blacklight-marc 5.5.0 expresses a dependency on `"blacklight", "~> 5.8"`, whereas the next more recent blacklight-marc 5.10.0 says `"blacklight", "~> 5.10"`.  So I think blacklight-marc 5.5.0 is the right one to use with BL 5.8?   

Trying to debug, I see that blacklight-marc 5.5.0 defines a [librarian_view method in Blacklight::Marc::Catalog].  However, if I try to make sure the actual CatalogController#librarian_view method is coming from there in my app, by doing `CatalogController.new.method(:librarian_view).source_location`, I get:

    ["/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.8.2/lib/blacklight/catalog/component_configuration.rb", 38]

When I look at the [ComponentConfiguration class in Blacklight 5.8.2](https://github.com/projectblacklight/blacklight/blob/v5.8.2/lib/blacklight/catalog/component_configuration.rb), I'm pretty confused at what's going on, and if this is really adding a `librarian_view` method or what, it's doing something very abstract/indirect. 

If I put a debugger line at the `blacklight_marc` gem's definition of `librarian_view`, it never gets tripped -- so I think the app is getting a `librarian_view` definition from blacklight rather than blacklight_marc. 

But I'm having trouble actually figuring out what it's doing in order to debug it and figure out why I'm getting "No MARC data found" instead of the MARC display. 

Can anyone give me some hints as to what's going on here, how I can debug, or what might be going wrong in my app?

**Comment by cbeer** [comment]
Your analysis seems sound, but I think to help, we'd have to see, say, your `CatalogController`, `SolrDocument`, and anything else you think might be helpful.

I will note that the demo.projectblacklight.org site is working fine (http://demo.projectblacklight.org/catalog/2008323726/librarian_view) using an out of the box configuration: https://github.com/projectblacklight/demo.projectblacklight.org

**Comment by jrochkind** [comment]
Aha! Switching the order of the includes in my local CatalogController seems to have resolved it. 

Including Blacklight::Marc::Catalog needs to happen _before_ including Blacklight::Catalog. Which is the opposite of what i had, that worked in earlier versions -- and honestly the opposite of what I would have expected. 

But it seems to work.... I need to investigate to make sure it doesn't cause any problems. 

Does this make sense to those who are more familiar with this code, am I doing the right thing, include Blacklight::Catalog::Marc needs to happen before include Blacklight::Catalog?

    include Blacklight::Marc::Catalog
    include Blacklight::Catalog

**Comment by cbeer** [comment]
Sure, that makes sense. Here's the conditional it's probably hitting with the reversed order:
https://github.com/projectblacklight/blacklight/blob/v5.8.2/lib/blacklight/catalog/component_configuration.rb#L59

I guess the `blacklight:marc:install` generator must always be prepending its controller mixin, so we haven't seen this in new installs.

Given that blacklight-marc is now pinned to `blacklight ~> 5.10` and how empty https://github.com/projectblacklight/blacklight-marc/blob/master/lib/blacklight/marc/catalog.rb is (and duplicative of the auto-generated methods anyway..), maybe the easiest thing to do would be update the [librarian_view](https://github.com/projectblacklight/blacklight-marc/blob/master/app/views/catalog/librarian_view.html.erb) template to support the same multi-document mode other document actions support.

**Comment by jrochkind** [comment]
Okay, I'm not sure I understand the 5.10 issues, but I seem to be back working for now with BL 5.8 (actually I up'd to 5.9 to see if it would make a difference, it didn't but didn't seem to harm anything either, so I'm working on 5.9 for now). 

I don't know if the documentation/README in blacklight-marc should say it's include needs to come _before_ Catalog's -- I find that the opposite of what I would have assumed was best without documentation, personally -- but I'll leave that to you.

Thanks for the help!
