### ISSUE TITLE
Re-ordering show.document_actions?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#1182]
Hi, I'm upgrading my app to BL 5.9, and switching to use the neat new configurable show.document_actions, instead of overriding a partial as I had been doing before. 

I want to change the order that the show.document_actions show up in the sidebar. 

However, the value of show.document_actions is not an Array or an Array sub-class or Array-like object which can be easily re-ordered. Instead, it appears to be a `Blacklight::NestedOpenStructWithHashAccess`, which I guess is more of a hash-like class, and the ordering is just the order the values were inserted in the hash-like data structure, I guess?

I guess to really re-order it, I'd have to create a new `Blacklight::NestedOpenStructWithHashAccess`, and set it's key/values in the order I want, perhaps taking the key/values from the original and making sure I'm not missing any, and then setting `blacklight_config.show.document_actions` to my newly created object with the desired ordering?

I'm a bit worried this is a fragile thing to do, which might easily break in future BL versions, because `Blacklight::NestedOpenStructWithHashAccess` isn't intended as public API at all, I'm getting into BL internals which could change at any time.  What do you think?  Or is there a better way to do this? 

Or perhaps I should just give up and decide this isn't supported in BL?  I'm not sure how important the ordering really is to my patrons; I was trying to keep the UI unchanged as I upgrade, but I could also tell internal stakeholders that in the newer BL version, re-ordering these links isn't really supported, this is just what BL is giving us. 

Any advice? Thanks!

**Comment by cbeer** [comment]
I don't have any helpful suggestions, although there should be nothing stopping you from carrying on as before, right? I assume you were overriding partials or the like before?

--

Thinking more about what a better pattern could be, perhaps we could:

- add ordering semantics to the partials configuration, and support something like:

```
blacklight_config.show.document_actions.endnote.before = :refworks
# or
blacklight_config.show.document_actions.endnote.order = -500
```

and determine sort order at runtime, perhaps somewhere in https://github.com/projectblacklight/blacklight/blob/0006292c7289117ed21d30ff29b3d78a32d881be/app/helpers/blacklight/component_helper_behavior.rb#L49?

- move the default configurations into a separate module that could be easily removed from applications?

```
class CatalogController
  include Blacklight::Catalog
  # include Blacklight::Catalog::DefaultComponents
end
```

**Comment by cbeer** [comment]
I suppose you could get to a blank slate today by doing, e.g.

```
blacklight_config.show.document_actions.reject! { true }

# and then build it back up in your order:
add_show_tools_partial(:refworks)
add_show_tools_partial(:bookmark)
```

**Comment by jrochkind** [comment]
Hmm, that could work, I hadn't realized that `add_show_tools_partial(:refworks)` was all I needed to do, no further config needs to be preserved from the original?  I'm a bit worried there might be further config, now or in the future.  The following works, deleting all the keys and reinserting them from the Blacklight::NestedOpenStructWithHashAccess, in my CatalogController config block:

~~~ruby
    # We want to try and re-order the show.document_actions to our desired order.
    # This appears to be one way to do it, deleting and reinserting everything we want.
    # https://github.com/projectblacklight/blacklight/issues/1182
    desired_order = [:bookmark, :citation, :refworks, :endnote, :email, :librarian_view]
    # Make sure we have any other existing keys on the end of our desired order list too
    desired_order.concat(  config.show.document_actions.keys - desired_order  )
    # Now delete and re-insert each one
    desired_order.each do |key|
      value = config.show.document_actions.delete(key)
      config.show.document_actions[key] = value if value
    end
~~~

Does that seem reasonable? I think the `config.show.document_actions[]` is considered public API safe to use, so if `delete` is too, then this is reasonably likely to be forwards-compatible and safe to do?  Good/bad idea? Thanks!

**Comment by cbeer** [comment]
No, you'd have to provide whatever configuration you need. That was just a quick example.

**Comment by cbeer** [comment]
What you propose makes sense to me, sure. Hash access is definitely in the public API.

**Comment by jrochkind** [comment]
I don't want to eliminate any future tools that end up defaults in BL, I just want to reorder to put my preferred ones at the top, with any future ones that show up that I don't yet know about it coming after. 

That's why I did the `desired_order.concat(  config.show.document_actions.keys - desired_order  )` thing, to catch anything that shows up later that I don't know about now, and make sure it's at the bottom.  

That handles that, and also handles me not having to know exactly what config is required for each tool -- I don't want to have to copy-and-paste all that and keep it up to date with any future changes manually, I just want to reorder what's already there. 

So okay, great, if it seems reasonable to you, I'll go with that, thanks!

**Comment by jrochkind** [comment]
I'm not sure what API changes I'd suggest to make this easier out of the box, but I would personally definitely prioritize those things: I shouldn't have to copy-and-paste exactly what config is needed and then keep it up to date if the default changes, and I should be able to re-order some things at the top (or bottom?) without having to hard-code in the complete list of tools. Both to be properly forwards-looking and not fix things that might change in default BL, but just change the thing I want to change: the order, nothing else.

**Comment by cbeer** [comment]
With https://github.com/projectblacklight/blacklight/commit/6bd6418fc400104ef63269451b5a2b62d46df61b, you should be able to rewrite the above as something like:

```ruby
    desired_order = [:bookmark, :citation, :refworks, :endnote, :email, :librarian_view]
    config.show.document_actions.sort_by! { |k,v| desired_order.index(k) || 1000 }
```
