### ISSUE TITLE
Please document new blacklight.yml

### ISSUE THREAD

**Issue by flyingzumwalt** [projectblacklight/blacklight#1184]
I'm working on https://github.com/UMNLibraries/aath.search, which is less than a year old.  It's using blacklight 5.7.2 at the moment and I'm getting a deprecation warning telling me to use blacklight.yml instead of solr.yml, but I can't find any documentation anywhere about what the blacklight.yml file should look like.  Can I just rename solr.yml to blacklight.yml?  The deprecation warning should point to some sort of clue about what to do. Currently all it says is:

`DEPRECATION WARNING: Configuration is now done via blacklight.yml. Suppport for solr.yml will be removed in blacklight 6.0.0.`

**Comment by cbeer** [comment]
Yep, that's all it is. You can also add the `adapter` argument, e.g.:

https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/config/blacklight.yml

**Comment by cbeer** [comment]
I've updated this wiki page:

https://github.com/projectblacklight/blacklight/wiki/Solr-Configuration

@flyingzumwalt, satisfied?

**Comment by flyingzumwalt** [comment]
+1
