### ISSUE TITLE
config.default_document_solr_params seems to have no effect

### ISSUE THREAD

**Issue by jronallo** [projectblacklight/blacklight#1186]
Using Blacklight 5.11.0 I have the following setting in my catalog_controller.rb:

```ruby
config.default_document_solr_params = {
   qt: 'document_asbury'
}
```

When I look in my logs for a show view request I still see that the qt parameter is set to "document".

What I have been able to do to work around this is the following as I am only setting the request handler:

```ruby
config.document_solr_request_handler = 'document_asbury'
```

**Comment by cbeer** [comment]
Do you know if that is a regression?

**Comment by cbeer** [comment]
Looks like it is. 
https://github.com/projectblacklight/blacklight/blob/v5.7.0/lib/blacklight/solr_helper.rb#L145-152

**Comment by jronallo** [comment]
Yes, this is a regression. This config was carried over from a very long lived Blacklight application so is known to have been working in previous versions of Blacklight.
