### ISSUE TITLE
  Should default_solr_param be overrideable?

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1189]
```ruby
class LocalNames
  include Blacklight::SearchHelper
  include Blacklight::Configurable

  copy_blacklight_config_from CatalogController

  blacklight_config do |conf|
    # conf.search_builder_class = LocalNameSearchBuilder
    config.default_solr_params = {
      'qf' => 'foaf_name_tesim',
    }
  end

  def initialize
    puts blacklight_config.default_solr_params
  end
end
LocalNames.new
```

This prints out the CatalogController defaults, not the defaults I set in this class. Is that right?

**Comment by cbeer** [comment]
Is the code you posted correct, or:
 -  `blacklight_config(&block)` isn't the same as `configure_blacklight(&block)`, is it?
 - `|conf|` and `config.default_solr_params` should probably match..

**Comment by jcoyne** [comment]
Doh! that was it. `s/blacklight_config/configure_blacklight/` Thanks @cbeer

**Comment by cbeer** [comment]
I don't know what the block to an openstruct is supposed to mean, but it seems like a no-op AFAICT:

```
> OpenStruct.new(x:1) { |x| puts "asdf!" }
=> #<OpenStruct x=1>
```
