### ISSUE TITLE
SearchBuilder design?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#1195]
If I understand right from the [new docs](https://github.com/projectblacklight/blacklight/wiki/Extending-or-Modifying-Blacklight-Search-Behavior#extending-blacklightsearchhelpersearch_params_logic)

To modify the Solr query, like the old solr_search_logic, you need to add a new method to a SearchBuilder class, but you still ask for that new method to be used in the CatalogController class, with eg:

```
  # in CatalogController (or equiv controller)
 self.search_params_logic += [:show_only_public_records] 
```

I would have expected the `search_params_logic +=` thing to be inside the SearchBuilder too. Set up a SearchBuilder, tell the CatalogController to use it.  Instead of having to go into the CatalogController (potentially multiple controllers using the same SearchBuilder), and configure something there using internals of the SearchBuilder -- should the CatalogController even know/have to know that there is a :show_only_public_records method in the SearchBuilder being used? That seems like an encapsulation violation.  Seems less confusing if this config were in the SearchBuilder too. 

Would that be better?

**Comment by jcoyne** [comment]
Yes, I agree that's a better place.

**Comment by cbeer** [comment]
And I think `self.search_params_logic = true` gets us most of the way there. I don't know how to get there in 5.x, though, without breaking backwards compatibility. Suggestions?

**Comment by jrochkind** [comment]
I didn't realize there was a 'self.search_params_logic = true` option, and I still don't understand what it does or how it works. 

If I understand right, jcoyne just updated the wiki page at https://github.com/projectblacklight/blacklight/wiki/Extending-or-Modifying-Blacklight-Search-Behavior#extending-blacklightsolrhelpersolr_search_params , but the code he updated it to will STILL stop working in 6? 

cbeer, you may be the only one that understands how to write code that works both in current BL release, and is planned to keep working in 6, code that truly isn't deprecated.  If you wanted to give us a few examples of such code somewhere (I don't know if it involves self.search_params_logic = true or not), it would be hugely helpful. I'm getting pretty lost figuring out all the alternatives, and which ones are planned to break in 6, even if they don't give deprecation notices now.

**Comment by jrochkind** [comment]
I would think, without truly understanding the code or features, that it would be possible to support this configuration in SearchBuilder _now_,  and recommend that in docs.  But also simultaneously support CatalogController#search_params_logic as deprecated behavior. (Although of course we already had CatalogController#solr_search_logic as deprecated behavior, it was an odd choice to add a new method which is _also_ planned to stop working in 6, if I understand right?).   Support both at once, doing it in SearchBuilder (entirely in SearchBuilder, including the equiv of #search_params_logic) and doing it CatalogController, with doing it in CatalogController deprecated.  The union of methods named in SearchBuilder and methods named in CatalogController class method will be called in SearchBuilder. 

But that may not be feasible, I don't really understand the code, or the intended API for BL 6. Examples would be awesome.

**Comment by cbeer** [comment]
`CatalogController#solr_search_logic` is deprecated in favor of `CatalogController#search_params_logic`. Blacklight 5.x applications should use the new name.

I think you've described exactly the current behavior. You can define `search_params_logic` methods in either a search builder or in your controller and they will be properly discovered, however using methods defined on your controller is deprecated behavior.

To maintain backwards compatibility, you define the `search_params_logic` on your controller. An option that was introduced in 5.11 was the ability to set `search_params_logic = true` and use the list of steps from the search builder instead an explicit list defined on the controller.  To use this new way, however, you have to make sure any plugins you are using are doing things the `SearchBuilder` way, and not the legacy way.

From the conversation on IRC, I understood that pushing the logic configuration into the search builder is something important to you. I don't have a good idea how we could support both configuration approaches simultaneously in Blacklight 5.x without causing ourselves a lot of grief, but would be very happy if we could.

**Comment by cbeer** [comment]
> If I understand right, @jcoyne just updated the wiki page at https://github.com/projectblacklight/blacklight/wiki/Extending-or-Modifying-Blacklight-Search-Behavior#extending-blacklightsolrhelpersolr_search_params , but the code he updated it to will STILL stop working in 6?

I think the document will still broadly hold in Blacklight 6. The only difference I see off-hand is instead of:

```
# ./app/controllers/catalog_controller.rb
class CatalogController  < ApplicationController 
  include Blacklight::Catalog
  self.search_params_logic += [:show_only_public_records]
end
```

you'll have

```
class SearchBuilder ....
  self.default_processor_chain += [:show_only_public_records]
end
```

We could, of course, start recommending the latter approach right now, but it would result in duplicate code if you needed to mix+match with the deprecated way of defining behaviors.

**Comment by jrochkind** [comment]
Okay, thanks for the SearchBuilder#default_processor_chain example. That is a much better design, I am reassured to see that's the design you planned, I got the wrong idea from jcoyne's wiki that CatalogController#search_params_logic was the new planned design (especially because that's a new method that didn't previously exist). 

I will see if I can find time to play with the code and get something that works with a mix+match without duplication, possibly with a PR, that can be used as a recommendation. 

I still think it's odd to have created a new method in 5.10+, CatalogController#search_params_logic, that you plan to remove in 6, with no deprecation notice.  It would probably make sense to at least deprecate it in the final 5.x, although really it seems like it shouldn't have been created at all, if it's going to go away in 6, people might as well be using the older CatalogController#solr_search_logic that will do the same thing (I think?) and also go away in 6 (or maybe I'm wrong and it doesn't do the same thing).

**Comment by jrochkind** [comment]
Hi @cbeer and @jcoyne, can you clarify, I want to make sure I'm not making any invalid assumptions, the current `CatalogController#search_params_logic`  method:

Is the current plan that it will be removed in BL6, and people should use `SearchBuilder#default_processor_chain` instead?

Or is the current plan that it will remain in BL6, and people can use either `CatalogController#search_params_logic` or `SearchBuilder#default_processor_chain`, they'll both work in BL6?

Or is there not really a current plan, it hasn't been thought through/decided/considered? 

Thanks!

**Comment by cbeer** [comment]
I think people should use `SearchBuilder#default_processor_chain` in Blacklight 6, and see no reason we should try to keep the controller-based list around. I don't think we can make that the default in Blacklight 5 without a lot of disruption.

**Comment by jrochkind** [comment]
Thanks, I think I'm wrapping my head around what's up, and think I can maybe prepare a PR that will be nice. 

One question though: I believe that the pre-5.10 `solr_search_params_logic` behavior is no longer supported in master, it's not backwards compatible with pre-5.10.  `solr_search_params_logic` used to specify method names of methods in the controller, that used the old `(request_params, solr_params)` signature. 

If I understand right, in current master and 5.13.0, [solr_search_params_logic is just another name for search_params_logic](https://github.com/projectblacklight/blacklight/blob/v5.13.0/lib/blacklight/request_builders.rb#L37-L45), which specifies methods in the SearchBuilder, with a different signature, not methods in the controller.  So that's not actually backwards compat -- there's no longer anything to trigger param building by methods in the controller. Unless I'm missing something?

Was that intentional?  I can deal with it either way, but if you would like me to try and restore backwards compat behavior (without breaking any new behavior, naturally), I can.  Or if what's there is intentional, I won't bother, but still have something to PR that I think matches what everyone wants and helps move forward. 

Or maybe I'm confused, and it still is backwards compat?  

Thanks for any guidance!

**Comment by cbeer** [comment]
> If I understand right, in current master and 5.13.0, solr_search_params_logic is just another name for search_params_logic, which specifies methods in the SearchBuilder, with a different signature, not methods in the controller

Wrong. We explicitly support both cases: https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/search_builder.rb#L120-124

**Comment by jrochkind** [comment]
Okay, thanks. I can't figure out how that possibly works, but I'm having trouble figuring out the code. I don't see any place it could be calling methods defined in the controller with the old api, but the code has layers within layers. I'll mess with it a debugger more, or just figure that if the tests still pass it's still working? 

Now to get my tests to run locally, something that oddly never ever works for me when I come back after a couple months of not testing.  You guys have no problem running tests locally with `bundle exec rake test`, it's just me?

**Comment by cbeer** [comment]
I've annotated the lines I linked to above, for your reading pleasure:

```ruby
    def processed_parameters
     #  a Blacklight::Solr::Request object, used here for backwards compatibility more than anything else. I believe this is an artifact of an early attempt at separating the Blacklight implementation from the required backend parameters. In 6.x, it might make sense to revert this back to an ordinary hash
      request.tap do |request_parameters|
        processor_chain.each do |method_name| # the list of processor steps to apply
          # check if the scope (which, again, is usually, but not necessarily, the controller instance) responds (publicly) to the method.. if it does, we assume this is the old-style controller-mixin way of doing things.
          if scope.respond_to?(method_name, true) 
            Deprecation.warn Blacklight::SearchBuilder, "Building search parameters by calling #{method_name} on #{scope.class}. This behavior will be deprecated in Blacklight 6.0. Instead, define #{method_name} on a subclass of #{self.class} and set search_builder_class in the configuration"
            # so we call that method
            scope.send(method_name, request_parameters, blacklight_params)
          else
            # if it isn't in the controller, it should be in the `SearchBuilder`. If it isn't, fail spectacularly with ruby's method not found exception
            send(method_name, request_parameters)
          end
        end
      end
    end
```

**Comment by cbeer** [comment]
`bundle exec rake test` (does that even exist?) isn't the right task. You should be using `bundle exec rake` or `bundle exec rake ci` to run the Blacklight test suite, and yes, it works for me (and for travis, and others).

**Comment by jrochkind** [comment]
Thanks, I guess it's 'scope' that was confusing me, I'll look into that. You're actually giving the SearchBuilder a reference to the controller as 'scope'?  But ordinarily, for future design, a SearchBuilder's "scope" is just "self", is that right? Phew! Yeah, I missed that a SearchBuilder could have a reference to a controller as 'scope'. 

Sorry, I typo'd, I was just `bundle exec rake`. I'm going to do a clean checkout from scratch of BL, see if I can get it to work.

**Comment by cbeer** [comment]
For the `Blacklight::SearchHelper` methods, `scope` could be a reference to the controller:

**Comment by jrochkind** [comment]
Thanks, that's helpful, so scope isn't jsut a temporary backwards compat thing, but will be there indefinitely, it's needed to carry things like the current_user, which you might need for your search building. 

oy veh, yeah, this stuff gets very complicated, with lots of moving parts. Trying out my ideas in code, I see it may not be possible to do the PR I wanted. 

Existing behavior we need to support in BL 5.x includes that _removing_ a symbol from CatalogController#solr_search_params_logic should remove it from the processor chain, true? Not just that adding a symbol adds it to the processor chain. True? Hm. 

Also, right away in latest BL 5.x, are people using a RequestBuilder outside of a CatalogController/SearchHelper context, but just using it directly, and that's something we need to support too?

**Comment by atz** [comment]
@jrochkind is this ticket obsolete/closable now?

**Comment by atz** [comment]
@jrochkind PING

**Comment by jrochkind** [comment]
@atz Sorry, I haven't been working with Blacklight for the last year. I don't really know if it's obsolete/closeable, I'm just as confused about how this API is intended to be use and what the planned future developments are as ever, but I won't be offended if you decide to close it.

**Comment by barmintor** [comment]
Closing as part of BL7.0 scoping.
