### ISSUE TITLE
CatalogController subclasses don't have access to all their routes by default

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/blacklight#1200]
We're working on an engine that subclasses the `CatalogController`, and we recently attempted to add "more" links to facets based on a user request. However, when we first enabled it, we got an `ActionView::Template::Error` [(stacktrace here)](https://gist.github.com/anarchivist/6a37894d84d07425e136). 

@terrellt suggested that this was an issue he ran into before, and suggested adding the following workaround in our engine's `config/routes.rb`:

```ruby
Krikri::Engine.routes.draw do
  # ...snip...
  resources :records, only: [:index, :show] do
    collection do
      get "facet/:id", :to => "records#facet"
    end
  end
# ...snip...
end
```

**Comment by cbeer** [comment]
I think that's the solution, but maybe it's worth a page on the wiki?

**Comment by jcoyne** [comment]
Did you try:

```ruby
Krikri::Engine.routes.draw do
  blacklight_for :records
end
```

**Comment by anarchivist** [comment]
@jcoyne With that, I get the following:

```
NoMethodError in Krikri::Records#index: undefined method `records_path' for #<Module:0x007fff4f17bcd0>
```

**Comment by jcoyne** [comment]
@anarchivist Yeah, I think the path becomes records_index_path. This is because the blacklight default is the "catalog" controller, a singular resource (which creates the *_index_path), we don't have many "catalogs".

**Comment by anarchivist** [comment]
I understand that, but our application does in fact have many records. :) Is this just a documentation issue?

**Comment by jcoyne** [comment]
Sufia does this: https://github.com/projecthydra/sufia/blob/master/app/views/catalog/_facet_limit.html.erb#L7

**Comment by jcoyne** [comment]
So, search_facet_url is a helper function that you can override: https://github.com/projectblacklight/blacklight/blob/b05cba165b39c0d0799e03d3fe1d30f76e263694/lib/blacklight/controller.rb#L63-L65

It calls `url_for` without a scope. We could add scope as we do in `render_constraints_query` https://github.com/projectblacklight/blacklight/blob/b05cba165b39c0d0799e03d3fe1d30f76e263694/app/helpers/blacklight/render_constraints_helper_behavior.rb#L42
