### ISSUE TITLE
Add Rubocop to Gemfile, versioned

### ISSUE THREAD

**Issue by rwd** [projectblacklight/blacklight#1204]
Trying to verify code syntax locally with `rubocop`, I'm hitting various errors with different versions of it due to missing cops: Style/ClosingParenthesisIndentation in 0.29.1; Style/Blocks in 0.31.0.

Can we have the actual version of Rubocop used in the CI tests added to the Gemfile so that developers can get the correct version installed?

**Comment by cbeer** [comment]
Hound has updated their version of rubocop to something a little more modern.
