### ISSUE TITLE
document_heading for title_field unused?

### ISSUE THREAD

**Issue by mottiok** [projectblacklight/blacklight#1205]
Hi,

I'm a bit confused about the documentation for "document_heading"
https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#title_field

One of our projects still using blacklight 4.x, recently we decided to upgrade (the projects is heavily modified) to the latest version but we encountered a weird problem so I decided to install a clean blacklight as a reference and the problem still exists.

It's appears that "document_heading" not used as a replacement for the default title_field field.
The call stack until the label value is like this:

_index_header_default > link_to_document > link_to_document > DocumentPresenter > render_document_index_label

To solve this we just created a new class that inherit from DocumentPresenter and overwrite "render_document_index_label", than we add to catalog_controller config "document_presenter_class" and pointed to our new class.

It solved the problem but I feel like it's a weird solution to a straightforward feature :(

Any suggestions?

Thanks,
Matthew.

P.S

A bit off topic.. any ETA about blacklight 6.x :) ? I want to update my blacklight_rtl  gem but I prefer to wait for the next big version due to big design changes you will probably make.

**Comment by jcoyne** [comment]
I updated the documentation. https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#title_field  Does that look better?  

I don't think we have an ETA on Blacklight 6.  As far as I know nobody is doing substantial work on it. 
/cc @barmintor

**Comment by mottiok** [comment]
So I was using it properly, good to know :)
Just change "#document_heading" to "#render_document_index_label".

Thanks and have a nice day!
Matthew.
