### ISSUE TITLE
Delete sample data from blacklight

### ISSUE THREAD

**Issue by Gybelle** [projectblacklight/blacklight#1227]
Hi,
It's not clear to me how I can delete the sample data from a blacklight application. Or how to delete records at all. I've tried to execute queries on Solr admin environment, but they don't give the good results.
Also, is it possible to add these features to an admin environment within the blacklight application?
Thanks in advance!

**Comment by jrochkind** [comment]
There actually is no Blacklight admin UI, so there's no place to add 
such admin features. I guess it would be hypothetically possible to add 
a Blacklight admin UI, sure.  I don't know of any plans to do so.

The documents are simply stored in the Solr index. It sounds like you've 
already found where your Solr index is located, great!  If you 
succesfully delete the documents from Solr, they will definitely be 
gone. You may just need to spend some more time with the Solr docs to 
learn how to do this.

But here's one easy way to delete all documents from your Solr, just 
issue the request to delete all documents to Solr over HTTP, making sure 
to include "&commit=true" on the end to tell Solr to commit the change. 
You can use the 'curl' command from a Linux or OSX computer to send the 
request (you could probably also just put it in a browser!).

      curl 
"http://your.solr.example.org/solr/update?stream.body=%3Cdelete%3E%3Cquery%3E%2A%3A%2A%3C%2Fquery%3E%3C%2Fdelete%3E&commit=true"

That confusing payload after "stream.body=" is just the URI-encoded 
version of: "<delete><query>*:*</query></delete>"

I think that should work. Hope this helps,

Jonathan

**Comment by Gybelle** [comment]
Thank you! This helped me.
