### ISSUE TITLE
How to show more fields and process imported data

### ISSUE THREAD

**Issue by Gybelle** [projectblacklight/blacklight#1228]
I'm new to Blacklight and Solr (or SolrMarc), but I can't find my way in the documentation. Is it correct to assume that imported xml-files (in BlackLight application) are first indexed in Solr-files? But how are these processed? After processing, the BlackLight webapp doesn't show all the fields of the tags in the imported xml-files, so I would like to customize these. And where can I find the content of the imported records on Solr? In case all tags where processed correctly, but not showed by the BlackLight app.

Thank you in advance!

**Comment by Gybelle** [comment]
Found a solution:
I check in my .mrc-file for the tag of the field I wan't to add to the web app of my Blacklight project. Next I search in the file index.properties for this value (example: 245) to determine the tag (example: dtitle_display) I need to add to the view of my web app. I do this by adding for example "config.add_show_field 'title_display', :label => 'Title'" to the catalogcontroller. 

Is this a good way to do this? 
Also, where can I find the custom defined functions to map .mrc-data to SolR within the blacklight project? I would like to write my own, but don't know where to place them.

**Comment by barmintor** [comment]
In current versions of Blacklight, this is related to the blacklight-marc project, and in particular the generated MarcIndexer model. See also: https://github.com/projectblacklight/blacklight-marc#indexing

Closing as part of BL7.0 scoping, but please open a ticket on blacklight-marc if there are clarifications to be made in that documetation.
