### ISSUE TITLE
rake solr:marc:index_test_data throws Fatal Error

### ISSUE THREAD

**Issue by foben** [projectblacklight/blacklight#1246]
I followed the steps in the Quickstart guide, creating the project "the hard way". Unfortunately, I cannot import the demo data, since a properties file ("demo_config.properties") referenced in SolrMarc.jar is not existent:

```
 INFO [main] (MarcImporter.java:816) - Starting SolrMarc indexing.
ERROR [main] (Utils.java:221) - Fatal error: Unable to find specified properties file: demo_config.properties
ERROR [main] (MarcImporter.java:826) - Fatal error: Unable to find specified properties file: demo_config.properties
Fatal error: Unable to find specified properties file: demo_config.properties
```

No such properties file exists on my system after following the described steps.

**Comment by barmintor** [comment]
Since blacklight-marc moved to traject, SolrMarc.jar is no longer a dependency.

Closing as part of BL7.0 scoping, but please open a new ticket if a similar problem arises for current releases.
