### ISSUE TITLE
SearchBuilder#merge / @merged_params

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#1252]
SearchBuilder has a #merge method, which adds things to a @merged_params iVar Hash. 

@merged_params is also maintained on various functions that copy a SearchBuilder. 

However, I don't believe the merged_params are _used_ for anything. The #merge method is documented as "Merge additional, repository-specific parameters".  

But I don't think this actually happens. There is no accessor for #merged_params. The "Repository" doesn't seem to use it. It is not used by SearchBuilder#processed_params.  It does not seem to be spec'd in the search_builder_spec or any other spec. 

I think it's in fact a no-op. 

Should it be removed to avoid confusion? Based on the existence of the method and method-level docs, I just tried to use it, and then had to debug why it seemed not to be doing anything. 

Same applies to @reverse_merge. 

I think they should be removed. They do not work and are not spec'd.

**Comment by jrochkind** [comment]
Note there's also a deprecation notice:

            Deprecation.warn(Blacklight::SearchBuilder, "Calling SearchBuilder#query with extra parameters is deprecated. Use #merge(Hash) instead")


But in fact I don't think #merge was ever implemented. This is deprecated for broken functionality.

**Comment by cbeer** [comment]
Aren't they used here?:

https://github.com/projectblacklight/blacklight/blob/6abc7e99c28d93490109acac47b0b63623901ca7/lib/blacklight/search_builder.rb#L104-L107

**Comment by jrochkind** [comment]
Aha! Thanks for finding that, appreciate it. I'll have to debug further why my attempt at using the feature was not working.
