### ISSUE TITLE
Nil exception when a user (most often a bot) does a facet search for a valid custom facet query but with a bad value

### ISSUE THREAD

**Issue by peetucket** [projectblacklight/blacklight#1255]
The scenario is one in which you have a custom facet query, such as this:

    config.add_facet_field 'timestamp', :label => 'Added recently', :query => {
       :weeks_1 => { :label => 'within last week', :fq => "timestamp:[\"#{show_as_timestamp(1.week.ago)}\" TO *]" },
       :months_1 => { :label => 'within last month', :fq => "timestamp:[\"#{show_as_timestamp(1.month.ago)}\" TO *]" },
       :months_6 => { :label => 'within last six months', :fq => "timestamp:[\"#{show_as_timestamp(6.months.ago)}\" TO *]" }
    }

If you ask for a facet value that exists, like below, everything works fine: 

http://localhost:3000/?f[timestamp][]=weeks_1

If you ask for one that doesn't exist, like below, you get a nil exception:

 http://localhost:3000/?f[timestamp][]=years_1 

The exception is from this: line https://github.com/projectblacklight/blacklight/blob/release-5.14/lib/blacklight/solr/search_builder_behavior.rb#L285 

undefined method `[]' for nil:NilClass
..../blacklight-5.14.0/lib/blacklight/solr/search_builder_behavior.rb:285:in `facet_value_to_fq_string'

This might seem theoretical since the user should not be able to request these values (unless they muck about with the URL parameters), but it happens in the real world when you have a value that you later remove, and bots (like Google and Bing) continue to visit previously valid links they clicked on before.  In this case, you get a *lot* of 500s, cluttering up your logs and exception notification system.  

A better behavior may be to simply return an empty result set, the same as would happen if the solr query resulted in 0 results.

I adjusted the Revs code to handle this situation by returning a 404 to the bot, thus hopefully causing them to stop following that link:

https://github.com/sul-dlss/revs/blob/60c4c12f0bbec2a257bb5ae7729cfcfc75ed67aa/app/controllers/catalog_controller.rb#L76-L79

**Comment by jrochkind** [comment]
I agree the 'correct' behavior there is an empty result set, rather than a 404 or an uncaught exception 500. 

I could swear I've seen that 'correct' behavior before, I wonder if something has changed since then in BL to change it, or if it only happens in certain specific circumstance with certain kinds of facet configuration. 

(There's a different issue where asking for a facet _field_ that no longer exists also causes an uncaught exception resulting in a 500, at first I thought this was that, but I see you are talking about a facet _value_ that didn't exist.)

@peetucket, if you were so inclined and had time, one way to help get this going might be to create a branch with a test case for a a request for a facet value that doesn't exist, which in the current codebase will apparently cause an uncaught exception.

**Comment by jrochkind** [comment]
@peetucket, what version of BL are you using?

In my app based on BL 5.08, a facet _value_ that does not exist in the db indeed results in an empty result set. I wonder what the difference is. 

Creating a failing test case would also specify exactly what circumstances, and in what BL versions, this happens in.

**Comment by peetucket** [comment]
We are on blacklight 5.14.0 

A search for facet values that don't exist "work" (return 0 results) when the facet is a solr field from the solr document (99% of cases, probably) - the problem is when you create a facet by specifying a list of allowed values that each run a custom query.  I presume the issue is the method searches your custom list of values and gets a nil when it doesn't find the value sent in.

I don't have commit access to blacklight so can't branch here, but already have a fork of blacklight setup, let me see if can create a new test case in a branch there.

**Comment by peetucket** [comment]
Here is the branch with two new tests (for 5.x). 

https://github.com/peetucket/blacklight/tree/custom-facet-value-nil-exception

Test for allowed values (passes):
/spec/controllers/catalog_controller_spec.rb:79

Test for bogus value (fails):
/spec/controllers/catalog_controller_spec.rb:73

**Comment by peetucket** [comment]
And I just committed a proposed fix which makes the test pass.

**Comment by jrochkind** [comment]
Ah, I missed the problem was specific to a "custom facet query". Awesome thanks for the PR.
