### ISSUE TITLE
Sass compatibility issues

### ISSUE THREAD

**Issue by dchandekstark** [projectblacklight/blacklight#1276]
Upgrading from BL 5.13.1 to BL 5.15.0 with 

sass 3.2.19
sass-rails 4.0.5
bootstrap-sass 3.3.5

breaks:

ActionView::Template::Error (undefined method `type' for .focus:Sass::Selector::Class
  (in /app/assets/stylesheets/blacklight.css.scss)):

Updating sass-rails to 5.0.4 fixes the problem:

bootstrap-sass (3.3.5)
sass (3.4.19)
sass-rails (5.0.4)

**Comment by jcoyne** [comment]
Due to this: https://github.com/sass/sass/issues/1656

**Comment by cbeer** [comment]
Yeah, I don't think there's anything we can do about it, it's a fight between our upstream dependencies.

**Comment by jrochkind** [comment]
Should blacklight's dependencies require sass at least 5.0.4?  Or would that not be flexible enough for all the possible Blacklight environments?

**Comment by cbeer** [comment]
I don't think it's our business, and indeed, it isn't flexible enough. In this case, you could happily run e.g. `bootstrap-sass` 3.3.4 with `sass` 3.2.19.

**Comment by PHLcoding** [comment]
Hi, I have tried to install
bootstrap-sass (3.3.5)
sass (3.4.19)
sass-rails (5.0.4)

while I am still getting the same error, any potential cause of this? I am on Windows 7, so things could be fishy right there..
