### ISSUE TITLE
Next/Previous buttons on show page shows wrong results

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1278]
When you have two sessions open.

1. Open one tab: http://demo.projectblacklight.org/?utf8=%E2%9C%93&search_field=all_fields&q=women Note: You should see 425 results
1. Open another tab: http://demo.projectblacklight.org/?utf8=%E2%9C%93&search_field=all_fields&q=virginia Note: You should see 34 results
1. On the first tab click the first search result. You will see "1 of 34" which is wrong. It should be "1 of 425"

This is because the search pagination is stored in the session.  It is assumed that you only have one session at a time.

**Comment by cbeer** [comment]
I thought we fixed this in #619. I wonder what changed.

**Comment by jcoyne** [comment]
This bug does exist in searchworks too.

**Comment by cbeer** [comment]
Fixed in https://github.com/projectblacklight/blacklight/pull/1280
