### ISSUE TITLE
Solr reporting "URI is too large >8192" for bookmarks request

### ISSUE THREAD

**Issue by mattcg** [projectblacklight/blacklight#1324]
We use hashes of document paths as IDs. These hashes are long. When attempting to load a bookmarks page with hundreds of bookmarked documents, the request URI sent to Solr by Blacklight causes Solr to respond with a 414 error.

Perhaps the request could be sent using POST?

**Comment by cbeer** [comment]
Yep -- in your `CatalogController`, if you set:

```ruby
configure_blacklight do |config|
  config.http_method = :post
end
```

Blacklight will use `POST` instead of `GET`.

**Comment by mattcg** [comment]
Fantastic. Thank you.
