### ISSUE TITLE
SASS induced NoMethodError

### ISSUE THREAD

**Issue by PHLcoding** [projectblacklight/blacklight#1325]
Hi, I am new to Blacklight and Ruby on Rails, and just trying to get the example to work. 

I have just encountered the issue:
undefined method `type' for .focus:Sass::Selector::Class
  (in /home/s.lai/projects/search_app/app/assets/stylesheets/blacklight.css.scss)

I tried what was suggested in issue #1276 and updated sass to 3.4.19, however from the log it seems that when I go to http://localhost:3000/catalog, 3.2.19 is still being used. I can see 3.4.19 in my ruby/gems folder.

How do I change what version sass, sass-rails, and bootstrap-sass, to be used in blacklight? 

ActionView::Template::Error (undefined method `type' for .focus:Sass::Selector::Class
  (in /home/s.lai/projects/search_app/app/assets/stylesheets/blacklight.css.scss)):
    19:     <title><%= render_page_title %></title>
    20:     <%= opensearch_description_tag application_name, opensearch_catalog_url(:format                                                                                   => 'xml') %>
    21:     <%= favicon_link_tag 'favicon.ico' %>
    22:     <%= stylesheet_link_tag "application", media: "all" %>
    23:     <%= javascript_include_tag "application" %>
    24:     <%= csrf_meta_tags %>
    25:     <%= content_for(:head) %>
  sass (3.2.19) lib/sass/selector/simple.rb:88:in `block in unify'
  sass (3.2.19) lib/sass/selector/simple.rb:88:in `each'
  sass (3.2.19) lib/sass/selector/simple.rb:88:in `each_with_i

![sasserr](https://cloud.githubusercontent.com/assets/15701233/11050786/d21117d8-870e-11e5-8876-e4828e468b52.png)

**Comment by cjcolvar** [comment]
You can pin the version of bootstrap-sass in your Gemfile.  Depending on your rails version, you'll want to pin it differently.  Here is an example: https://github.com/projectblacklight/blacklight_advanced_search/blob/master/Gemfile#L22-L29

**Comment by PHLcoding** [comment]
Thanks, I edited in the blacklight-5.16.3\gemfile in the following, where I also changed the if statement to 4.0, as my rails version is 4.0.12 (on windows 7 if relevant). Unfortunately i will get the same error, and the log still shows sass 3.2.19 " sass (3.2.19) lib/sass/selector/simple.rb:88:in `block in unify'"

Is there something equal to recompile for Ruby on Rails i had to run after gemfiles edited? or other gemfile I should edit?

blacklight-5.16.3\gemfile edits:
  if ENV['RAILS_VERSION'].nil? || ENV['RAILS_VERSION'] =~ /^4.0/
    gem 'bootstrap-sass', '>= 3.3.5.1'
	gem 'sass', '>= 3.4.19'
	gem 'sass-rails', '>= 5.0.4'
    gem 'responders', "~> 2.0"
    gem 'sass-rails', ">= 5.0"
  else
    gem 'bootstrap-sass', '< 3.3.5' # 3.3.5 requires sass 3.3, incompatible with sass-rails 4.x
    gem 'sass-rails', "< 5.0"
  end

In the  bootstrap-sass-3.3.5\bootstrap-sass.gemspec, it seems to be it should force sass 3.4 to be used instead of 3.2.19..
 s.add_runtime_dependency 'sass', '>= 3.3.0'

**Comment by cjcolvar** [comment]
Can you create a gist (gist.github.com) of the Gemfile.lock from your application and paste it here?  You probably shouldn't be modifying blacklight's Gemfile but making these changes in your application's Gemfile.

**Comment by jcoyne** [comment]
I also wanted to chime in that Rails 4.0 is unsupported (even for severe
security releases).  You should not use it.  See
http://guides.rubyonrails.org/maintenance_policy.html

-Justin

**Comment by PHLcoding** [comment]
Suggestions from cjcolvar seem to work that I no longer have sass related error for the moment at least, while the next line 23 is now getting me issues:

I have yet to successfully upgrade to Rails 4.2 on windows 7, could this new issue related to OS?

Showing /gem/ruby/gems/blacklight-5.16.3/app/views/layouts/blacklight.html.erb where line #23 raised:

TypeError: Object doesn't support this property or method
  (in /.gem/ruby/gems/turbolinks-2.5.3/lib/assets/javascripts/turbolinks.js.coffee)
Extracted source (around line #23):
          
20       <%= opensearch_description_tag application_name, opensearch_catalog_url(:format => 'xml') %>
21       <%= favicon_link_tag 'favicon.ico' %>
22       <%= stylesheet_link_tag "application", media: "all" %>
23       <%= javascript_include_tag "application" %>
24       <%= csrf_meta_tags %>
25       <%= content_for(:head) %>

**Comment by cjcolvar** [comment]
Searching for that error, I found this page which suggests locking the version of coffee-script-source to 1.8.0:

http://stackoverflow.com/questions/28312460/object-doesnt-support-this-property-or-method-rails-windows-64bit

**Comment by PHLcoding** [comment]
Thanks cjcolvar and jcoyne (though no luck for clean install of rails 4.2 on windows 7 yet), everything now runs smoothly in terms of blacklight per se. I will close this issue now.
