### ISSUE TITLE
Can we get a feature to add custom arguments to :helper_methods?

### ISSUE THREAD

**Issue by ismail44** [projectblacklight/blacklight#1331]
When adding index or show fields it would be nice if we could also pass in some custom arguments to the method (that get appended with document, field, and value). 

For example... I have an index field that is very large coming back from SOLR, I would like to pass it to a helper method that truncates that value, however, I would like to be able to pass in different "max_lengths" to that function. Currently, I have to define a helper_method for each field.

**Comment by cbeer** [comment]
Thanks, that's a good idea. In #1333, I've proposed adding the entire field configuration as an additional parameter, so you can write something like:

```ruby
config.add_index_field 'some_field', helper_method: :truncate_field, length: 120

#...

def truncate_field(options={})
  truncate(options[:value], options[:config].length)
end

```
