### ISSUE TITLE
Solr.yml & Solr Admin Authentication

### ISSUE THREAD

**Issue by leeheeman** [projectblacklight/blacklight#1349]
I want to make sure my Solr admin page is password protected. I know how to set that up, but the problem is my Blacklight app is not setup to access the Solr admin page using credentials.

My solr.yml file only references the URL to get to the Solr admin page. I am not sure how to edit this file to properly make it connected to a password protected Solr admin page.

I am thinking of installing a gem that allows me to do it: https://github.com/justinko/sunspot-rails-http-basic-auth

However, the way their sunspot.yml file examples are setup looks different than the way my solr.yml file looks like, so I am not sure if it is compatible.

For example, my solr.yml file looks like this:

production:
    url: http://127.0.0.1:8080/solr

The example at that gem I linked shows:

development:   
  solr:
    host: localhost
    port: 8982
    path: /solr
    user: theuser
    password: thepassword
    log_level: INFO

Would I have to rewrite my solr.yml to reflect this format or could I just have?

production:
    url: http://127.0.0.1:8080/solr
    user: theuser
    password: thepassword

**Comment by cbeer** [comment]
Blacklight uses the RSolr gem to talk to your Solr service, and should pass all keys through to  `RSolr.connect`. It looks like RSolr supports HTTP basic auth natively:

https://github.com/rsolr/rsolr/blob/master/lib/rsolr/connection.rb#L61

this may be as easy as:

```yaml
production:
  url: http://theuser:thepassword@127.0.0.1:8080/solr
```

**Comment by jjmamtora** [comment]
Hi,

I am using solr 7.5 and I want to protect solr admin panel using username and password.

Could you please help me out for windows and ubuntu platform? I am using it on both the platform.

Thanks..
