### ISSUE TITLE
Quick Start / Hydra Solr?

### ISSUE THREAD

**Issue by ewlarson** [projectblacklight/blacklight#1379]
Hello hello.  I ran through the BL quick start script today and surprisingly ended up with the Hydra project's solr install (schema/config, etc.), so indexing blacklight's example marc records did not work.

Ran this command:
$ rails new search_app -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb

Somewhere during this install script, the jetty:clean task seems to ignore the local ZIP_URL value pointing to blacklight-jetty and ends up with hydra-jetty instead.  Hope it's an easy fix.

**Comment by cbeer** [comment]
I'm not sure I understand how that would happen -- is it possible you had a running hydra-jetty instance already running elsewhere?

**Comment by ewlarson** [comment]
Thanks for the reply.  No, I've never run the Hydra stack on this laptop
before.  If you can't reproduce it, perhaps you need a fresh machine to
replicate the bug?  Or maybe I just got unlucky on that one?  Either way,
thought you guys would want to know.

**Comment by lbast3** [comment]
Jettywrapper uses hydra-jetty by default.
It can be configured to work with any Jetty-based zip file, such as blacklight-jetty.

Workaround:
- Download blacklight-jetty zipfile
- Create environment variable JETTY_ZIP and refer to this zip file.
     $ export JETTY_ZIP=[full path to zipfile] 
- $ rails new search_app -m ...

Maybe there is a more elegant solution ?

Kind regards

**Comment by adjam** [comment]
Can confirm, by default on a clean machine, provisioned from scratch in Vagrant, 6.0.1 will install the jetty from the Hydra project, and 

`rake solr:marc:index_test_data`

fails due to a missing core: 

(HTML response: ```<p>Problem accessing /solr/blacklight-core/update. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty:/```

**Comment by mejackreed** [comment]
We had something similar happen in the GeoBlacklight workshop recently. Could never figure out what the cause was.

**Comment by jcoyne** [comment]
All Blacklight development has moved from jetty-wrapper to solr_wrapper. Someone shook update the quickstart too.


Justin

**Comment by chrxr** [comment]
Hi there. Any update on a workaround for this issue? Or an updated Quickstart guide?

**Comment by natehill** [comment]
None of this is working for me.  An updated quickstart would be really helpful, or some clear step-by-step instructions in this thread would do as well.

**Comment by barmintor** [comment]
Cf #1868

**Comment by barmintor** [comment]
The quickstart has been updated to use solr_wrapper; issues with the v7.0 quickstart are being tacked in another ticket.
