### ISSUE TITLE
A facet without a limit only shows 10 values

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1381]
and it doesn't show "more >>" link

**Comment by cbeer** [comment]
How do you think we should handle this? Always invoke the facet pagination logic?

**Comment by jcoyne** [comment]
I think we can handle this as a comment in the catalog_controller.rb template.

**Comment by barmintor** [comment]
Documented fix in https://github.com/projectblacklight/blacklight/commit/3aa964bf9f9911e5fd3f594c214a7afa115790e9
