### ISSUE TITLE
error with Creating a new application the hard way, step 2

### ISSUE THREAD

**Issue by alawvt** [projectblacklight/blacklight#1391]
I am setting up for the class next week. I've run through the steps until error with Creating a new application the hard way, step 2

```
alaw:~/projects/my_new_blacklightapp$ gem 'blacklight', ">= 5.3.0"
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command blacklight,
```

**Comment by cbeer** [comment]
You should be adding the line `gem 'blacklight', '>= 5.3.0'` to your Gemfile, not trying to execute it from the shell.

**Comment by alawvt** [comment]
thanks!
