### ISSUE TITLE
Update default installer/generators to use solr5

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/blacklight#1396]
Currently the default install process installs solr4 when the `jettywrapper` option is passed
* [Template Installer](https://github.com/projectblacklight/blacklight/blob/e3c72d5795ff72523703dec7242eccc23d8f78d4/template.demo.rb#L9)
* [Install Generator](https://github.com/projectblacklight/blacklight/blob/e3c72d5795ff72523703dec7242eccc23d8f78d4/lib/generators/blacklight/install_generator.rb#L30-L31)

This causes solr4 to be installed using either the template installer or by manually installing Blacklight "the hard way".

We should update to use solr5 by default (which should probably be in a minor release).

**Comment by guoyoujun** [comment]
I just make solr 5.5 work with blacklight 5.18.0
the key steps are after installing solr:
1. copy missing jars  from solr5/contrib/analysis-extras/lucene-libs/* and solr5/contrib/analysis-extras/libs/* into solr5/server/solr-webapp/webapp\WEB-INF/lib/

2. modify solrconfig.xml by adding requestHandlers needed by blacklight. There are maybe dozen of them. 

3. modify managed_schema by adding  the field definitions which used by blacklight

**Comment by cbeer** [comment]
Fixed in 7dceaf371a16f3aec37ee7bdc5fb61ba24cbcb87
