### ISSUE TITLE
demo.projectblacklight.org is down.

### ISSUE THREAD

**Issue by dannyrose42** [projectblacklight/blacklight#1400]
Not sure if this is the right place to report this but just letting you know. 

![image](https://cloud.githubusercontent.com/assets/5464924/14497689/46e7ee1a-015d-11e6-8104-57c195818dae.png)

**Comment by cbeer** [comment]
Thanks, I'll report it to the appropriate people.

**Comment by cbeer** [comment]
Thanks, we're back up again.
