### ISSUE TITLE
Suggestions are funky

### ISSUE THREAD

**Issue by cam156** [projectblacklight/blacklight#1401]
With blacklight-5.16.3 I get a really funky spelling suggestion:

![screen shot 2016-04-13 at 11 34 15 am](https://cloud.githubusercontent.com/assets/1599081/14499300/bac099d2-016b-11e6-8310-41134e662fc6.png)

after changing code in app/catalog/_did_you_mean.html.erb locally to: (see word["word"])

```
 <h4 class="suggest"><em><%= t('blacklight.did_you_mean', :options => safe_join(@response.spelling.words.map { |word| link_to_query(word["word"]) }, " #{t('blacklight.or')} ")).html_safe %></em></h4>
```

I get expected result:
![screen shot 2016-04-13 at 11 34 03 am](https://cloud.githubusercontent.com/assets/1599081/14499304/bc644202-016b-11e6-9b9d-0d85c00ed1de.png)

**Comment by tampakis** [comment]
The Solr response format for spelling suggestions changed in Solr 5. In Blacklight 6.x the spelling suggestion code was updated to reflect Solr 5 syntax: https://github.com/projectblacklight/blacklight/blob/6212647c3b73258d2df7daea4f77e42c497829dc/lib/blacklight/solr/response/spelling.rb#L63
