### ISSUE TITLE
MARC import error (undefined method 'extract_marc')

### ISSUE THREAD

**Issue by atiro** [projectblacklight/blacklight#1406]
Running solr:marc:index on some records is throwing an import error:
``
2016-05-10T14:54:02+00:00  INFO    Traject::SolrJsonWriter writing to 'http://127.0.0.1:8983/solr/blacklight-core/update/json' in batches of 100 with 1 bg threads
2016-05-10T14:54:02+00:00  INFO    Indexer with 1 processing threads, reader: Traject::MarcReader and writer: Traject::SolrJsonWriter
2016-05-10T14:54:02+00:00 ERROR Unexpected error on record id`ocm10362455/ocm10362455`at file position 16
    while executing (to_field format at /opt/projects/search_app/app/models/marc_indexer.rb:23)
    Exception: NoMethodError: undefined method`extract_marc' for Blacklight::Marc::Indexer::Formats::FormatMap:Module
    /var/lib/gems/2.3.0/gems/blacklight-marc-6.1.0/lib/blacklight/marc/indexer/formats.rb:142:in `map_leader'

rake aborted!
NoMethodError: undefined method `extract_marc' for Blacklight::Marc::Indexer::Formats::FormatMap:Module
/var/lib/gems/2.3.0/gems/blacklight-marc-6.1.0/lib/blacklight/marc/indexer/formats.rb:142:in`map_leader'
/var/lib/gems/2.3.0/gems/blacklight-marc-6.1.0/lib/blacklight/marc/indexer/formats.rb:177:in `block in get_format'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/indexer/step.rb:144:in`execute'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/indexer.rb:346:in `block (2 levels) in map_to_context!'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/indexer.rb:400:in`log_mapping_errors'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/indexer.rb:345:in `block in map_to_context!'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/indexer.rb:339:in`each'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/indexer.rb:339:in `map_to_context!'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/indexer.rb:474:in`block (2 levels) in process'
/var/lib/gems/2.3.0/gems/traject-2.3.1/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in`run_task'
/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in`loop'
/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in`catch'
/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Tasks: TOP => solr:marc:index => solr:marc:index:work
(See full trace by running task with --trace)
``

This is a clean install of Blacklight following the 'hard way' instructions running on 

ruby 2.3.0p0 
Rails 4.2.6

The record causing the error is (in marcxml):
`
<record>
    <leader>01158nas a2200337   4500</leader>
    <controlfield tag="001">ocm10362455</controlfield>
    <controlfield tag="008">880505c19849999kyuqr1p  bo   0uuua0eng d</controlfie  ld>
    <datafield tag="010" ind1=" " ind2=" ">
      <subfield code="a">   84645929 //r87</subfield>
      <subfield code="z">sn 84005944</subfield>
    </datafield>
    <datafield tag="022" ind1="0" ind2=" ">
      <subfield code="a">0742-5473</subfield>
    </datafield>
    <datafield tag="040" ind1=" " ind2=" ">
      <subfield code="a">NSD</subfield>
      <subfield code="c">NSD</subfield>
      <subfield code="d">DLC</subfield>
      <subfield code="d">NST</subfield>
      <subfield code="d">DLC</subfield>
      <subfield code="d">NST</subfield>
      <subfield code="d">NSD</subfield>
      <subfield code="d">NST</subfield>
      <subfield code="d">AIP</subfield>
      <subfield code="d">HUL</subfield>
      <subfield code="d">NST</subfield>
      <subfield code="d">IUL</subfield>
      <subfield code="d">NST</subfield>
      <subfield code="d">m/c</subfield>
      <subfield code="d">NST</subfield>
      <subfield code="d">DLC</subfield>
      <subfield code="d">AVA</subfield>
    </datafield>
  <datafield tag="042" ind1=" " ind2=" ">
      <subfield code="a">lc</subfield>
      <subfield code="a">nsdp</subfield>
    </datafield>
    <datafield tag="049" ind1=" " ind2=" ">
      <subfield code="a">AVAR</subfield>
    </datafield>
    <datafield tag="050" ind1="0" ind2=" ">
      <subfield code="a">PR4579</subfield>
      <subfield code="b">.D495</subfield>
    </datafield>
    <datafield tag="082" ind1="0" ind2=" ">
      <subfield code="a">823/.8</subfield>
      <subfield code="2">19</subfield>
    </datafield>
    <datafield tag="210" ind1="0" ind2=" ">
      <subfield code="a">Dickens q.</subfield>
    </datafield>
    <datafield tag="222" ind1="0" ind2="0">
      <subfield code="a">Dickens quarterly</subfield>
    </datafield>
    <datafield tag="245" ind1="0" ind2="0">
      <subfield code="a">Dickens quarterly.</subfield>
    </datafield>
    <datafield tag="260" ind1="0" ind2="0">
      <subfield code="a">Louisville, Ky. :</subfield>
      <subfield code="b">Dickens Society,</subfield>
      <subfield code="c">c1984-</subfield>
    </datafield>
    <datafield tag="300" ind1=" " ind2=" ">
      <subfield code="a">v. ;</subfield>
      <subfield code="c">23 cm.</subfield>
    </datafield>
    <datafield tag="310" ind1=" " ind2=" ">
      <subfield code="a">Quarterly</subfield>
    </datafield>
    <datafield tag="362" ind1="0" ind2=" ">
      <subfield code="a">Vol. 1, no. 1 (Mar. 1984)-</subfield>
    </datafield>
    <datafield tag="500" ind1=" " ind2=" ">
      <subfield code="a">Title from cover.</subfield>
    </datafield>
  <datafield tag="510" ind1="2" ind2=" ">
      <subfield code="a">Abstracts of English studies</subfield>
      <subfield code="x">0001-3560</subfield>
    </datafield>
    <datafield tag="510" ind1="2" ind2=" ">
      <subfield code="a">MLA international bibliography of books and articles on   the modern languages and literatures (Complete edition)</subfield>
      <subfield code="x">0024-8215</subfield>
    </datafield>
    <datafield tag="600" ind1="1" ind2="0">
      <subfield code="a">Dickens, Charles,</subfield>
      <subfield code="d">1812-1870</subfield>
      <subfield code="x">Periodicals.</subfield>
      <subfield code="w">1n</subfield>
    </datafield>
    <datafield tag="690" ind1=" " ind2=" ">
      <subfield code="a">Periodicals and transactions</subfield>
      <subfield code="z">British Isles.</subfield>
    </datafield>
    <datafield tag="710" ind1="2" ind2="0">
      <subfield code="a">Dickens Society.</subfield>
      <subfield code="w">cn</subfield>
    </datafield>
    <datafield tag="780" ind1="0" ind2="0">
      <subfield code="t">Dickens studies newsletter</subfield>
      <subfield code="x">0012-2432</subfield>
    </datafield>
    <datafield tag="910" ind1=" " ind2=" ">
      <subfield code="a">NEW</subfield>
    </datafield>
    <datafield tag="949" ind1="0" ind2="0">
      <subfield code="a">0</subfield>
      <subfield code="b">L.1090-1984</subfield>
      <subfield code="d">PP.13.G</subfield>
    </datafield>
 <datafield tag="999" ind1=" " ind2=" ">
      <subfield code="a">9727</subfield>
  </datafield>
`
Seems to be a problem with any record for a journal/newsletter ?

**Comment by atiro** [comment]
Managed to fix this by including Traject::Macros::Marc21 directly in the FormatMap module and modifying the call to Traject::Macros::Marc21.extract_marc

Possibly the module should be inheriting it instead though ?

**Comment by jamesrf** [comment]
I had the same issue, I think it resolved by an open PR blacklight-marc, I've commented to that effect there:

https://github.com/projectblacklight/blacklight-marc/issues/32
https://github.com/projectblacklight/blacklight-marc/pull/37

**Comment by abidfakhrealam** [comment]
WHILE IMPORTING MARC DATA INTO BLACKLIGHT BY FOLLOWING COMMAND 
rake solr:marc:index MARC_FILE=/home/discovery/Downloads/koha.mrc
 
I got following error: 

2018-04-03T20:38:31+05:30 ERROR Could not add record  at source file position 26949: Solr error response: 400: {
  "responseHeader":{
    "status":400,
    "QTime":0},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"Document is missing mandatory uniqueKey field: id",
    "code":400}}

2018-04-03T20:38:31+05:30 ERROR Could not add record  at source file position 26950: Solr error response: 400: {
  "responseHeader":{
    "status":400,
    "QTime":0},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"Document is missing mandatory uniqueKey field: id",
    "code":400}}

2018-04-03T20:38:31+05:30  WARN Traject::SolrJsonWriter: 26965 skipped records
2018-04-03T20:38:31+05:30  INFO Traject::SolrJsonWriter sending commit to solr at url http://127.0.0.1:8983/solr/blacklight-core/update/json...
2018-04-03T20:38:31+05:30  INFO finished Indexer#process: 26965 records in 60.033 seconds; 449.2 records/second overall.
2018-04-03T20:38:31+05:30 ERROR Indexer#process returning 'false' due to 26965 skipped records.

**Comment by barmintor** [comment]
Closing since the PR referenced by @jamesrf above was merged and released in blacklight-marc v6.2.0
