### ISSUE TITLE
Instructions for custom document index titles don't work

### ISSUE THREAD

**Issue by mel-mason** [projectblacklight/blacklight#1409]
The Configuration Results View wiki page gives [instructions](https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#title_field) to make the document titles on the index page a concatenation of two fields. The instructions are contradictory - the code example overrides `render_document_index_label`, but the text above it suggests overriding `document_heading`. Neither suggestion works correctly:
- `Document_heading` controls only the title on the show page, not on the index page.
- Overriding `render_document_index_label` changes the index page headings, but breaks thumbnails - thumbnail rendering depends on `render_document_index_label` returning the thumbnail image tag string unaltered.

Checking in `render_document_index_label` if the `field` parameter is a string and not altering it if so solves the thumbnail problem. (Note: this only works if you also set `config.index.title_field` in CatalogController, otherwise `field` will always be a string). But it's rather unintuitive, and took a while to figure out.

**Comment by barmintor** [comment]
This documentation has been updated in-line with currently released versions of Blacklight.
