### ISSUE TITLE
Refactor DocumentPresenter

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1414]
It appears that the `DocumentPresenter` could be decomposed into some of the following components:

```
FieldPresenter
HTMLTitlePresenter
DocumentHeadingPresenter
IndexLabelPresenter
```
These all would have dependencies on a `FieldRetriever` and `FieldRenderer`

**Comment by jrochkind** [comment]
Will that make it harder for app developers to figure out how to customize, so many classes involved? What are the benefits to developers (app or BL)?

**Comment by jcoyne** [comment]
Currently it's an impossible mess. It needs to do a better job of encapsulating the individual responsibilities. This will make it easier to inject the behavior you require.
