### ISSUE TITLE
bump devise-guests version

### ISSUE THREAD

**Issue by atz** [projectblacklight/blacklight#1428]
The generated dependency on devise-guests is sem-ver `~> 0.3`:
https://github.com/projectblacklight/blacklight/blob/v6.3.0/lib/generators/blacklight/user_generator.rb#L26

There are a half dozen releases since then.  We can bring that up to `~> 0.5` without shifting any of the underlying dependency compatibility, while delivering a more uniform and current base.

**Comment by cbeer** [comment]
Sounds reasonable to me, especially as it's in a generator and won't affect existing applications at all. Would you mind creating a pull request for the change?

**Comment by atz** [comment]
Sure, not top priority, but I'd be happy to.

**Comment by atz** [comment]
Can you add me to this project or otherwise assign me the ticket?
