### ISSUE TITLE
Solr 6 support?

### ISSUE THREAD

**Issue by woodruffw** [projectblacklight/blacklight#1441]
Does Blacklight 6.x support the Solr 6.x tree?

I'm running Solr 6.0.1 with document ingestion from ManifoldCF, and I get a `NoMethodError` in `CatalogController#index` (tracing back to `Search.none`) when performing any sort of search:

*app/controllers/concerns/blacklight/controller.rb:94*:
```ruby
def searches_from_history
  session[:history].blank? ? Search.none : Search.where(:id => session[:history]).order("updated_at desc")
end
```

I'm familiar with Ruby but not as much with RoR, so I may be way off base here. 

Thanks in advance.

**Comment by jcoyne** [comment]
`Search.none` is a method provided by ActiveRecord here: https://github.com/rails/rails/blob/f45d06e11fdacf45df55b7b6f20b4987fe367109/activerecord/lib/active_record/relation/query_methods.rb#L782-L784

Which version of Rails are you using?

**Comment by woodruffw** [comment]
`rails -v` says 5.0.0.

**Comment by woodruffw** [comment]
Some other strangeness: Attempting to log into a devise account (created via the Rails console) results in another `NoMethodError` in `Catalog#index`, this time with `relation_delegate_class` (for `Search`):

*lib/active_record/relation/delegation.rb:106*:
```ruby
def relation_class_for(klass)
  klass.relation_delegate_class(self)
end
```

**Comment by jcoyne** [comment]
All those problems you are experiencing are deeper in the stack, in Rails itself, not in Blacklight. I'm not sure I can be of help to you.

**Comment by woodruffw** [comment]
Yeah, that's what I was afraid of. Do you have any version recommendations for a stable Rails/Blacklight/Solr combination?

**Comment by jcoyne** [comment]
Running Rails 5, blacklight 6.3.1 and Solr 6.1.0 is working for me.

**Comment by woodruffw** [comment]
Alright, thank you for all your help!
