### ISSUE TITLE
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators/actions.rb:26:in `gem': can't modify frozen String (RuntimeError

### ISSUE THREAD

**Issue by krinkere** [projectblacklight/blacklight#1443]
Anyone else is getting this error?

rails --version
Rails 4.2.4

ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by jcoyne** [comment]
It looks like you're hitting this bug:

https://github.com/rails/rails/issues/23137

-Justin

**Comment by krinkere** [comment]
Seems to be... the bug that you mentioned marked as closed, yet I did not see it as being actually resolved?

**Comment by krinkere** [comment]
Anyway, just switched to ruby 2.2 and I was able to run 
rails new search_app -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb

command.

**Comment by jcoyne** [comment]
I'd also give rails 4.2.6 a try in conjunction with ruby 2.3. The issue was fixed in this PR: https://github.com/rails/rails/pull/23216

**Comment by jcoyne** [comment]
Looks like the fix went into the 5.0 branch of Rails, not the 4.2 branch.  You could probably backport it and submit a PR.

**Comment by krinkere** [comment]
Ah nice. Thank you.
I am using ruby 2.2 and rails 5 now, so it is working, and for what I am doing 2.2 is fine. Thanks again for the help and the link
