### ISSUE TITLE
If fetch_many is called with a lot of ids, it produces a Solr URL that is too long

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1451]
https://github.com/projectblacklight/blacklight/blob/289c3376591a343d6e0a9c4876cea5094ac521aa/app/controllers/concerns/blacklight/search_helper.rb#L156

Instead we should force it to post if the number of requested ids exceeds a threshold (maybe 200?).

**Comment by atz** [comment]
Or just post all the time.

**Comment by mejackreed** [comment]
Agree that `POST` all of the time is optimal here. I think sometimes that makes Solr logs difficult to read and is the reason why some may want to keep the `GET` option.

**Comment by jkeck** [comment]
I think the root of the issue is, it would be useful for those that would like to get useful information out of solr logs (using `GET` requests) could still use this feature without throwing errors for users when bookmarking large numbers of records.

**Comment by cbeer** [comment]
Sending `POST` requests in the bookmarks controller (by default) seems pretty reasonable to me, although I wouldn't do it for the catalog controllers for the reason @jkeck mentioned.

**Comment by cbeer** [comment]
Fixed by #1468
