### ISSUE TITLE
'separator' option on config.add_index_field does not effect output

### ISSUE THREAD

**Issue by chrxr** [projectblacklight/blacklight#1454]
The separator option on `config.add_index_field` or `config.add_show_field`, [as defined in the wiki](https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#fields
), does not seem to have any effect on the eventual output. Multivalued fields continue to be output with commas, 'and', no matter what is entered as the separator.

For example:     

    config.add_show_field 'artifact_provenance', label: 'Provenance', separator:"; "

this has no effect on the separator for the artifact_provenance multivalued field.

**Comment by cbeer** [comment]
Looks like some out-of-date documentation, I'll fix it up soon.

In Blacklight 6.x, we switched to using [`Array#to_sentence`](http://apidock.com/rails/Array/to_sentence) from Rails, e.g.:

```ruby
config.add_show_field 'artifact_provenance', label: 'Provenance', separator_options: { words_connector: '; ' }
```
