### ISSUE TITLE
Can't work on a multivalued field as a list

### ISSUE THREAD

**Issue by chrxr** [projectblacklight/blacklight#1455]
We would like to display multivalued fields as a list of items rather than a concatenated string, so that we can display each on a separate line in the front-end. 

Is there an option for this? I can't seem to find anyway to opt out of the automatic concatenation of multivalued fields.

**Comment by mejackreed** [comment]
Hi @chrxr . Have you seen the "Custom Helper Method" section over here: http://jessiekeck.com/customizing-blacklight/metadata_fields/

I think that might be what you are looking for.

**Comment by chrxr** [comment]
Thanks @mejackreed that did indeed help. Just returning the values with the helper_method seemed to do it:

      def list_multivalue options={}
        options[:value]
      end

**Comment by mejackreed** [comment]
Nice! Sorry you banged up against that.
