### ISSUE TITLE
Quickstart won't run on a 'fresh' Ubuntu 16 machine

### ISSUE THREAD

**Issue by viktorsmari** [projectblacklight/blacklight#1459]
Ubuntu 16.04.01
Ruby 2.3.1p112
Rails 4.2.6

When running:
`rails new search_app -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb`

I get this error msg:

> 
     create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
       apply  https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb
/usr/lib/ruby/vendor_ruby/rails/generators/actions.rb:26:in `gem': can't modify frozen String (RuntimeError)
	from https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb:2:in `apply'
	from /usr/lib/ruby/vendor_ruby/thor/actions.rb:223:in `instance_eval'
	from /usr/lib/ruby/vendor_ruby/thor/actions.rb:223:in `apply'
	from /usr/lib/ruby/vendor_ruby/rails/generators/app_base.rb:143:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `each'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `map'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:133:in `invoke_all'
	from /usr/lib/ruby/vendor_ruby/thor/group.rb:232:in `dispatch'
	from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
	from /usr/lib/ruby/vendor_ruby/rails/commands/application.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/rails/cli.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/bin/rails:9:in `<main>'
ubuntu@ubu2:~/blacklight$ ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
ubuntu@ubu2:~/blacklight$ rails --version
Rails 4.2.6
ubuntu@ubu2:~/blacklight$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by jcoyne** [comment]
I think this is this bug: https://github.com/rails/rails/issues/23137
which is only present if you use Ruby 2.3 and Rails 4. Have you tried using
Rails 5 instead?

-Justin

**Comment by viktorsmari** [comment]
It works when I run the following:

`rails _5.0.0.1_ new  search_app -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb`

**Comment by jcoyne** [comment]
@viktorsmari Excellent. That's good to hear. We may have fixed the problem with Rails 4.2 if you are still concerned about that.

**Comment by viktorsmari** [comment]
Yeah I noticed the merge, nice work! :+1:
