### ISSUE TITLE
Restyle active facets cards

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight#1499]
In Bootstrap 4, cards with the success border are... less subtle:

![screen shot 2016-09-11 at 6 20 14 pm](https://cloud.githubusercontent.com/assets/111218/18422212/7203d6f2-784c-11e6-9e08-7f3401507423.png)

Looking at a sampling of the sites listed at projectblacklight.org, it seems like most are removing that styling entirely. Maybe we can just drop it?

**Comment by mejackreed** [comment]
I wonder if this can't be more easily configurable. Out of the box, I like the fact that Blacklight offers this. But could offer it in a more configurable way?

**Comment by cbeer** [comment]
👌 I generally like it too, although if a sizable smattering of installs are removing it, shipping with the DOM classes available but unstyled would be useful for them.

I guess we could also be clever and check if a sass variable is defined (for the background and text) and use that to decide whether to style the card or not.

**Comment by cbeer** [comment]
Fixed by #1497
