### ISSUE TITLE
Blacklight 6.7.0 breaks blacklight-access-controls

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1534]
https://travis-ci.org/projectblacklight/blacklight-access_controls/jobs/163301845

**Comment by cbeer** [comment]
Blacklight-access-controls does something kinda weird:

https://github.com/projectblacklight/blacklight-access_controls/blob/474e939945893e515a7833030df63856aeb5a723/lib/blacklight/access_controls/permissions_query.rb#L33

That module seems ripe for refactoring...

In the meantime, #1535 ought to fix the behavior, although I think we ought to deprecate it.

**Comment by jcoyne** [comment]
Thanks @cbeer
