### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#1543]
| Locale | Key | Value in other locales or source |
| --- | --- | --- |
| de | blacklight.search.facets.missing | en [Missing] |
| it | blacklight.search.facets.missing | en [Missing] |
| pt-BR | blacklight.search.facets.missing | en [Missing] |

**Comment by jcoyne** [comment]
@andresmrm would you be able to help us out with the Portuguese?

**Comment by jcoyne** [comment]
@lpugin Can you help us translate "missing" (as in: "this facet is missing from the Solr result") to Italian?

**Comment by cbeer** [comment]
I think `blacklight.search.facets.missing` is a little more nuanced than that -- rather more like "if you click on this label to see all documents for this search that have no values for the facet field"

**Comment by andresmrm** [comment]
Sure! PR sent!

**Comment by lpugin** [comment]
will do asap

**Comment by barmintor** [comment]
@simosacchi might be able to help with it?

**Comment by simosacchi** [comment]
@jcoyne @barmintor In the context/example provides above "is missing" can be translated in Italian as "manca" or "è mancante" or "non compare". (i.e. the English sentence "this facet is missing from the Solr result", it Italian would be something like "questa faccetta non compare nei risultati di Solr" or "questa faccetta manca dai risultati di Solr" ). 

Ping me if this is not what you were looking for.

**Comment by barmintor** [comment]
Fixed in https://github.com/projectblacklight/blacklight/commit/463914d5c15be5b3182918e73d629ca447eed3f5
