### ISSUE TITLE
facet and search labels do not translate

### ISSUE THREAD

**Issue by cam156** [projectblacklight/blacklight#1550]
When I translate the page the facet labels and search fields do not translate.

I know this is a feature, but it would be nice to I18N the Facet and Search labels.

![screen shot 2016-10-18 at 7 51 21 am](https://cloud.githubusercontent.com/assets/1599081/19476540/b9ae95aa-9507-11e6-889b-656b727fa0b4.png)

**Comment by jcoyne** [comment]
I rink these are i18n, we just don't have translations so it's falling back to en

**Comment by cbeer** [comment]
@jcoyne is absolutely right, and I should have asked for those translations in my email.

https://github.com/projectblacklight/demo.projectblacklight.org/blob/master/config/locales/en.yml

**Comment by cbeer** [comment]
I've added application locale files for `de`, `fr`, and `es`: https://github.com/projectblacklight/demo.projectblacklight.org/tree/master/config/locales
