### ISSUE TITLE
autocomplete not working on demo site

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#1551]

**Comment by cbeer** [comment]
I'm not sure we've ever indexed content into the autocomplete field.

We're using this sold configuration: https://github.com/projectblacklight/demo.projectblacklight.org/tree/master/solr/conf

And this rake task:
https://github.com/projectblacklight/blacklight-marc/blob/master/lib/railties/solr_marc.rake#L41

**Comment by mejackreed** [comment]
Yeah that's part of it. Other part is that the search form is returning the wrong url for the suggest path
