### ISSUE TITLE
Search submit button styling is off on mobile view

### ISSUE THREAD

**Issue by ronan-mch** [projectblacklight/blacklight#1552]
Using Galaxy S5 setting on Google Chrome. Search submit button is too small and has lost its text.

![demo projectblacklight org- galaxy s5](https://cloud.githubusercontent.com/assets/1145457/19492541/5a98f46e-9577-11e6-8d7f-4a586f227b28.png)

**Comment by cbeer** [comment]
Bootstrap 4 dropped the glyphicon font we were using for this icon and for the view style selector. In the short-term, I suppose we should either glyphicon ourselves or grab an SVG-equivalent for these (pulling in a huge font for ~5 glyphs seems... overkill)?

**Comment by mejackreed** [comment]
something like octicons maybe?
