### ISSUE TITLE
Enabling turbolinks corrupts search nav rendering when hitting back button 

### ISSUE THREAD

**Issue by codeforkjeff** [projectblacklight/blacklight#1562]
Starting in v6.3.0, enabling turbolinks causes the browser rendering of the "for-search-field" span in the search navigation to be messed up when you click the browser back button. It appears too tall.

![blacklight_search_nav_bug](https://cloud.githubusercontent.com/assets/615941/19730176/5a43dd80-9b67-11e6-8cba-12ca89295da8.png)

You can reproduce this in the demo environment, using both Firefox and Chrome: http://demo.projectblacklight.org
- search for any keyword (e.g. "literature")
- click Next twice to browse results
- click the browser back button
- you should see the messed up search dropdown, as in the screenshot above

This does not happen in v6.2.0. I think this issue was introduced in commit 50a635cff1ed1b37ac16b7bad2c992c6c31d2af8

The workaround is to disable turbolinks. Not sure what the root cause of this is, as I'm not very familiar with turbolinks, and once I looked into what it was, I decided to turn it off for my project anyway.

**Comment by cbeer** [comment]
There's an open pull request to fix this: https://github.com/projectblacklight/blacklight/pull/1541

**Comment by cbeer** [comment]
Make that a merged pull request to fix that.

**Comment by codeforkjeff** [comment]
Thanks Chris!
