### ISSUE TITLE
Add an upgrading Blacklight from Bootstrap 3 to 4 guide

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#1575]

**Comment by atz** [comment]
Did we do a Bootstrap 2 -> 3 guide?  Something to start from or at least point to for folks doing a larger update.

**Comment by mejackreed** [comment]
@atz I don't think so but this is usually my goto when upgrading: http://getbootstrap.com/migration/

**Comment by cbeer** [comment]
Indeed, the upstream documentation is usually pretty good. We noted the need, blacklight-specific notes, and links to the major changes as part of the release notes: https://github.com/projectblacklight/blacklight/releases/tag/v5.0.0

**Comment by mejackreed** [comment]
Ah yes of course that. Most definately a great resource when upgrading.
