### ISSUE TITLE
Deprecation: ActiveRecord::Migration inheritance

### ISSUE THREAD

**Issue by atz** [projectblacklight/blacklight#1576]
Warning on downstream builds against rails `5.0.0.1`, for example:

```
DEPRECATION WARNING: Directly inheriting from ActiveRecord::Migration is deprecated. 
Please specify the Rails release the migration was written for:
```
```ruby
  class CreateSearches < ActiveRecord::Migration[4.2]
```

Some examples start at: https://travis-ci.org/projectblacklight/blacklight_range_limit/builds/153589181#L711

**Comment by cbeer** [comment]
Rails 4.2 doesn't have support for the compatibility version in migrations, so we'll either have to maintain two separate sets of migrations or accept the (relatively harmless..) deprecation warning until we can drop Rails 4.2.

**Comment by atz** [comment]
Ok, that makes sense.  I guess we can leave this as a reminder to clean that up when 4.2 is dropped.
