### ISSUE TITLE
Librarian View is missing some styles

### ISSUE THREAD

**Issue by sandbergja** [projectblacklight/blacklight#1580]
When I try to do a stock install of master, index the sample MARC files, and open up the "Librarian View", the MARC view has much more whitespace than it should.  I've attached an image of what I'm seeing.  Thanks for your help with this!

![librarian_view](https://cloud.githubusercontent.com/assets/7086943/19967198/7e03d998-a18c-11e6-9f37-7b1869a6c094.png)

**Comment by jcoyne** [comment]
I think this is just drawing a bunch of HTML with no values in it:

<img width="928" alt="screen shot 2016-11-03 at 9 20 15 am" src="https://cloud.githubusercontent.com/assets/92044/19967507/022fb484-a1a7-11e6-949a-43c59a2370ce.png">

I suspect it's always worked this way, but I have no objections to changing it.

**Comment by cbeer** [comment]
It used to be "better", e.g:

<img width="570" alt="screen shot 2016-11-03 at 6 26 47 am" src="https://cloud.githubusercontent.com/assets/111218/19967658/8a441022-a18e-11e6-83b9-a8aba3487960.png">

**Comment by cbeer** [comment]
Ah, I know. It looks like I've disabled the blacklight marc styles until it is updated for bootstrap 4 compatibility?

https://github.com/projectblacklight/demo.projectblacklight.org/blob/master/app/assets/stylesheets/blacklight.scss#L4

**Comment by barmintor** [comment]
@cbeer so this is really a `blacklight-marc` ticket? I know we need to have working examples for 7.0, just want to know where the work is required.

**Comment by barmintor** [comment]
@sandbergja Below is a picture from the blacklight-marc 7.0.0 RC. Will this close the issue when publicly available?
<img width="815" alt="librarian-view-7" src="https://user-images.githubusercontent.com/119860/47673846-235cf880-db8c-11e8-9c26-6aa9e7297fe8.png">

**Comment by sandbergja** [comment]
Yeah, I think so!  Thanks for your work on this, all!

**Comment by barmintor** [comment]
Closed via blacklight-marc 7.0-RC1
