### ISSUE TITLE
Opensearch configuration bug

### ISSUE THREAD

**Issue by idanstark42** [projectblacklight/blacklight#1587]
When I tried to configure my opensearch to use a different title_field from the index view, I ran into trouble.
In my catalog_controller.rb I wrote:
```
configure_blacklight do |config|
    ...
   config.view['opensearch'] = { title_field: 'my_title_field' }
    ...
end
```
but blacklight doesn't seem to mind it.
After a lot of digging I found out that the OpenStruct class from which config inherits, turns all of it's keys into symbols, while  blacklight uses a string to get the opensearch configuration, in search_helper.rb in the method get_opensearch_response:
   `field ||= blacklight_config.view_config('opensearch').title_field`
In order to work, this line should be:
   `field ||= blacklight_config.view_config(:opensearch).title_field`
Thank you all for constructing blacklight! It's a pleasure to use and develop with it!

**Comment by atz** [comment]
I suppose we could make `view_config` call `to_sym` on its argument also.

**Comment by idanstark42** [comment]
Thank you, that'll do it
