### ISSUE TITLE
More facet window will not close.

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1641]
1. Go to http://demo.projectblacklight.org/
1. Click "Topic" to expand the facet
1. Click "more"
1. On the popup window press "Next"
1. Now attempt to close the popup (click the "X")

<img width="1432" alt="screen shot 2017-03-06 at 3 47 01 pm" src="https://cloud.githubusercontent.com/assets/92044/23635385/5637e7ca-0284-11e7-9ee1-f4e47895b557.png">

Probably related to: https://github.com/twbs/bootstrap/issues/21607

**Comment by group99001** [comment]
i see you are already fixed your issue , plz tell me how this issue fixed?

**Comment by jcoyne** [comment]
Seems to work on Bootstrap 4 beta2.
