### ISSUE TITLE
Searches table grows uncontrollably; is there a better solution than manual/scheduled deletion?

### ISSUE THREAD

**Issue by dmolesUC3** [projectblacklight/blacklight#1652]
We recently were warned by our IT department that our database server was running out of disk space, and eventually found that the culprit was Blacklight's `searches` table, which in less than four months of uptime had grown to 2.5 GB and 8.5 million rows.

Searching the mailing list archives, it's clear this is a [long-standing problem](https://groups.google.com/forum/#!topic/blacklight-development/1ZH5YYUCorU). I'm aware there's a [rake task](https://github.com/projectblacklight/blacklight/blob/master/lib/railties/blacklight.rake#L7-L11) for dealing with this, but I assume we're not the only publicly accessible site that gets tens of thousands of bot hits per day. We're probably not even going to bother with the rake task ourselves, just create a cron job to truncate the table daily or weekly. Surely there's some way sessions could be made to clean up after themselves?

**Comment by tampakis** [comment]
We have this issue too and we set up a cron job to run the rake task nightly to delete searches and the guest users if they are more than 7 days old.

**Comment by jcoyne** [comment]
@dmolesUC3 the scheduled cron job is the best idea we have so far. Feel free to open a pull request if you can think up a better solution.

**Comment by dmolesUC3** [comment]
So for our application, since we don't have logged-in users and we're not exposing search history, what we're trying out is a couple of monkey-patches to Blacklight::Controller and Blacklight::SearchContext that basically just [do away with the search history entirely](https://github.com/CDLUC3/stash_discovery/commit/9d31bb163cfa9438ffff33bd2de707b6e6686266). (This obviously isn't an ideal solution for most sites, but I'm linking to it in case it proves useful for someone else.)

Meanwhile, though, I also did a bit of research on what our search table rows look like and how feasible it would be to just store search history directly in session cookies, at least for anonymous users (who I suspect make up the vast majority of search table entries, at least on sites visible to bots). A typical query for us might produce a `query_params` value in the range of 250-350 bytes, with our longest being a bit over 500 bytes.

Max browser cookie size is apparently 4096 bytes, suggesting we could store < 10 queries if we
simply jammed them all into the session instead of storing them in the database. This obviously isn't feasible, since the default max number of saved searches per user (`search_history_window`)
is 100. On the other hand, the `query_params` values are pretty compressible --  the Ruby leader is shared across all searches, and many facet names and even facet values are also shared. 

Experimenting with real-world values, the longest hundred (distinct) searches in our database, lengths 470-520, marshalled, take ~52 KB. Deflated, they take only 2196 bytes. This suggests that with compression, we could easily stuff 100 searches into the session cookie if we wanted to, even without changing the saved search format.

Is this worth spending more time on? Does this seem like something the community might be interested in?
