### ISSUE TITLE
Add MVP ResourceSync implementation

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#1653]
- [ ] Generating a sitemap dynamically (configurable) 
 - [ ] Return the json serialization 
 - [ ] Return the html serialization (SEO)
 - [ ] Add documentation on how to configure/best practices

Notes from discussion at LDCX:
https://docs.google.com/document/d/1Pwl1bTeE4LLTKlkzsKy79IVXPt9QUARbg9iUjJ7N_90/edit

VuFind for performance does this performately by using id's in a term and then generates all urls by generating those terms. (Rather than paging through everything)

**Comment by barmintor** [comment]
Since this is a new feature (and thus no presumed API compatibility issues) marking 7.x

**Comment by mejackreed** [comment]
Yeah, and I'm happy to defer to Infinity.x . I'm not sure there is interest in this anymore.
