### ISSUE TITLE
Enhance custom index views to have the ability not to show up in split button views

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#1686]
It would be useful to be able to add a new index view to Blacklight without that view having to show an icon in the split button icon view selection

**Comment by mejackreed** [comment]
Potentially something similar to document_actions?

```ruby
##
    # Remove bookmark action for the hierarchy view
    config.view_config(:hierarchy).document_actions.delete(:bookmark)
```

**Comment by cbeer** [comment]
Does `config.view.embed.if = false` address this (not that it could be done better or more obviously)?

**Comment by mejackreed** [comment]
I _think_ this does it now: https://github.com/projectblacklight/blacklight/commit/c5755d90a384cf59c3a4806454fee81e53ab8d38

Close?

**Comment by cbeer** [comment]
Ah, yep, that's what enabled the behavior.
