### ISSUE TITLE
Excessive field loading killing performance

### ISSUE THREAD

**Issue by mattcg** [projectblacklight/blacklight#1718]
On document pages, the logic that pulls in the data from Solr in order to build the next/previous links when coming from a search specifies `fl: '*'`.

For large documents, this causes a huge amount of data to be loaded and kills Blacklight performance over high latency networks.

It seems to me that the `*` is needlessly excessive.

See [request_builders.rb:42](https://github.com/projectblacklight/blacklight/blob/v6.10.1/app/controllers/concerns/blacklight/request_builders.rb#L42).

__UPDATE__

There's the same problem with bookmarks: see [search_helper.rb:145](https://github.com/projectblacklight/blacklight/blob/v6.10.0/app/controllers/concerns/blacklight/search_helper.rb#L145).

**Comment by cbeer** [comment]
Agreed; I wonder if we should add another configuration field for this, and fall back on the configured  id + title fields (in Blacklight 7; in 6, we probably need to keep `*` as the fallback)?

**Comment by mattcg** [comment]
In the meantime, is there anything we can do to override this parameter? It's problematic for us (and causes OOMEs in Solr at peak times).

**Comment by jcoyne** [comment]
How about adding another argument for fl to `previous_and_next_document_params` (default to `*`) https://github.com/projectblacklight/blacklight/blob/4e5af828ded57bc426b640bac35a7f94556eee30/app/controllers/concerns/blacklight/request_builders.rb#L23 Then you can pass in a value for fl here: https://github.com/projectblacklight/blacklight/blob/df877345587112dfc7b9cee7d0acef35744d661d/app/services/blacklight/search_service.rb#L58

**Comment by pirhoo** [comment]
@mattcg you can monkey patch `Blacklight::RequestBuilders` within an initializer:

```ruby
Blacklight::RequestBuilders.class_eval do
  # Create an alias on the parent method since `super` is not available within `class_eval`
  alias_method :super_previous_and_next_document_params, :previous_and_next_document_params

  def previous_and_next_document_params(index, window = 1)
    # Call parent's method
    solr_params = super_previous_and_next_document_params index, window
    # Override selected fields with the document's unique id
    solr_params[:fl] = blacklight_config.document_unique_id_param
    solr_params
  end
end
```

**Comment by mattcg** [comment]
@cbeer the fix by @pirhoo seems like it should be the default behaviour (to request only the ID).

**Comment by mattcg** [comment]
There's the same problem with bookmarks: see [search_helper.rb:145](https://github.com/projectblacklight/blacklight/blob/v6.10.0/app/controllers/concerns/blacklight/search_helper.rb#L145).

**Comment by pirhoo** [comment]
Thanks @jkeck!
