### ISSUE TITLE
Librarian view not working on demo

### ISSUE THREAD

**Issue by starsplatter** [projectblacklight/blacklight#1746]
https://demo.projectblacklight.org/en/catalog/2004558925

![screen shot 2017-08-15 at 1 00 15 pm 2](https://user-images.githubusercontent.com/2148239/29326500-bd6ae41a-81b9-11e7-8c7a-47f466a56abe.png)

**Comment by jcoyne** [comment]
I'm working on fixing this in https://github.com/projectblacklight/blacklight-marc/pull/46

**Comment by cbeer** [comment]
Thanks, all fixed.
