### ISSUE TITLE
ERROR: Error CREATEing SolrCore 'blacklight-core': Unable to create core [blacklight-core] Caused by: Setting defaultSearchField in schema not supported since Solr 7

### ISSUE THREAD

**Issue by SykesStudio** [projectblacklight/blacklight#1792]
/home/user1/.rvm/gems/ruby-2.4.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:322:in `exec': Failed to execute solr create:  (RuntimeError)
Copying configuration to new core instance directory:
/opt/projects/my_new_blacklightapp/solr-7.0.0/server/solr/blacklight-core

Creating new core 'blacklight-core' using command:
http://localhost:8983/solr/admin/cores?action=CREATE&name=blacklight-core&instanceDir=blacklight-core

ERROR: Error CREATEing SolrCore 'blacklight-core': Unable to create core [blacklight-core] Caused by: Setting defaultSearchField in schema not supported since Solr 7

**Comment by SykesStudio** [comment]
Has any one encountered this type of error before or can point me in the right direction? Thanks. Khamp

**Comment by mejackreed** [comment]
Hi @SykesStudio . This is due to an upstream change in Solr 7. You can remove the `defaultSearchField` in your Solr `schema.xml`. See this PR for how it can done:

https://github.com/projectblacklight/blacklight/pull/1787/files#diff-fc43f961448809f3be07b3199002e1f8L548

**Comment by SykesStudio** [comment]
That worked. Thank you so much @mejackreed. Life saver....
