### ISSUE TITLE
Draft Blacklight 7 upgrade guide

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1793]
1. Bootstrap has been upgraded from version 3 to version 4 [Migration guide](https://github.com/projectblacklight/blacklight/wiki/Bootstrap-3-to-4-Migration-Guide)
1. `shared/ajax_modal` has moved to `shared/modal`

**Comment by mejackreed** [comment]
I've updated the release notes to include these two changes. Are there other breaking changes/upgrade help we should offer in the release notes?

**Comment by jcoyne** [comment]
@mejackreed I think that looks good and is complete as far as I know.

**Comment by mejackreed** [comment]
Great. I'm 👍 for closing this issue then.. 1 step closer.
