### ISSUE TITLE
inverting slashes in link_to_document

### ISSUE THREAD

**Issue by kunwon1** [projectblacklight/blacklight#1794]
Hello!

I am nearly finished with blacklight customization but i've run into another hitch

I am overriding link_to_document in app/helpers like so:

```ruby
  def link_to_document(doc, field_or_opts = nil, opts={:counter => nil})
    if doc['url'].start_with?('file:')
      foo = doc['url'].gsub! 'file:/', ''
      puts foo
      foo = foo.gsub! '/', '\\'
      puts foo
      foo = foo.gsub! 'mnt\s', 'file:/S:\'
      puts foo
    else
      foo = doc['url']
    end
    link_to doc['title'], foo
```

the calls to puts confirm that the slashes are converted, but in the rendered html they are switched back to forward slashes. How do I override that behavior?

**Comment by jcoyne** [comment]
I wonder if that's perhaps the default behavior of the link_to helper in rails? http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to  I don't think this an issue with the blacklight code.
