### ISSUE TITLE
Quickstart Guide no longer works because of solr 7 incompatibility issue

### ISSUE THREAD

**Issue by bibliotechy** [projectblacklight/blacklight#1795]
The latest solr from solr_wrapper is now 7.0. which does not support `defaultSearchField` and `solrQueryParser` which are defined in the default solr schema.

Following the quickstart guide leads to an exception when trying to start solr_wrapper.

Would it be preferable to pin Blacklight to solr 6.x or update schema to remove?

**Comment by jcoyne** [comment]
I think we should update the schema. This is already done in master and just needs a backport.
