### ISSUE TITLE
Any good references to production roll out versus development

### ISSUE THREAD

**Issue by SykesStudio** [projectblacklight/blacklight#1824]
Hi, 
I  have been using the development and would like to know if there is a good reference for standing up Blacklight on Redhat for production.

**Comment by mejackreed** [comment]
There may be some relevant pieces here: https://web.archive.org/web/20160807011614/http://www.curationculture.org/archives/2221

Focused on GeoBlacklight on AWS but perhaps some similar methods.

**Comment by SykesStudio** [comment]
Thank you for the suggest. Do you know how I can get my rails solr and rails server to run as a daemon versus in the console?
