### ISSUE TITLE
Access kerberos solrcloud

### ISSUE THREAD

**Issue by jalongar** [projectblacklight/blacklight#1834]
Hi,
It is possible to configure Blacklight to access a kerberized solrcloud server?

Regards

**Comment by epugh** [comment]
You can do basic auth by just doing `http://user:pass@yourblacklight.server`

**Comment by jalongar** [comment]
Does not work with kerberos

**Comment by jcoyne** [comment]
I don't think we know enough about kerberos to be helpful.  Please consider asking questions on the mailing list (blacklight-development@googlegroups.com). You'll reach a broader audience there.
