### ISSUE TITLE
Black light autocomplete problem. Solr Admin Suggest working fine.

### ISSUE THREAD

**Issue by furqanwasi** [projectblacklight/blacklight#1844]
Solr Admin Suggest working fine. Black light autocomplete problem. Although, both request sent have same params. I followed this link  https://stackoverflow.com/questions/32862609/how-to-get-suggestions-in-solr-5-3-0 which made my solr suggest working fine. Solr admin panel request looks like this which returns correct results
`447141 INFO  (qtp1830712962-12) [   x:development] o.a.s.c.S.Request [development] webapp=/solr path=/suggest params={q=furq&wt=json&_=1521210506457} status=0 QTime=1`

Response `{
  "responseHeader": {
    "status": 0,
    "QTime": 1
  },
  "suggest": {
    "default": {
      "furq": {
        "numFound": 1,
        "suggestions": [
          {
            "term": "Furqan",
            "weight": 0,
            "payload": ""
          }
        ]
      }
    }
  }
}`

even by hit suggest link (http://localhost:8983/solr/development/suggest?q=furq&wt=json) direct gives result 
`450464 INFO  (qtp1830712962-13) [   x:development] o.a.s.c.S.Request [development] webapp=/solr path=/suggest params={q=furq&wt=json} status=0 QTime=1`

`
{"responseHeader":{"status":0,"QTime":1},"suggest":{"default":{"furq":{"numFound":1,"suggestions":[{"term":"Furqan","weight":0,"payload":""}]}}}}
`

However same request using my blacklight installation
`481052 INFO  (qtp1830712962-17) [   x:development] o.a.s.c.S.Request [development] webapp=/solr path=/suggest params={q=furq&wt=json} status=0 QTime=3`

returns empty array `[]`

![1](https://user-images.githubusercontent.com/4498754/37528216-e4c04250-2955-11e8-9131-44a225496b4e.png)

My Catelog Contoller 

`
class CatalogController < ApplicationController

  
  include Blacklight::Catalog
  include Blacklight::Marc::Catalog

  configure_blacklight do |config|
    # Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    # Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    # Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response

    # Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters

    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select'

    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]

    # Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SearchHelper#solr_doc_params) or
    # parameters included in the Blacklight-jetty document requestHandler.
    #
    # config.default_document_solr_params = {
    #     :qt => 'Furqan',
    #     :fq => '*:*',
    #     :rows => 20
    # }
      config.default_solr_params = {
            defType: 'edismax',
            :rows => 5
    }
    # solr field configuration for search results/index views
    # config.index.title_display = :id_is
    # config.index.display_type_field = 'name_texts'
    # # config.index.document_presenter_class = MyPresenter
    # config.add_index_field 'author_display', :label => 'Author:', :link_to_search => :id_is
    # #config.index.thumbnail_field = 'thumbnail_path_ss'

    # solr field configuration for document/show views
    #config.show.title_field = 'title_display'
    #config.show.display_type_field = 'format'
    #config.show.thumbnail_field = 'thumbnail_path_ss'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    config.add_facet_field 'name_texts', label: 'Students'
    config.add_facet_field 'courses_sms', label: 'Courses'
    config.add_facet_field 'klass_sms', label: 'Classes'
    # config.add_facet_field 'language_facet', label: 'Language', limit: true
    # config.add_facet_field 'lc_1letter_facet', label: 'Call Number'
    # config.add_facet_field 'subject_geo_facet', label: 'Region'
    # config.add_facet_field 'subject_era_facet', label: 'Era'

    # config.add_facet_field 'example_pivot_field', label: 'Pivot Field', :pivot => ['format', 'language_facet']

    # config.add_facet_field 'example_query_facet_field', label: 'Publish Date', :query => {
    #    :years_5 => { label: 'within 5 Years', fq: "pub_date:[#{Time.zone.now.year - 5 } TO *]" },
    #    :years_10 => { label: 'within 10 Years', fq: "pub_date:[#{Time.zone.now.year - 10 } TO *]" },
    #    :years_25 => { label: 'within 25 Years', fq: "pub_date:[#{Time.zone.now.year - 25 } TO *]" }
    # }

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    # config.add_index_field 'name_texts', label: 'Title'
    # config.add_index_field 'courses_sms', label: 'Title'
    # config.add_index_field 'klass_sms', label: 'Title'
    
    # config.add_index_field 'title_vern_display', label: 'Title'
    # config.add_index_field 'author_display', label: 'Author'
    # config.add_index_field 'author_vern_display', label: 'Author'
    # config.add_index_field 'format', label: 'Format'
    # config.add_index_field 'language_facet', label: 'Language'
    # config.add_index_field 'published_display', label: 'Published'
    # config.add_index_field 'published_vern_display', label: 'Published'
    # config.add_index_field 'lc_callnum_display', label: 'Call number'

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.index.title_field = 'name_texts'
    
    # config.add_show_field 'name_texts', label: 'Title'
    config.add_index_field 'name_texts', label: 'Title'
    # config.add_show_field 'title_vern_display', label: 'Title'
    # config.add_show_field 'subtitle_display', label: 'Subtitle'
    # config.add_show_field 'subtitle_vern_display', label: 'Subtitle'
    # config.add_show_field 'author_display', label: 'Author'
    # config.add_show_field 'author_vern_display', label: 'Author'
    # config.add_show_field 'format', label: 'Format'
    # config.add_show_field 'url_fulltext_display', label: 'URL'
    # config.add_show_field 'url_suppl_display', label: 'More Information'
    # config.add_show_field 'language_facet', label: 'Language'
    # config.add_show_field 'published_display', label: 'Published'
    # config.add_show_field 'published_vern_display', label: 'Published'
    # config.add_show_field 'lc_callnum_display', label: 'Call number'
    # config.add_show_field 'isbn_t', label: 'ISBN'

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different.

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise.

    # config.add_search_field 'name_texts', label: 'name_texts'

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields.

    config.add_search_field('name_texts') do |field|
        
        
        #logger.debug "$$$$$$$$$$$$$$$$$$$@@@@@@@@@@@@ #{field.method.inspect} @@@@@@@@@@@@@@@@@@@@@"

      # solr_parameters hash are sent to Solr as ordinary url query params.
      # field.solr_parameters = { qf: 'name_texts:*', q:'*' }
        field.solr_local_parameters = { 
            'spellcheck.dictionary': 'name_texts',
            qf: 'name_texts',
            pf: 'name_texts'
        }
    end

    config.add_search_field('testing_texts') do |field|
      field.solr_parameters = {
        
        qf: 'testing_texts',
        
      }
    end

    # # Specifying a :qt only to show it's possible, and so our internal automated
    # # tests can test it. In this case it's the same as
    # # config[:default_solr_parameters][:qt], so isn't actually neccesary.
    # config.add_search_field('subject') do |field|
    #   field.qt = 'search'
    #   field.solr_parameters = {
    #     'spellcheck.dictionary': 'subject',
    #     qf: '${subject_qf}',
    #     pf: '${subject_pf}'
    #   }
    # end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    # config.add_sort_field 'score desc, pub_date_sort desc, title_sort asc', label: 'relevance'
    # config.add_sort_field 'pub_date_sort desc, title_sort asc', label: 'year'
    # config.add_sort_field 'author_sort asc, title_sort asc', label: 'author'
    # config.add_sort_field 'name_texts_sort asc, pub_date_sort desc', label: 'title'

    # If there are more than this many search results, no spelling ("did you
    # mean") suggestion is offered.
    config.spell_max = 5

    # Configuration for autocomplete suggestor
    config.autocomplete_enabled = true
    config.autocomplete_path = 'suggest'
  end
end
`

**Comment by furqanwasi** [comment]
any suggestions ?

**Comment by cajahnke** [comment]
I had the same issue this week and ran through the code line-by-line with byebug.  The issue wound up being if you have renamed the suggester from Solr's default of 'mySuggester' you need to replace the occurrence of 'mySuggester' in the suggestions definition of blacklight's Response class with whatever your suggester is named.

Apparently Blacklight's original developers did not think anyone would rename the suggester.

**Comment by jcoyne** [comment]
@cajahnke Can you submit a pull request to make that change in Blacklight? It sounds like it would be something others would appreciate.

**Comment by cajahnke** [comment]
Absolutely, might be a month or more before I get to the pull request but bla bla competing projects and there are some other changes that I need to work out with getting grouped responses to count results properly instead of reporting number of groups

**Comment by barmintor** [comment]
Closing since PR was merged into master and will be in 7.0.0RC2
