### ISSUE TITLE
Improve display for citation modal

### ISSUE THREAD

**Issue by tampakis** [projectblacklight/blacklight#1852]
The citation display is missing a header with a dismiss button and padding.
Possibly address along with #900.

<img width="911" alt="screen shot 2018-03-29 at 1 54 29 pm" src="https://user-images.githubusercontent.com/4650153/38113709-a268e9a2-335a-11e8-8fba-202fa1ea97e3.png">

**Comment by cbeer** [comment]
Fixed, probably by #2053?
