### ISSUE TITLE
Customize facets by user

### ISSUE THREAD

**Issue by pirhoo** [projectblacklight/blacklight#1854]
Hello Blacklight team!

I couldn't find a way to customize facets per user (defined in `CatalogController`). Is it possible? More generally, it would be very cool to be able to configure the controller outside of the `configure_blacklight` method.

Thanks for the amazing work!

Pierre

**Comment by jcoyne** [comment]
@pirhoo you can define a `blacklight_config` method in your controller that overrides https://github.com/projectblacklight/blacklight/blob/master/app/models/concerns/blacklight/configurable.rb#L6
and provides a `Blacklight::Configuration` object that is appropriate for the current user.  This is the mechanism that Spotlight (https://github.com/projectblacklight/spotlight) is  using.

In the future if you have questions please use the blacklight-development@googlegroups.com
list as we only use blacklight issues for tracking bugs.

**Comment by pirhoo** [comment]
This is very useful. Thanks!
