### ISSUE TITLE
Issue running the Quickstart

### ISSUE THREAD

**Issue by mrinalinihanagodu** [projectblacklight/blacklight#1855]
Hi,

I am a newbie when it comes to blacklight/ruby/rails/solr, hence tried to follow the quickstart guide for blacklight.

I get the following error when i try to run " bundle exec solr_wrapper " :

**Starting Solr 7.2.1 on port 8983 ... C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:134:in `getpgid': getpgid() function is unimplemented on this machine (NotImplementedError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:134:in `wait'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:91:in `stop'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:67:in `ensure in wrap'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:67:in `wrap'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/exe/solr_wrapper:113:in `<top (required)>'
        from C:/Ruby24-x64/bin/solr_wrapper:23:in `load'
        from C:/Ruby24-x64/bin/solr_wrapper:23:in `<main>'**

When i run the command again, it takes alot of time to process(almost an hour) and then throws the below error : 
**Starting Solr 7.2.1 on port 8983 ... C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:153:in `block in create': Not started yet (RuntimeError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:152:in `create'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:216:in `with_collection'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/exe/solr_wrapper:114:in `block in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/lib/solr_wrapper/instance.rb:65:in `wrap'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solr_wrapper-1.2.0/exe/solr_wrapper:113:in `<top (required)>'
        from C:/Ruby24-x64/bin/solr_wrapper:23:in `load'
        from C:/Ruby24-x64/bin/solr_wrapper:23:in `<main>'**

I am using Windows OS,
Ruby version:  ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
Rails version: Rails 5.1.6
Could you please help me out with this.

Thanks

**Comment by mejackreed** [comment]
Thanks for filing the issue @mrinalinihanagodu . It seems to me like there might be a Windows compatibility issue with the [solr_wrapper](https://github.com/cbeer/solr_wrapper) gem. solr_wrapper is used as a simple way to start up Solr. I have seen success using this with the Windows 10 Linux subsystem. Are you running this in the Linux subsystem? See [installing linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10). An alternative here is you can just install and configure Apache Solr [manually](https://lucene.apache.org/solr/guide/6_6/installing-solr.html#install-command).

**Comment by mrinalinihanagodu** [comment]
I installed the linux subsystem however have not tried on it, will do that.
I have a running solr on my system already, what changes would i need to make (configuration wise) for it to be compatible with backlight?

**Comment by mejackreed** [comment]
There is a sample Solr configuration and schema in the Blacklight repository. For Blacklight version 6.14.1 it is located here: https://github.com/projectblacklight/blacklight/tree/v6.14.1/solr/conf

You can use that to configure your existing Solr configuration or modify the Blacklight configuration and CatalogController configuration to work with your existing Solr setup.

I'm closing this issue as I think it may be either Solr setup related or an issue with SolrWrapper. Feel free to reach out to the blacklight-development@googlegroups.com list or #blacklight on the [code4lib Slack organization](https://docs.google.com/forms/d/120Dw1JjLxPJB9VTGl0mUY7Ot6yg6YNY1RZUISJFzdwk/viewform?c=0&w=1)
