### ISSUE TITLE
Vanilla install of `7.0.0.rc1` issues

### ISSUE THREAD

**Issue by cdmo** [projectblacklight/blacklight#1868]
I'm using a Mac 10.12.6.

Just wanted to share my experience in attempting a vanilla install of the rc1 release for Blacklight 7. I ran into a few problems, most I could fix:

1. The `add_devise_to_users.rb` migration failed
1. Hit a routing error: `undefined method `add_show_tools_partial' for CatalogController:Class`
1. Hit scss errors on unknown variables
1. `unknown field 'marc_display` on `rake solr:marc:index_test_data` 

I solved 1 by just removing the migration (sidestepping this issue entirely)

I solved 2 by changing `CatalogController`:

```
# frozen_string_literal: true
class CatalogController < ApplicationController

  include Blacklight::Catalog
  include Blacklight::DefaultComponentConfiguration # this is what I added
  include Blacklight::Marc::Catalog
```

Solved the third issue by just commenting out the unknown variables in `blacklight.scss`

The 4th one I haven't been able to solve. Seems like it should be working, but isn't. Running `rake solr:marc:index_test_data` the following error is hit for all documents:

```
2018-04-23T15:08:25-04:00 ERROR Could not add record 2008308175/2008308175 at source file position 25: Solr error response: 400: {
  "responseHeader":{
    "status":400,
    "QTime":0},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"ERROR: [doc=2008308175] unknown field 'marc_display'",
    "code":400}}
```

EDIT: It looks like the field doesn't exist in the out-of-the-box `schema.xml` file doesn't have any mention of that `marc_display` field. When I use the `schema.xml` from the old 6.x branch, it will index but then Blacklight hits an error `Blacklight::Exceptions::InvalidRequest in CatalogController#index` ...

**Comment by erosas87** [comment]
Do you need to install marc? I don't know if it's supported with v7.0.0.rc1, I would recommend trying to install it without that

**Comment by cdmo** [comment]
@erosas87 Are you referring to the `solr-marc` gem? So, to explain, I was following the quick start guide, which has solr-marc as a dependency, but perhaps the intention is to update the quick start guide later or maybe abandon it.

**Comment by cdmo** [comment]
Sorry I didn't see the release notes about 

`  include Blacklight::DefaultComponentConfiguration # this is what I added`

My bad!

https://github.com/projectblacklight/blacklight/releases/tag/v7.0.0.rc1

**Comment by barmintor** [comment]
@cdmo re: your 1st item - you didn't happen to stash the backtrace for that failed migration anywhere? I'll try to run through the startup from scratch, but a headstart is always useful.

**Comment by cdmo** [comment]
The 4th item, as most of this issue, is more of a headsup that the quick start guide does not work for Blacklight 7. I would assume that it would need to work, or that guide should just get a clear notice at the top that says "Only for Blacklight 6." As I said in the edit, using the 6.x solr schema out of the box did work. If that caveat was added to that quickstart guide, then this issue could be closed. 

No, sorry, I don't have a backtrace of the failed migration.

**Comment by cdmo** [comment]
Good to see some activity! @barmintor ++

**Comment by barmintor** [comment]
@cdmo We've got a new version of blacklight-marc pushed (7.0.0.rc1) - would it be possible to try to run through the vanilla/quickstart again?

**Comment by cdmo** [comment]
So, I did it. Used the "hard way" and specified `blacklight` 7.0.0.rc. Ran the install. Then I changed the generated gem dependency on `blacklight-marc` from version 6.1 to 7.0.0.rc. Ran `bundle update blacklight-marc`. Ran `bundle exec solr_wrapper`, ran the sample index task. Got this:

```
➜  rake solr:marc:index_test_data
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 0)
/Users/cdm32/quick/my_new_blacklightapp/app/models/marc_indexer.rb:16:in `initialize'
Tasks: TOP => solr:marc:index:work
(See full trace by running task with --trace)
```

**Comment by cdmo** [comment]
I think this needs to be changed to `7.0.0.rc1`:

https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/install_generator.rb#L91

?

**Comment by cdmo** [comment]
yep, that did it. I put in a PR https://github.com/projectblacklight/blacklight/pull/2030

QuickStart worked perfectly with that one line change. Thanks.

**Comment by beggnla** [comment]
I just thought I'd add I'm running into all of the issues described trying to run through the Quickstart guide just using the "easy way".
