### ISSUE TITLE
Allow multiple document types to be rendered by the same controller

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#1878]
Currently if I were to have two backends one that returns Solr records and another that returns Primo Central records, I could potentially bookmark both types of records and have a list of mixed document types.

Nevertheless, when I go to the bookmarks index page the resulting document list is rendered using the `render_document_index` helper method and this method treats all of the listed documents as belonging to one type.

Thus if we wanted to render a list of different document types we would have to keep the list separated by type (two lists) override the template for rending the list and then change the context to match the documents we are rendering (i.e. change the context to PrimoCentralController for Primo record list and CatalogController for Solr record list).

This is unfortunate because it means we can't easily have a list of mixed document types.

I think it should be possible for the controller to use the document type of the individual record to decide how to render that record instead of assuming one type for all records in a document list.

**Comment by dkinzer** [comment]
The more I think about it the less sure I am that there is a good backwards compatible way to get multi document type rendering to work.

The problem is that so much of how things are rendered depends on `blacklight_config`, and it is used on a global level.

A hack for implementing this feature in a backwards compatible way could be to temporarily swap out the global `@blacklight_config` value per document in the the list as they are being rendered.

But this approach may end up causing some major headaches because `@blacklight_config` will stop being stable.  So reasoning about what is going on will be harder.

A better approach would be do stop using `blacklight_config` for everything, and instead separate out the configurations into `blacklight_config` and `document_config`.  `document_config` can be implemented to behave according to `@document`.  This will be easier to reason about because we would know that the configuration is associated to a specific document type.

Unfortunately there is not a backwards compatible way to implement the feature using the second approach because users who currently override the `blacklight_config` method in the document rendering context will need to update the name to `document_config`.

**Comment by dkinzer** [comment]
@jcoyne precisely.  Also sorting and pagination has similar issues.  We've implemented something for tulibraries  for bookmarks that currently just uses the order that the bookmarks where first added.  Eventually we'll add sorting; and we might add pagination.

But you are absolutely correct.  Merging lists from different sources is tricky because the merging process is not trivial if you want to merge on relevancy.

When I worked on the IxQuick search engine we would merge sources and weigh them higher or lower based on duplication.   But if your sources are completely different that technique wouldn't work.

**Comment by jkeck** [comment]
FWIW, when thinking about how to implement select lists in our multi-backend Blacklight app (SearchWorks), we've been thinking about making our bookmarks/selection UI able to switch between selections from the different backends (as opposed to interfiling them).

**Comment by dkinzer** [comment]
@jkeck take a look at our implementation for bookmarks, we merge the items into one list, which I think is the user expected behavior for this kind of feature: https://github.com/tulibraries/tul_cob/blob/master/app/controllers/concerns/multi_source_bookmarks.rb#L35

It's a hack because we have to dynamically change the controller that is used per item at render or items get rendered with the same controller which doesn't work.
