### ISSUE TITLE
Bootswatch versioning issues for v7.0.0.rc1

### ISSUE THREAD

**Issue by erosas87** [projectblacklight/blacklight#1879]
Current setup:

Blacklight v7.0.0.rc1
Ruby v2.4.1
Rails v5.2.0
Sass-rails v5.0.7
Bootstrap v4.1.1
Bootswatch-rails v3.3.7

We are attempting to implement the Bootswatch Darkly theme with the above setup and are running into issues.

We have added the following to our /app/assets/stylesheets/application.css.scss file:

```
@import "bootswatch/darkly/variables";
@import "bootstrap";
@import "bootswatch/darkly/bootswatch";
@import 'blacklight/blacklight'
```

After starting the rails server, a stack trace appears in the browser:

```
Sass::UnitConversionError in Catalog#index
Showing /app/views/layouts/blacklight/base.html.erb where line #21 raised:

Incompatible units: 'rem' and 'px'.
```

And the following appears in the server log:

ActionView::Template::Error (Incompatible units: 'rem' and 'px'.):
    18: 
    19:     <title><%= render_page_title %></title>
    20:     <%= opensearch_description_tag application_name, opensearch_catalog_url(format: 'xml') %>
    21:     <%= favicon_link_tag %>
    22:     <%= stylesheet_link_tag "application", media: "all" %>
    23:     <%= javascript_include_tag "application" %>
    24:     <%= csrf_meta_tags %>
  
app/assets/stylesheets/application.css.scss:20

~~~~~~

I'm suspecting there are versioning issues, is there a workaround that can be done in the meantime before an official fix can be implemented?

**Comment by jcoyne** [comment]
bootswatch-rails has not been maintained for a number of years, which makes me doubt it supports Bootstrap 4.

**Comment by mejackreed** [comment]
@erosas87 Are you looking to theme your application solely with Bootswatch? For Blacklight 7 / Bootstrap 4 we recommend a different approach. I'll update the wiki accordingly.

**Comment by erosas87** [comment]
@jcoyne Do you know of an alternative to bootswatch-rails that accomplishes the same thing and is actively maintained?

@mejackreed Bootswatch was considered because the Darkly theme satisfied our requirements, but if there is another theming library that also has a like-theme that could also work. What's the recommended approach?

**Comment by mejackreed** [comment]
I would recommend an approach that overrides the Bootstrap variables separately (rather than a theming library) if possible. The Bootstrap docs have some examples of this: https://getbootstrap.com/docs/4.0/getting-started/theming/#theme-colors
