### ISSUE TITLE
Generate AC::MimeReponds into API controller?

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1894]
Our use of `respond_to { } ` depends on `AC::MimeResponds`, this is not part of API::Controller. We could make it compatible by adding:
```
  include ActionController::MimeResponds
```

to the `ApplicationController`.  I'm not sure if we should though.

**Comment by barmintor** [comment]
Marking as 7.0 since it seems related to JSON API baseline.
