### ISSUE TITLE
JSON Search results should only display fields that are configured to display

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1899]
e.g. they have `add_index_field`

**Comment by dkinzer** [comment]
I find being able to look at a record in JSON mode to see all the fields quite useful.  I think I'm not the only one who makes use of this feature.

**Comment by jcoyne** [comment]
@dkinzer Maybe you could use the solr endpoint to do so? I'm concerned that we may unintentionally display data that was intended to be private.  If you only examine the html responses, you may be unaware you are exposing this data.
