### ISSUE TITLE
Facets not working on the demo

### ISSUE THREAD

**Issue by craigboman** [projectblacklight/blacklight#1902]
When I click the demo facets, none of them are responding. https://demo.projectblacklight.org/

**Comment by jcoyne** [comment]
js error is `Bloodhound is not defined`

**Comment by cbeer** [comment]
The `blacklight:assets` generator short-circuits if assets were previously generated:

https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/assets_generator.rb#L19-L33

We should include a note about including the new assets in the 7.0 upgrade guide.

**Comment by craigboman** [comment]
Thanks for following up with this!
