### ISSUE TITLE
edismax + searchbuilder and advanced search breakage with Solr 7.2

### ISSUE THREAD

**Issue by adjam** [projectblacklight/blacklight#1925]
Solr 7.2 included a change to how the ExtendedDisMax (edismax) parser reads the query string, namely that it it no longer allows local parameters (http://lucene.apache.org/solr/7_2_0/changes/Changes.html#v7.2.0.upgrade_notes).  This feature is used in the SearchBuilder.

This affects you if:

You are using Solr 7.2 or a later version
Your default query parser  in `solrconfig.xml` is ExtendedDisMax (```xml <defType>edismax</defType>```

Symptom:  

Solr queries built by SearchBuilder that set `q={! qf=$something pf=$something_else}actual search terms` will return unexpected or no results.

Fix: for now you must rewrite the queries, either break out the components of your query into separate HTTP parameters, e.g. `q=actual search terms&pf=$something&qf=$something_else`, or add `defType=lucene` as an HTTP parameter (the latter still allows usage of local-params parsing)

**Comment by adjam** [comment]
Duplicate of #1838

**Comment by magibney** [comment]
Prefer to explicitly update existing blacklight configs to conform to new localParams parsing constraints. See #2020.
