### ISSUE TITLE
app/views/layouts/blacklight/base.html.erb assumes sprockets

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1926]
But we may want to use webpack instead of sprockets.

The call to `javascript_include_tag` invokes sprockets.
Webpack would use something like `javascript_pack_tag 'application'` instead.

This could help us prepare for Rails 6: https://github.com/rails/rails/pull/33079

**Comment by barmintor** [comment]
Do you want to introduce a public API method that insulates this in views (`blacklight_javascript_tag`) or change the default? If we regard this as Rails API in overridable views, is this a post-7.0 issue?
