### ISSUE TITLE
Blacklight 7, allow for solr doc to be able to be returned in API responses

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#1968]
In previous versions of Blacklight you are able to request the `json` or `xml` formats and get the entire Solr doc back. This is a useful feature for lots of people, developers building apis, metadata experts, etc. I would hate to lose this feature. is there a way to establish some compromise with some of the new api response things to also get backwards compatible behavior?

Related to https://github.com/geoblacklight/geoblacklight/issues/711

cc @jcoyne

**Comment by barmintor** [comment]
Is there a reason the solr doc couldn't be the value of `attributes`?

**Comment by barmintor** [comment]
@jcoyne how do you feel about that approach?

**Comment by jcoyne** [comment]
@barmintor I think that approach may leak more data than was intended.  If the field is not configured in the configuration, by default I think it should not display.

**Comment by barmintor** [comment]
Some ideas:
1. Just agree that all the relevant fields should be configured in advance
2. A route that would return the solr document from, eg, /catalog/12345/solr_document (which I think would be called solr_document_solr_document_path, bonus)
3. A `.solr` format

We actually use resourceful solr_document routes as part of our indexing process at CUL (we have comments like `# RESTful routes for reindex API, working around Blacklight route camping`) so I'm sympathetic to wanting to keep the options in place alongside the new API (this also came up in discussion around #1899).

The decision over here will matter for #1898 as well.

**Comment by barmintor** [comment]
I can also imagine wanting to suppress fields in the html display that are configured for the API - it would be nice not to require template overrides for this stuff since they're such a maintenance pain point.

**Comment by jcoyne** [comment]
I like 1.  I think 2 would be acceptable if we keep it behind a feature flag with the default being "off".  3 seems a bit awkward (what would its mime-type be? `application/json+solr`?).  I'm not sure what 4 means.

**Comment by jcoyne** [comment]
I wonder if that could be handled by:
```ruby
config.add_index_field 'myField', if: Proc {...}
```

**Comment by barmintor** [comment]
To be clear, I think an acceptable resolution to this ticket would be an upgrade guide that describes that kind of business, too - but GeoBlacklight should probably have a clear path forward.

**Comment by jcoyne** [comment]
Does Geoblacklight have a specific need for this or is it just a general Blacklight thing?  I was unable to ascertain this from geoblacklight/geoblacklight#711

**Comment by jcoyne** [comment]
Another idea.  What if the FieldPresenter could be different per response types? Would this fix the problem enough? I'm not certain I understand the problem case quite well enough to know if the problem is that they are being wrapped in HTML, or if it's "Don't use JSON-API" https://github.com/projectblacklight/blacklight/blob/8f1b3f2a4c7cbd69a5f6a4a74c8c34bf7d209042/app/presenters/blacklight/index_presenter.rb#L76

**Comment by andrewbattista** [comment]
@jcoyne Yes, many of us in the GeoBlacklight community rely on calling the .JSON document directly from GeoBlacklight, especially people who are hoovering metadata from others =) I and others appreciate the work to bring this functionality into Blacklight 7!

**Comment by jcoyne** [comment]
@andrewbattista Can you explain why you depend on that and for what purpose?

**Comment by mejackreed** [comment]
Many adopters in the GeoBlacklight community routinely harvest, share, and reindex eachothers metadata. We rely heavily on using the <= Blacklight 6 JSON API that returns the entire Solr document. Because GeoBlacklight-Schema documents are natively JSON this made a really useful feature for many in the community as a way to check what is indexed, and when it happened. For example in our workshop we demonstrate to metadata operators how they can copy the json representation from a GeoBlacklight instance and then go index that in their own application.

I know here at Stanford, other Blacklight application users (Spotlight, and SearchWorks specifically) use this feature also. It provides them with a way to check the Solr Document's status.

I think its important to provide a way for these types of users to continue to use the tool in way they are used to, while also supporting JSON API and enhancements needed for that approach.

> if the problem is that they are being wrapped in HTML, or if it's "Don't use JSON-API"
1) Yes definitely, getting the raw values is important here
2) I'd be ok with using JSON API if there was a way to return the full document (the kitchen sink under attributes?).

**Comment by andrewbattista** [comment]
@jcoyne Sorry for the delay. @mejackreed nicely summarized why we use it so much. We've been able to get Solr-compliant metadata via this method even though some institutions have been unwilling to share GeoBlacklight/Solr compliant metadata into the OpenGeoMetadata collective. Also, it's useful to go to other deployments, add a .json to the end of a catalog URL and see if other institutions are deploying custom elements (and if so, how). Hope this is helpful!

**Comment by barmintor** [comment]
This behavior is optionally configured in Blacklight 7 by adding:
`raw_endpoint: OpenStructWithHashAccess.new(enabled: false)`

to the Blacklight controller configuration, and requesting `/catalog/12345/raw.json` or similar, per the configured controller.
