### ISSUE TITLE
Bookmark change for a guest "Can't verify CSRF token authenticity"

### ISSUE THREAD

**Issue by cdmo** [projectblacklight/blacklight#2002]
Blacklight 7, Rails 5.2

A not-logged in User (Guest) does a search
Guest clicks a checkbox to bookmark
Guest clicks the same checkbox to un-bookmark
An alert message is displayed saying "error"

The application log looks like this:

```
Started DELETE "/bookmarks/10023235" for 127.0.0.1 at 2018-10-31 09:47:13 -0400
Processing by BookmarksController#destroy as JSON
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"2oNI6L6OmHe90HTjoH4ZcQmASQCpuuR3wwKRMW8VVUytQE+hwo3vVfbd58zcQdlWv2XbtELma+fbT7ZMTzEnfQ==", "id"=>"10023235"}
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)



ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
```

If you add the following line to the `bookmarks.rb` it goes away

`skip_before_action :verify_authenticity_token` or `protect_from_forgery unless: -> { request.format.json? }`

As in 

```rb
    copy_blacklight_config_from(CatalogController)

    skip_before_action :verify_authenticity_token ## or protect_from_forgery unless: -> { request.format.json? }
    before_action :verify_user
```

If I am understanding correctly, `protect_from_forgery unless: -> { request.format.json? }` is slightly safer and intended for API-based json formatted requests.

This has come up in a bunch of places like GitHub and StackOverflow, [here's one place](https://github.com/psu-libraries/psulib_blacklight/issues/71). Seems like a [change in Rails 5.2](https://github.com/rails/rails/issues/29193).

One weird thing is that you can un-bookmark from the My Bookmarks page, no problem.

I'm looking into a method that is better than just turning it off.

**Comment by jcoyne** [comment]
I'm not able to duplicate this on https://demo.projectblacklight.org/, are you? This lends credence to the theory that it's a Rails 5.2 change as the demo site is running 5.1

**Comment by jcoyne** [comment]
I don't understand why this would be a change from 5.1, because ApplicationController > CatalogController> BookmarksController, so we've always been using ApplicationController, so we should get that forgery protection both in 5.1 and in 5.2

**Comment by cdmo** [comment]
Well that shoots that theory! :) It's been there all along and working properly for guests. I have a [full trace](https://github.com/psu-libraries/psulib_blacklight/issues/71#issuecomment-434727876) available fwiw.

I attempted some debugging yesterday and from what I could see it looks like on the second bookmark action on a search results page, the client sends a matching token and a nil token. I'm not super confident about this assessment though tbqh.

**Comment by mejackreed** [comment]
@cdmo I wonder if something like this fixes things for you: https://github.com/sul-dlss/arclight-demo/commit/df0818eb34f287d997e5463855c149c4789afc54

**Comment by cdmo** [comment]
We solved this via [adding rails_ujs and starting it](https://github.com/psu-libraries/psulib_blacklight/pull/433/files#diff-c0a98e77a42efd669302853444d5c362R12-R15). Apologies for not reporting back sooner. Just something we didn't realize we needed in our webpacker-only implementation.
