### ISSUE TITLE
LatLonType is deprecated in Solr 7

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2016]
https://github.com/projectblacklight/blacklight/blob/8b9041544553ce0dd0d979f9f39f78d94b30b46d/lib/generators/blacklight/templates/solr/conf/schema.xml#L267

**Comment by jcoyne** [comment]
@mejackreed should we just drop the LatLonType since we have the SpatialRecursivePrefixTreeFieldType?
https://github.com/projectblacklight/blacklight/blob/8b9041544553ce0dd0d979f9f39f78d94b30b46d/lib/generators/blacklight/templates/solr/conf/schema.xml#L273

**Comment by jcoyne** [comment]
Another option would be to introduce the `LatLonPointSpatialField`

**Comment by mejackreed** [comment]
Yeah, I think the intent is for `LatLonType` -> `LatLonPointSpatialField`. Seems like the idiomatic way forward.
