### ISSUE TITLE
Displaying thumbnails in show views

### ISSUE THREAD

**Issue by awead** [projectblacklight/blacklight#2035]
The catalog config seems to imply you can add thumbnails to the default show views by adding/uncommenting this line:

    config.show.thumbnail_field = 'thumbnail_path_ss'

Where `thumbnail_path_ss` is the solr field with the path to the thumbnail. When we enable this config, it doesn't seem to work. If I call the `catalog/_thumbnail.html.erb` partial directly:

    <%= render 'thumbnail, document: @document %>

I get: Undefined method "thumbnail" for Blacklight::ShowPresenter, which is in reference to https://github.com/projectblacklight/blacklight/blob/master/app/views/catalog/_thumbnail.html.erb#L1

I'm wondering if this is an actual bug, or if we're just not doing something right.

**Comment by dgcliff** [comment]
This seems (loosely) correlated with #2067 

The index presenter has a ThumbnailPresenter defined
https://github.com/projectblacklight/blacklight/blob/v7.0.1/app/presenters/blacklight/index_presenter.rb#L5 whereas ShowPresenter doesn't.

As currently implemented I think you have two choices. Making your own ShowPresenter, or modifying Blacklights to provide a `thumbnail` method (and presenter), or modifying the thumbnail partial to utilize some other way of reaching your thumbnail presenter https://github.com/projectblacklight/blacklight/blob/v7.0.1/app/views/catalog/_thumbnail.html.erb#L1

I think fundamental to both this issue and #2067 is that the partials assumptions and lack of nil safety cause a pretty rough "gotcha" moment that's hard to understand without spelunking into BL's codebase.

I'm going to take a look at the suggested TODO referenced in #2067 via the helper comments `TODO: Move this to the controller. It can just pass a presenter or set of presenters.` Hopefully a PR will result

**Comment by cbeer** [comment]
I believe this was fixed with #2204.
