### ISSUE TITLE
Verify Rails template works with BL 7.0.0

### ISSUE THREAD

**Issue by barmintor** [projectblacklight/blacklight#2045]
> I just thought I'd add I'm running into all of the issues described trying to run through the Quickstart guide just using the "easy way".

_Originally posted by @beggnla in https://github.com/projectblacklight/blacklight/issues/1868#issuecomment-451056288_

**Comment by jcoyne** [comment]
I just ran the template and it worked without issue.

**Comment by jcoyne** [comment]
After doing that, I did hit this:
> unknown field 'marc_display on rake solr:marc:index_test_data

**Comment by beggnla** [comment]
Thanks @jcoyne . I'll run through it today and give more thorough explanation of any issues.

The unknown field error was actually the first one that I came across. I was able to get around that as described earlier in this thread by using and old schema.xml file. I was then able to index data however then I came across errors in the web app looking for fields that didn't exist. For example:

`Blacklight::Exceptions::InvalidRequest in CatalogController#index
RSolr::Error::Http - 400 Bad Request Error: { "responseHeader":{ "status":400, "QTime":0, "params":{ "f.subject_ssim.facet.limit":"21", "facet.query":["pub_date_ssim:[2014 TO *]", "pub_date_ssim:[2009 TO *]", "pub_date_ssim:[1994 TO *]"], "f.language_ssim.facet.limit":"11", "facet.field":["format", URI: http://127.0.0.1:8983/solr/blacklight-core/select?wt=json&facet.field=format&facet.field=%7B%21ex%3Dpub_date_ssim_single%7Dpub_date_ssim&facet.field=subject_ssim&facet.field=language_ssim&facet.field=lc_1letter_ssim&facet.field=subject_geo_ssim&facet.field=subject_era_ssim&facet.query=pub_date_ssim%3A%5B2014+TO+*%5D&facet.query=pub_date_ssim%3A%5B2009+TO+*%5D&facet.query=pub_date_ssim%3A%5B1994+TO+*%5D&facet.pivot=format%2Clanguage_ssim&&&rows=10&facet=true&f.subject_ssim.facet.limit=21&f.language_ssim.facet.limit=11&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc Backtrace: /usr/local/rvm/gems/ruby-2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute' /usr/local/rvm/gems/ruby-2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute' /usr/local/rvm/gems/ruby-2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive' /usr/local/rvm/gems/ruby-2.5.3/gems/blacklight-7.0.0/lib/blacklight/solr/repository.rb:62:in `block in send_and_receive' /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/benchmarkable.rb:43:in `block in benchmark' /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext/benchmark.rb:14:in `block in ms' /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime' /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext/benchmark.rb:14:in `ms' /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/benchmarkable.rb:43:in `benchmark' /usr/local/rvm/gems/ruby-2.5.3/gems/blacklight-7.0.0/lib/blacklight/solr/repository.rb:60:in `send_and_receive' /usr/local/rvm/gems/ruby-2.5.3/gems/blacklight-7.0.0/lib/blacklight/solr/repository.rb:23:in `search'`

Thanks,
Rob

**Comment by beggnla** [comment]
Sorry for the delayed reply, I haven't got any further than the last message I posted.
I just tried following the quick guide again the easy way and got the below error when trying to index data.

`unknown field 'marc_display`

I'm assuming that if I modify they schema I'll end up with the same error as above.

**Comment by jcoyne** [comment]
I suspect everything will work when we release 7.0.1.  I think this issue has already been addressed in master.

**Comment by beggnla** [comment]
Thanks @jcoyne .
I think the quickstart guide creates the app from master which I still haven't been able to get to work.
> rails new search_app -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb
I'm happy to leave it for now though and try a later release.
Thanks for your help.

**Comment by jcoyne** [comment]
@beggnla it's correct that the template comes from master, but the template says to install the released version from rubygems, and the bug is in the released version.

**Comment by jendiamond** [comment]
### My Goal:
I am trying to update to 7.0.0 so I can use the new and changeable **alt tag**.  

(*I want the alt tag for the thumbnails to be either "thumbnail" or the Title of the image, whichever is best for accessibility.* I read that the older versions of Blacklight don't support that but the new ones do.)

---

So I updated the gem and my app completely  broke.

@jcoyne  told me that  `Blacklight::Utils` was removed in 7.0.  It provided support for Rails 4, which is not supported in Blacklight 7.

Once I commented out the `Blacklight::Utils`  
`app/models/user.rb`
```
class User < ApplicationRecord

#  if Blacklight::Utils.needs_attr_accessible?
#    attr_accessible :email, :password, :password_confirmation
#  end

# Connects this user object to Blacklights Bookmarks.
  include Blacklight::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier for
  # the account.
  def to_s
    email
  end
end
```
My app runs again but I still have an error which looks like it doesn't like the new include tag, `include Blacklight::DefaultComponentConfiguration`.

I now get this error:
```
undefined local variable or method `blacklight_config' for CatalogController:Class
Rails.root: /ursus

Application Trace | Framework Trace | Full Trace
app/controllers/catalog_controller.rb:7:in `include'
app/controllers/catalog_controller.rb:7:in `<class:CatalogController>'
app/controllers/catalog_controller.rb:5:in `<top (required)>'
```

Then, I commented out the `include Blacklight::DefaultComponentConfiguration` in the `app/controller/catalog/controller`  and I added these configs at the bottom of the `app/controller/catalog/controller` page as per the release instructions.  
```
    config.add_results_document_tool(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    config.add_show_tools_partial(:citation)

    config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: :render_bookmarks_control?)
    config.add_nav_action(:search_history, partial: 'blacklight/nav/search_history')
```

#### New Error
I believe this has to do with using the range gem   `blacklight_range_limit 6.3.3`   
Is that gem now included in blacklight and therefore the app breaks because of it?

```
NameError in Catalog#index

Showing /usr/local/bundle/gems/blacklight_range_limit-6.3.3/app/views/blacklight_range_limit/_range_limit_panel.html.erb where line #2 raised:

undefined local variable or method `solr_field' for #<#<Class:0x0000555b8bd35bf8>:0x0000555b8bd1a150>

1 <%- # requires solr_config local passed in
2  field_config = range_config(solr_field)  
3  label = facet_field_label(solr_field)
4
5   input_label_range_begin = field_config[:input_label_range_begin] || t("blacklight.range_limit.range_begin", field_label: label)
6  input_label_range_end   = field_config[:input_label_range_end] || t("blacklight.range_limit.range_end", field_label: label)
```

Is it too soon to upgrade?

I was wondering if I should try your newest release which is v6.19.2 ?

If anyone has the time to walk through an upgrade with me I can contribute to the documentation with the issues that arise.

**Comment by barmintor** [comment]
@jendiamond can you move this to a new issue?

**Comment by jendiamond** [comment]
Sure, thanks for your reply.

**Comment by jcoyne** [comment]
v7.0.1 has been released.
