### ISSUE TITLE
Citation modal doesn't draw modal header because it wont render citation.js.erb 

### ISSUE THREAD

**Issue by bbarberBPL** [projectblacklight/blacklight#2052]
I just did an update from black light 6.7 to 6.19.1 and discovered something odd about the citation modal not having a modal header or modal body. After playing around with the code, some investigation,  and 
 verifying this is also broken on the test site. I found a couple things

First if you go to this diff here 
[here](https://github.com/projectblacklight/blacklight/compare/v6.7.0...v6.19.1#diff-0b79e35ce72565f0814a51fa527519aaL58)
(Note This link should bring you to Line 58 of  `default_component_configuration.rb` in the *Files Changed* Tab of this diff)

The `format.js` lines were taken out so even if you `remote: true` to the data hash(eg: `data: {ajax_modal: 'trigger', remote: true}`)  of your `link_to` it will never render the `citation.js.erb` partial [here](https://github.com/projectblacklight/blacklight/blob/release-6.x/app/views/catalog/citation.js.erb)
It will only seem so render the `citation.html.erb` partial here [here](https://github.com/projectblacklight/blacklight/blob/release-6.x/app/views/catalog/citation.html.erb)

The main difference between the `js.erb` and the `html.erb` in the js version, the  `render :partial => 'citation'` is inside a `div class=modal-body` and a `div  class='modal-header'` is present at the top. The html version only contains one line `render :partial => 'citation'` 

If possible please patch for v6.x.

**Comment by jcoyne** [comment]
@mejackreed needs a backport to 6.x?

**Comment by jkeck** [comment]
Closed by https://github.com/projectblacklight/blacklight/releases/tag/v6.19.2
