### ISSUE TITLE
parameter "facet" to method "search_results" sometimes ignored

### ISSUE THREAD

**Issue by nicolasfranck** [projectblacklight/blacklight#2066]
I'm executing some extra queries after the main query, as done by blacklight.
I'm using the method "search_results" from the "Blacklight::SearchHelper" in my
helper class for this:

```
search_results({
  :q => "plato",
  :facet => "false"
})
```

when I look in the rails log, I see that the parameter value from "facet" is ignored in favour
of the default value "true", as determined by the "default_solr_params".

Not sure where this happens. Any idea on how to fix this?
Am I using this method in a wrong way?

Version: blacklight-6.10.1
Ruby: 2.3.3

**Comment by cbeer** [comment]
Hi @nicolasfranck: 

Note that the first parameter to `search_results` does not directly map to parameters Blacklight sends to Solr, but rather parameters (usually from the user) that get translated into Solr parameters. 

Depending on your needs, you have a couple options:

- bypass Blacklight's translation logic entirely, and send a solr query directly, e.g. with `repository.search({ q: 'plato', facet: false })`
- Use Blacklight's parameter mapping, and then modify the result before sending it onto solr:

```
search_results(q: 'plato') do |builder|
  builder.merge(facet: false)
end
```
