### ISSUE TITLE
Updating from 6 to 7, undefined method `thumbnail' for nil:NilClass errror for an index page.

### ISSUE THREAD

**Issue by ZahraMousavi** [projectblacklight/blacklight#2067]
For action_names which are not in ['show','citation','index'] the presenter returns nil. 
https://github.com/projectblacklight/blacklight/blob/v7.0.1/app/helpers/blacklight/blacklight_helper_behavior.rb#L259
There should be a way, to configure presenters for different actions, or for the configured index presenter to be treated as default.
It has been discussed in Blacklight development group: https://groups.google.com/forum/#!topic/blacklight-development/7Mp5Wc5fRK8

**Comment by cbeer** [comment]
Fixed by #2354
