### ISSUE TITLE
Rails generate blacklight:install fails

### ISSUE THREAD

**Issue by craigboman** [projectblacklight/blacklight#2070]
Ruby 2.6.1p33; rails 5.2.2; and openjdk v10.0.2 running on Ubuntu 18.04.2 LTS

The following command failed:
`rails generate blacklight:install --marc --solr_version=latesteed`  
stating: 
`/usr/local/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir': Permission denied @ dir_s_mkdir - /run/user/0/spring-1000 (Errno::EACCES)`

Speaking with Chris Beer, he recommended trying:
`unset XDG_RUNTIME_DIR`

This allowed me to run `rails generate` successfully.

**Comment by jcoyne** [comment]
This looks like something that Spring uses: https://github.com/rails/spring#environment-variables

Blacklight does not require spring, so it's likely to be a problem for you whether or not us use Blacklight.  Perhaps if you remove it from your Gemfile before doing `blacklight:install` you won't have this problem?
