### ISSUE TITLE
Pagination in results view not wrapping on smaller screens

### ISSUE THREAD

**Issue by sensei100** [projectblacklight/blacklight#2072]
The nav pagination currently breaks the view for screens smaller than 485px.  I noticed that this also happens on the demo project.  I added flex-wrap: wrap to the pagination class in the css files to fix the issue for our project.

**Comment by jcoyne** [comment]
I'm not sure I understand what you mean when you say it breaks.  Can you provide a screenshot?

**Comment by sensei100** [comment]
The fact that it doesn't wrap content leaves a gap on the right side.

![screen shot 2019-02-25 at 11 41 13 am](https://user-images.githubusercontent.com/15167238/53353274-5ae97080-38f2-11e9-8d92-34ae8f87f517.png)

**Comment by jcoyne** [comment]
Yes, that looks like a good fix. Can you submit a pull request with that change?

**Comment by sensei100** [comment]
Sure.
