### ISSUE TITLE
replace tracking route with ping attribute

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2091]
See https://lapcatsoftware.com/articles/Safari-link-tracking.html

**Comment by barmintor** [comment]
I think this could complement #2558 in a useful way - I've edited the description over there to elaborate it.

**Comment by jcoyne** [comment]
I'm going to close this as link auditing is disabled by default in Firefox.  I think switching to this will be a regression in the user experience for those users.

**Comment by barmintor** [comment]
@jcoyne not disagreeing, but I think there remains an argument that *if* an installation wants to store the search session (per the legacy behavior), that the ping attribute is the responsible way to do it, as indicated by the default disabling of the behavior in FF.
