### ISSUE TITLE
twitter-typeahead-rails locked to 0.11.1.pre.corejavascript 

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2092]
The app generator [generates a Gemfile line]: `gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'`, locking to that exact version. 

While the twitter-typeahead-rails gem isn't getting much love, [it did have](https://rubygems.org/gems/twitter-typeahead-rails/versions/0.11.1) a `0.11.1` release on June 25 2015, superseding Feb 22 2015's `0.11.1.pre.corejavascript`. 

Is there a reason to be generating a Gemfile that locks to `0.11.1.pre.corejavascript` specifically?

(Also, is this in fact being used by BL, and is there concern that this gem is pretty much abandoned?)

**Comment by jcoyne** [comment]
The organization who took over maintenance at that time, which was called "corejavascript" made some changes that broke the functionality we used.  I'm not thrilled that we are using an unmaintained gem, so if you would like to propose an alternative, I think the community would be happy to see it.

**Comment by jrochkind** [comment]
Hmm, yeah, actually I see now that the gem `twitter-typeahead-rails` with version `0.11.1.pre.corejavascript` was released Feb 22 2016, which is _after_ `0.11.1`, which was released June 25 2015. 

So `0.11.1.pre.corejavascript` is the more _recent_ version. A diff seems to confirm that it has changes _not_ found in `0.11.1`.  (Which totally breaks bundler/rubygems ideas of gem version ordering). 

So if BL is known to be working with `0.11.1.pre.corejavascript`, it might _not_ work with `0.11.1`. So the Gemfile generated is probably right as it is, locking to `0.11.1.pre.corejavascript`, which seems likely at this point to be last version of `twitter-typeahead-rails` ever released. 

Ugh, indeed, unpleasant. 

Is `twitter-typeahead-rails` gem used only for [autocomplete functionality as documented here](https://github.com/projectblacklight/blacklight/wiki/Blacklight-Autocomplete)?

**Comment by jrochkind** [comment]
I am personally currently still so confused by what's going on with JS in Blacklight, the mechanism by which BL is trying to support either sprockets or webpacker, and what exactly is going on there... that I'm kind of afraid to touch any of the JS myself in a PR.  But maybe I can find time to try to get a better understanding.

**Comment by jrochkind** [comment]
While also barely maintained, one option would be: https://github.com/bassjobsen/Bootstrap-3-Typeahead

(README says it works with BS 4)

**Comment by tampakis** [comment]
No longer a dependency.
