### ISSUE TITLE
Generate with JQuery 3?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2097]
The install generator will [generate a require jquery](https://github.com/projectblacklight/blacklight/blob/55e748dd3465b9e2781d4def04b912fcbfb1b231/lib/generators/blacklight/assets_generator.rb#L19) into your application.js. 

This will include jquery source into your sprockets asset pipeline, provided by the [jquery-rails](https://github.com/rails/jquery-rails) gem. 

However, [that particular require](https://github.com/rails/jquery-rails#installation), of just "jquery" will be the final JQuery 1.x. 

In fact, there is a JQuery 2.x and a JQuery 3.x now. The [JQuery Download page](https://jquery.com/download/) actually only offers 3.x download. So Blacklight is encouraging use of a pretty old JQuery. 

I'm having trouble finding definitive notes, but I believe JQuery 2 and 3 are _pretty_ backwards compatible with 1.0 -- the main change was dropping old browser versions. But JQuery 3 still supports IE9+, as well as fairly old iOS and Android default browser, last two of the 'evergreen' browsers, etc. It should be fine. 

I think JQuery 2 may have been _exactly_ compat with 1, but for dropping browsers. And JQuery 3 is _pretty, pretty_ compat, mostly but for some odd edge cases.  It is quite likely all the Blacklight JS will work just fine in JQuery 3 (I'm not totally sure how to verify this -- would CI alone be enough? It _appears_ to be working for me in a demo, but I can't say I've exersized all the features). 

Would it make sense to update the Blacklight generator to insert `require jquery3` instead of `require jquery`?

**Comment by jrochkind** [comment]
As it is, since it's generated into your app, the developer _can_ just change it to "require jquery3". This is what I've done. I did discover a [problem with blacklight_range_limit](https://github.com/projectblacklight/blacklight_range_limit/issues/99) insisting on JQuery 1 in it's requires, but when I fixed that in a fork, blacklight_range_limit worked fine with jquery3.

**Comment by jcoyne** [comment]
> Would it make sense to update the Blacklight generator to insert require jquery3 instead of require jquery?

Blacklight does not insert `require jquery`, that's a `jquery-rails` thing. I believe.
