### ISSUE TITLE
doResizeFacetLabelsAndCounts needs `trim` to avoid whitespace bug, if needed at all

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2098]
There is a JS [doResizeFacetLabelsAndCounts](https://github.com/projectblacklight/blacklight/blob/8b9041544553ce0dd0d979f9f39f78d94b30b46d/app/javascript/blacklight/facet_load.js#L6-L17)

That attempts to calculate number of characters in all `.facet-count` spans in a given facet group, find the longest one, and then on that longest one, set inline CSS `width` to be that number of characters plus one in CSS `ch` units. 

I am not certain why this JS is needed at all. Shouldn't the CSS, which uses `display:table` layout, be sufficient for layout? Or is there another way to get the CSS to take care of it?

This seems to be the commit where it was originated: 99500552390e1759f1be95e6bd3d2dc8521ad1d9 "Fix facet wrapping/hyphenation in Firefox". Seems a bit tricky to figure out if it's still needed in Firefox, or if there's a better way. 

Assuming it is still needed, there is a problem in this JS where it's trying to calculate display size of a `span.facet-count` by using JS `.textContent.length`.  If a `.facet-count` element has leading or trailing whitespace, this will be ignored by the browser in actual display rendering, but is still included in `.textContent.length`. Leading to a much too long calculation. 

[blacklight_range_limit is rendering a .facet-count with leading and trailing whitespace.](https://github.com/projectblacklight/blacklight_range_limit/issues/98), leading to disastrous behavior from Blacklight's "doResizeFacetLabelsAndCounts".  blacklight_range_limit can work around this by making sure there is no leading/trailing whitespace inside it's rendered `.facet-count`. 

However, I believe the code in Blacklight, if it is needed, should be changed to use `.textContent.trim().length` to avoid the implicit requirement that `.facet-count` elements have no leading or trailing whitespace. This implicit requirements ends up being hard to debug when violated and it does cause problems!

Thoughts/feedback welcome!

**Comment by jrochkind** [comment]
@bkeese thanks for the history!  

The converse problem though is that this workaround fix can also cause problems in edge cases, such as this one, and it's similarly very hard to know and test for all the cases it might break. 

A CSS measurement in `ch` is not reliably the 'natural' width of the element, actually anywhere, for one reason because this isn't a fixed-width font, so actual character widths very. There may be other reasons. 

The ".facet-count" span is just the actual numerical count, eg "9,654". 

I would like to remove this JS entirely. If I do a test on FF of the case you are remembering (I'm thinking a very large .facet-count as a well as a very large label), and it displays appropriately (using CSS hyphenation) -- would you support removing this JS workaround?

Alternately, if there is not consensus around removing this JS workaround, i will PR a change to add `trim` to it, to at least fix this edge case identified here. But that of course runs the risk of introducing additional bugs/edge cases, and/or leaving existing as-yet-unknown ones unfixed too. I'd rather remove the sketchy code than add additional workarounds on top of workarounds. 

If we can't actually currently demonstrate the workaround is needed, I think it should be removed (and if we could demo/reproduce the problem, that would open up the possibility of finding an alternate solution for it in CSS alone).

**Comment by bkeese** [comment]
It's possible the js is no longer needed. We were testing some extreme cases with really long words like this Welsh placename: Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochuchaf. The browser couldn't find a good place to split it, and since the container (the table column, iirc) didn't have a fixed width, it would opt to not split it at all. If that test case works for you, I'm in favor of removing the js.

**Comment by jrochkind** [comment]
OK I will try to find time to try it out and PR with info!

the odd thing is that the fixed width is being added to the span that includes the _count_ not the facet label... but I'll try to test everything weird I can think of, in FF specifically since that was mentioned in the original commit. 

(Also a reason why it's always a good idea to provide more info about reproducing the weird browser thing you are fixing in the commit or PR, otherwise it's hard to know if the workaround is still needed later!)

**Comment by bkeese** [comment]
Yeah, the browser can calculate the width of the label column from the fixed with of the count column. Fixing the width of the count column made more sense, since it's contents would never want to be wrapped.

**Comment by jrochkind** [comment]
okay, if there isn't already CSS directives to never wrap the count, that might be indicated. I'll check it out, thanks!

**Comment by jrochkind** [comment]
Ok, in trying to demo this, I am running into something I don't understand with Blacklight Javascript, that isn't like other Rails apps. 

My usual way of trying out new JS:

1. Make my local app point to a local on-disk checkout of Blacklight
2. Modify the JS there
3. restart my local app

And it usually has the new JS. But trying to use that method to change JS in [facet_load.js](https://github.com/projectblacklight/blacklight/blob/8b9041544553ce0dd0d979f9f39f78d94b30b46d/app/javascript/blacklight/facet_load.js#L6-L17) -- it does not work. My local app somehow still has the old unchanged copy of the JS.

This is an ordinary Blacklight 7 app generated according to the guide for generating a Blacklight app.  

I am vaguely recalling something funny going on in Blacklight with a need to do something special... somehow related to the webpacker/npm support... but I can't remember the details or where to find them.  The ["using the javascript" section of the README](https://github.com/projectblacklight/blacklight#using-the-javascript) seems to suggest there is something funny going on indeed, but I'm still not figuring out what it means. 

@bkeese do you understand what I need to do to try out JS changes, and to make commits with JS changes that will actually stick?

**Comment by jrochkind** [comment]
Oh wiat, I think the answer is in the [Building the javascript section of the README](https://github.com/projectblacklight/blacklight#building-the-javascript). 

OK, I'll mess around with it. Wow, this really raises the inconvenience of trying out Javascript changes.

**Comment by jrochkind** [comment]
OK, I did reproduce the problem. 

It's... really hard to explain. I was going to provide screenshots, but the "bad behavior" screenshot scrolled so far off my viewport it was hard to capture. 

but yes, you can reproduce with really long words in facet values. I reproduced in both Chrome and FF in fact. 

It seems that `table-layout: auto` (as opposed to fixed) really doesn't come up with very good column widths when combined with CSS hyphenation, indeed. 

So the solution was to use `table-layout: fixed`, and then try to use JS to figure out what the fixed width of the second column should be. It's a pretty hacky solution, because the width really isn't quite right (it's assuming 10 arbitrary characters have the width `10ch` in CSS, which they do not). And is subject to other bugs, like the one reported here, where it counts leading/trailing whitespace in deciding how many `ch`. 

It could possibly be solved with a lot of CSS hacking, maybe entirely different CSS not trying to use table layout (flexbox? grid depending on minimum browser support needed?). Especially since the minimum browser support has maybe changed since it was originally written. 

But I've spent a lot of time hacking on the facets CSS in my day too, I know it's a real thorny issue, so, okay!

So I think the workaround to the workaround, where `doResizeFacetLabelsAndCounts` uses JS `trim` to ignore leading/trailing whitespace when estimating number of characters--is still called for.
