### ISSUE TITLE
where is search relevance weighting defined for each term and how to change them

### ISSUE THREAD

**Issue by mankind** [projectblacklight/blacklight#2112]
1.  I was wondering if any one knows the blacklight and hyrax recommened way to boost a search term's relevance. For instance I added this alternative_title_tesim^4.15 below and it works but is this the recommended way
```config.add_search_field('all_fields', label: 'All Fields', include_in_advanced_search: false) do |field|
      all_names = config.show_fields.values.map(&:field).join(" ")
      title_name = solr_name("title", :stored_searchable)
      field.solr_parameters = {
        qf: "#{all_names} file_format_tesim all_text_timv alternative_title_tesim^4.15",
        pf: title_name.to_s
      }
end```

2. Where can I find the default boosting for various fields. I looked here https://github.com/projectblacklight/blacklight/blob/v6.12.0/solr/conf/solrconfig.xml#L87-L185  and saw some fields with boosting, I copied the file to my app in this case Hyku changed a few of them but the changes were not picked.

Can someone point me to where the default boosting comes from and how to override them in bulk.
Many thanks

**Comment by jcoyne** [comment]
You can do it this way, or you can put the boost in the solrconfig.xml (e.g. https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/solr/conf/solrconfig.xml#L44-L54). Doing it in solrconfig *might* be preferable as you don't have to send that parameter between blacklight and solr on every request.

**Comment by mankind** [comment]
Thanks Justin.
