### ISSUE TITLE
Deprecation warning directs users to private method

### ISSUE THREAD

**Issue by eliotjordan** [projectblacklight/blacklight#2115]
Deprecation warning for the `document_show_fields` method points to a private method.

https://github.com/projectblacklight/blacklight/blob/master/app/helpers/blacklight/configuration_helper_behavior.rb#L33

https://github.com/projectblacklight/blacklight/blob/master/app/presenters/blacklight/show_presenter.rb#L66-L69

**Comment by eliotjordan** [comment]
I see that `fields_to_render` is now the preferred method to use. I'm going to close this issue, but it is confusing for those upgrading from BL6.

**Comment by cdmo** [comment]
I noticed this same problem, on the code4lib slack I brought this up a bit ago. Wasn't sure it was a problem. But where did you find `fields_to_render` as the preferred method? I ended up using `blacklight_config.show_fields` directly.

Just to illustrate further, from `configuration_helper_behavior.rb`

```rb
  # used in the catalog/_show partial
  def document_show_fields _document = nil
    Deprecation.warn(self, "document_show_fields is deprecated and will be removed in Blacklight 8. Use ShowPresenter#fields instead")
    blacklight_config.show_fields
  end
```

but then `ShowPresenter#fields`  is a `private` method.
