### ISSUE TITLE
Improve facet-modal navigation

### ISSUE THREAD

**Issue by christinach** [projectblacklight/blacklight#2123]
Add a filter in the "more" facets modal where the user can type a value in the input field and return the facet if it matches an existing facet value. 
This implementation would help to navigate through several pages of a facet with many values. Please check: https://github.com/geoblacklight/geoblacklight/issues/815 for more info on this feature.

**Comment by jrochkind** [comment]
I think this is kind of hard to do with Solr, at least with the way we are using Solr, and it's unclear how to do it. Is one thing I think has kept it from happening before; it's been widely desired I think.

**Comment by magibney** [comment]
Interesting! @jrochkind is right that this has historically been difficult with Solr, but (for text values anyway) I think that the `facet.contains` param (as of Solr 5.1/6.0) could be used to implement this type of functionality: https://issues.apache.org/jira/browse/SOLR-1387

I think it would be worthwhile to move toward better support for more explicit, user-directed operations with facets, especially with the kind of high-cardinality facets that libraries often work with. The implementation might be tricky, but I think any movement in that direction would make facets much more useful.

Perhaps worth considering as part of this conversation, Penn's browse (name/subject/callno) is implemented over facets, and essentially provides functionality equivalent to the facet modal, but allowing users to navigate (via text input) to an arbitrary point in the index-order-sorted list of values (left-anchored, not substring-filtering).

**Comment by andrewbattista** [comment]
Well said! This is exactly what we are looking for in GeoBlacklight and it seems to make sense to have it developed upstream in Blacklight
