### ISSUE TITLE
iOS does not allow interaction with facet collapse icons

### ISSUE THREAD

**Issue by sensei100** [projectblacklight/blacklight#2127]
It seems that iOS does not allow a user to click on an element that is not a `<button>` or an `<a>` tag.  This was not reproducible when using chrome dev tools, but on an actual mobile device I could not open the facets with the icon. This was tested using both our library search site and the blacklight demo project.  There is more information about this issue here: https://github.com/kaliber5/ember-bootstrap/issues/355

In our project, I added the css style cursor:pointer to the facet-field-heading class and that resolved the problem.  Another approach could be to move the collapse actions to an `<a>` tag.  I am happy to do the work and submit a PR if you let me know which approach you would rather take to resolve the issue.

**Comment by cbeer** [comment]
Interesting; I'd vote to make the expand/collapse icon a button and applying the `.stretched-link` class to it to get it to make the header area clickable

**Comment by cdmo** [comment]
I don't know about anchor versus button, to me it's about the same. But, I do like making use of the existing underlying framework to solve a problem, so I'd vote for applying `.stretched-link` too.

I also think there's value in having the heading tag above the anchor/button in terms of accessibility and general web semantics (especially when the facet block is expanded).

**Comment by mejackreed** [comment]
Fixed in #2132
