### ISSUE TITLE
Update breakpoint at which sidebar goes from full-width to 3-col

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/blacklight#2133]
The facet sidebar is displayed at full-width in the default (`xsmall`) and `small` Bootstrap breakpoints. At the `medium` breakpoint and larger it is displayed in three columns next to the nine-column main content. From a UX point of view, @jvine and I are don't think that the showing the sidebar in three columns at the medium breakpoint is ideal. There is only enough space available to show 3 to 5 characters of each facet value, making for a pretty ugly and difficult to read display:

<img width="868" alt="Screen Shot 2019-09-16 at 11 26 23 AM" src="https://user-images.githubusercontent.com/101482/64983639-d05c6480-d875-11e9-8cbf-433b9a1060ba.png">

We recommend changing the responsive behavior of the sidebar such that it doesn't go to three columns unless we are in the `large` or `xlarge` breakpoints. This would mean that in the `medium` example shown above, the facets would be displayed above the main content and extend full-width of the content area (which is admittedly pretty wide for the facet elements but we think a worthwhile tradeoff).

I think the change needed is fairly simple; changing the `#sidebar`'s column specification to:

`<section id="sidebar" class="page-sidebar col-lg-3 order-first">`

from the current

`<section id="sidebar" class="page-sidebar col-md-3 order-first">`

but I wanted to bring it up as an issue rather than a PR to see if anyone has objections or sees a downside to this change.

(**Not** doing this has some implications for current ArcLight work.)

**Comment by jvine** [comment]
I think we also need to add the collapse behaviour - otherwise we end up with all facets listed before the search results.

<img width="848" alt="Screen Shot 2019-09-16 at 11 49 16 AM" src="https://user-images.githubusercontent.com/6945691/64984643-1e726780-d878-11e9-9a89-fb4f7a66c81b.png">

instead of

<img width="619" alt="Screen Shot 2019-09-16 at 11 49 26 AM" src="https://user-images.githubusercontent.com/6945691/64984683-321dce00-d878-11e9-9233-38ee02941d29.png">

**Comment by ggeisler** [comment]
I don't think we need to **add** it. Just ensure that the existing facet collapse behavior (which you can see in the `small` breakpoint) is adjusted if necessary to make sure it happens at the `medium` breakpoint as well.
