### ISSUE TITLE
Add jump links to pages

### ISSUE THREAD

**Issue by estelendur** [projectblacklight/blacklight#2144]
@mejackreed pointed out that [Arclight issue #840](https://github.com/projectblacklight/arclight/issues/840) could just as well be done here.

Quoting that ticket body:

----
Example implementation here: https://searchworks.stanford.edu - I copied this HTML and CSS from there and adjusted it a bit for visual style; but if there's a better way to implement this, feel free.

- [x] **Add a skip link section as the first div in the `<body>` tag.**

   ```
   <div id="skip-link">
       <a href="#search_field" class="element-invisible element-focusable" data-turbolinks="false">Skip to search</a>
    <a href="#main-container" class="element-invisible element-focusable" data-turbolinks="false">Skip to main content</a>
   </div>
   ```
"Skip to search" and "Skip to main content" should be present on all pages. 

- [x] **Style the links so they are invisible until they receive focus via tab key.**

   ```
   #skip-link .element-invisible {
       position: absolute !important;
       clip: rect(1px, 1px, 1px, 1px);
       overflow: hidden;
       height: 1px;
   }
   #skip-link {
       position: absolute;
       top: 5px;
       left: 10px;
       z-index: 1;
   }
   #skip-link .element-invisible.element-focusable:active, #skip-link .element-invisible.element-focusable:focus {
       position: static !important;
       clip: auto;
       overflow: visible;
       height: auto;
   }
   #skip-link a:focus {
       background-color: white;
       border-radius: 0 0 0.2rem 0.2rem;
       padding: .5rem 1rem;
   }
   ```

- [x] **Add a third link on search results pages**

   `<a href="#documents" class="element-invisible element-focusable" data-turbolinks="false">Skip to first result</a>`

**Comment by estelendur** [comment]
The search bar has autofocus on "catalog-like index page[s] without query or facet parameters", including the front page, which means that the skip links are not the first thing in the tab order. What should we do with this?

**Comment by mejackreed** [comment]
@jvine ? ^^

**Comment by jvine** [comment]
How did I miss that?! We should remove the autofocus. As much as people like to save a click, autofocus dumps a non-sighted user into an input with zero context. Let the user control when they're ready to search.

**Comment by mejackreed** [comment]
I wonder if we should make the auto-focus default configurable so that its "backwards" compatible?

**Comment by jvine** [comment]
I hate to say yes, because it's like... it's not good practice. But probably yes.

**Comment by estelendur** [comment]
Where would the configuration for that live?

**Comment by mejackreed** [comment]
It could live in `lib/blacklight/engine.rb`

**Comment by estelendur** [comment]
Is that a file that implementers would know to look at to edit? Would I just add a line like `config.enable_search_bar_autofocus = false`?

**Comment by mejackreed** [comment]
Yep that should do it. An implementer could alter this in their app using an initializer or in `application.rb`. If we want to maintain backwards compatibility we could do something like:

`config.enable_search_bar_autofocus = true # DEPRECATED: This will be removed in Blacklight 8`

Or something like that? 🤷‍♂

**Comment by estelendur** [comment]
Also, should the catalog_helper_behavior `should_autofocus_on_search_box?`, which is already marked deprecated, be set to always return false, or should I figure out how to make it play nicely, or what?

**Comment by mejackreed** [comment]
Maybe just update the conditional in `def autofocus?` to also check the config? Maybe its ok not to do it in both places?
