### ISSUE TITLE
Does blacklight support displaying results like solr/browse?

### ISSUE THREAD

**Issue by ukoyi** [projectblacklight/blacklight#2187]
Hi, guys
       I have indexed rich documents with solr 7.7.2  .  I take the content of the file as text field.  When searching using the Solritas UI ( http://my.com:8983/solr/collection1/browse ) the search results displaying like this:
     1. When there is no keyword query, the query results only show the first paragraph of the document.
     2. When querying by keyword, if there is matching content in the document, the relevant content part of the key will be displayed.
     Blacklight displays all the contents of the document。
     I want to use blacklight to achieve this effect. Does blacklight support this? If support，how to configure。
     I am new to solr. so pls suggest me in brief. Thanks in advance。

**Comment by jcoyne** [comment]
I don't believe this is something Blacklight can do. You could ask on the mailing list (http://groups.google.com/group/blacklight-development) if anyone has built something like that on top of blacklight.
