### ISSUE TITLE
v7.3.0 helper method breaks if collection.entry_name(..) is nil.

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#2192]
REF https://github.com/projectblacklight/blacklight/pull/2140#pullrequestreview-311262574

When we recently upgraded to the latest blacklight version (v7.3.0) our articles search breaks due to `collection.entry_name(..)` returning nil in our use case.

I feel like this is a breaking change that should be left for a major upgrade as it's not required to add the new functionality and it breaks sites that are already using BL and were depending on the fact that the code was already checking for nil.

In addition, I believe that we should have a clear interface for all response objects this kind of issue doesn't come back.

**Comment by cbeer** [comment]
Could you please post your stack trace too? It's not clear to me off-hand what's calling `collection.model_name` with the new code.

**Comment by sensei100** [comment]
@cbeer Here is the stack trace.

blacklight (7.3.0) app/helpers/blacklight/catalog_helper_behavior.rb:48:in `page_entries_info'
blacklight (7.3.0) app/views/catalog/_paginate_compact.html.erb:6:in

**Comment by dkinzer** [comment]
@cbeer Yeah, sorry ... it's when `collection.entry_name(..)` returns nil that we get the error.  I just posted code that got removed seems to account for nil situations which is why we didn't see issue before.
