### ISSUE TITLE
Remove left padding on "Limit your search" heading

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/blacklight#2217]
I think this issue crept in as part of the BS4 upgrade.

There's now some left padding on the "Limit your search" heading in the sidebar of the homepage and results page. I'm pretty sure most implementors will want the heading to be left-aligned with the left-edge of the facets:

![Screen Shot 2019-12-04 at 10 00 50 AM](https://user-images.githubusercontent.com/101482/70168378-941ef000-167d-11ea-99f5-f7c4599b6be6.png)

**Comment by jcoyne** [comment]
It looks like this is due to the `padding` on the `.navbar` class

**Comment by ggeisler** [comment]
I was thinking we'd just use a more specific selector to remove the left padding. Something like:

```css
.facets .navbar {
  padding-left: 0;
}
```

But I wanted to leave it to a developer to figure out the best combo of classes to use to be more specific, since there are several possible options.
