### ISSUE TITLE
Blacklight development flow; running test suite 

### ISSUE THREAD

**Issue by ewlarson** [projectblacklight/blacklight#2231]
Hi everyone,

I have a pretty simple, but important, PR for GeoBlacklight we'd like to submit upstream to Blacklight instead: https://github.com/geoblacklight/geoblacklight/pull/865

However! I don't know how to run Blacklight locally anymore. Am I to launch a docker instance of Solr? Also, I can't run the test suite via `bundle exec rake ci` now. How has that changed? The old ci task is still in master... Feeling lost here. Any new documentation I should read?

Once I'm back up and running, I can submit a PR. Thanks for the help!

**Comment by cdmo** [comment]
Here's my experience for what it's worth because I just had to do some of this to get a PR into blacklight_advanced_search.

```sh
git clone git@github.com:projectblacklight/blacklight.git
bundle
bundle exec rake
```

At this point there are errors related to solr not being there. I don't have the time at the moment to see the cause of that (also I rarely use solr_wrapper except for working on blacklight core gems), but a workaround is to go into the `.internal_test_app` directory and run `solr_wrapper`. Then go back and run `bundle exec rake` from the main blacklight directory.

The seed then runs ok and it finds solr. However, locally I have a number of failing specs related to sprockets 4.0.0 that all look like (see https://github.com/projectblacklight/blacklight_advanced_search/pull/109#issuecomment-574712087 where I hit this there too):

```
  71) Search Page shows vernacular (Linked 880) and call number
      Failure/Error: //= link_tree ../images

      ActionView::Template::Error:
        link_tree argument must be a directory
      # ./.internal_test_app/app/assets/config/manifest.js:1
      # ------------------
      # --- Caused by: ---
      # Sprockets::ArgumentError:
      #   link_tree argument must be a directory
      #   ./.internal_test_app/app/assets/config/manifest.js:1
```

I'm not sure exactly why this is happening locally for me, but I have a feeling it's related to my version of ruby locally. I know that Travis CI doesn't encounter these errors.

```
➜  blacklight git:(master) ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
```

**Comment by mejackreed** [comment]
Related to the changes in https://github.com/projectblacklight/blacklight/pull/2012#issuecomment-540750149

I think the @cdmo work around should work.

1. `cd` to `.internal_test_app`
1. Run `solr_wrapper` (if you have solr_wrapper installed globally)
1. run `rake` from top level directory

Sub-optimal developer experience for sure, lets fix this.

I'm open to reverting #2012. There seemed to be a lot of people interested in using docker locally for development from the comments there. I wonder if someone who is working on Blacklight development with solr/docker could contribute better documentation?

**Comment by cdmo** [comment]
I could give it a whack, working with docker for solr (only, not ruby yet anyway) has been smooth.

**Comment by mejackreed** [comment]
Also this comment might be useful: https://github.com/projectblacklight/blacklight/pull/2012#issuecomment-435448951

**Comment by whereismyjetpack** [comment]
Hi (semi-outsider here)

from what I can tell we're talking about how to run solr, and we probably shouldn't look at this any differently than something like postgres. i think a bit of this stems around the fact that solr_wrapper is kind of a black box to most developers. 

I would suggest standardizing on something like `docker-compose` and the developer simply runs `docker-compose up solr` to get solr, then rake tasks should _just work_ for the developer that doesn't want to run docker, or doesn't have the cycles now, we should provide a way to easily run solr_wrapper, or have the ci rake task detect that solr isn't running and give a friendly message pointing to docs on the various ways to start solr.

**Comment by cdmo** [comment]
Thanks for volunteering @whereismyjetpack 😉

**Comment by ewlarson** [comment]
Thanks @cdmo and @mejackreed for the tips. I'm off and running with the work around.

**Comment by cdmo** [comment]
Running the following worked for me too:

```
# Start doccker desktop
git clone git@github.com:projectblacklight/blacklight.git
cd blacklight
bundle
docker pull solr:7
docker run -d -p 8983:8983 -v $PWD/lib/generators/blacklight/templates/solr/conf:/myconfig solr:7 solr-create -c blacklight-core -d /myconfig
# wait for localhost:8983/solr to respond, like seconds
bundle exec rake
```

I pulled 7, but, that could easily be 8 or whatever version of solr of course.

And yeah I think a docker-compose up solr would be slicker.

**Comment by whereismyjetpack** [comment]
This is very similar to another PR the only exception being I was more explicit with the bind mount, and i gave solr data a volume so the developer can persist their solr data through restarts. 

given the following docker-compose.yml within the root of blacklight:

```
version: '3.5'

services:
  solr:
    image: solr:7
    volumes:
    - solr-data:/opt/solr/server/solr/mycores/blacklight
    - type: bind
      source: ./lib/generators/blacklight/templates/solr/conf
      target: /opt/solr/conf
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"


volumes:
  solr-data:
```
a developer only needs to run `docker compose up solr` or `docker-compose up solr -d` (to background it) to get a solr. If we begin to dockerize other layers of the stack, the ux is the same. 

this seemed to work for me in the 2 minutes of testing I did. another thing to note, solr 7 is a bit different than solr 8 in how it gets configuration and such, so i'm not convinced that swapping out the major version would work 1:1 

as for travis, it's docker support seems to be a bit behind others in this space, but not impossible 
you can do something like this to fire up solr before the build 

https://docs.travis-ci.com/user/docker/

**Comment by cdmo** [comment]
I just gave @whereismyjetpack's solution a try and it worked. Same set of instructions from earlier, just swap out the docker commands. So it's like:

```
# Start Docker Desktop
git clone git@github.com:projectblacklight/blacklight.git
cd blacklight
bundle
docker-compose up solr
# wait for above command to finish out, doesn't take long
# in new terminal:
bundle exec rake
```

**Comment by ewlarson** [comment]
@cdmo I too see a bunch of sprocket errors running the master branch test suite.  They all look like this:

```
  76) Bookmarks cites items in bookmarks
      Failure/Error: //= link_tree ../images
      
      ActionView::Template::Error:
        link_tree argument must be a directory
```

They disappear if you change your app/assets/config/manifest.js file to look like:

```
//= link application.js
//= link_directory ../stylesheets .css
```

Hope this helps!

**Comment by cdmo** [comment]
Thanks @ewlarson. Yeah, I think I did that to get rid of the error temporarily, but it comes back. Also, in my catalog application this will happen if I upgrade to the latest blacklight (I'm on 7.2.0). I think it's maybe a thing (bug maybe?) with a dependency of Blacklight (maybe latest rails 5?). Still poking around
