### ISSUE TITLE
Previous next error

### ISSUE THREAD

**Issue by cdmo** [projectblacklight/blacklight#2295]
I don't have a solution to this, admittedly, edge case problem, but I didn't see an issue for it so I thought I'd make one. This happens in a few production catalogs I tried as well as the blacklight demo app.

## Steps 

1. Do a search
1. Click into any result record
1. In the URL bar go to a different record directly

## The problem

The previous/next widget will display the context for the item you clicked on in step 2

## What I would have expected

The previous/next widget would not display at all. As is the case usually when you go directly to a record view.

**Comment by jcoyne** [comment]
Yes, this is a known concern. Because our paging is stored in the session, it gets confused when you run two sessions simultaneously.

**Comment by cdmo** [comment]
Assuming the only other option is to load a result link click with a solr query and then do that in every result view and then match against the current item to find position. I mean just writing it sounds crazy, definitely more expensive (and more problematic) paging based on actual solr query. More problematic in that rankings can potentially change over the course of a search, like if the index is updated and the algorithm returns different results.

Going to assume there is no fix for this, I'm fine with this being closed and marked "wontfix" or "works as designed" or whatever. Thanks.

**Comment by cdmo** [comment]
I'm considering this fixed. Thanks!
