### ISSUE TITLE
Move show page tools to page header area

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/blacklight#2316]
Part of #2314.

The way the show page tools are currently displayed -- in a sidebar box -- is arguably less than ideal in a couple of ways. First, just visually, the display in a dedicated sidebar box makes the tools, which in most cases are likely to be used only occasionally by users, very prominent. More importantly, if a Blacklight-based application wants to use the show page sidebar to display additional application-specific features it's challenging to display them in a way that makes them more prominent to the user than the Blacklight tools.

A specific example of this is in GeoBlacklight, where the show page sidebar can be used to show the user several types of resources and tools related to the current item. With the way the Blacklight tools are currently displayed, this results in a cluttered sidebar where the geo-specific tools are mixed in with the generic tools and they all have equal weight in the sidebar:

<img width="1146" alt="Screen Shot 2020-07-24 at 4 11 19 PM" src="https://user-images.githubusercontent.com/101482/88442224-9aa6d700-cdc8-11ea-8ed1-7826690023a0.png">

This ticket proposes moving the Blacklight tools out of a sidebar and to a set of buttons that goes in the page header area. This places them in a location where they feel de-emphasized but available, and provides more focused sidebar for applications like GeoBlacklight to place application-specific tools or features.

I'd suggest:

- Right-align the group of buttons on the same row as the pagination controls
- Style the buttons as `btn btn-outline-secondary btn-sm` 

Examples below.

## Item show page with no sidebar
![Blacklight - no sidebar column](https://user-images.githubusercontent.com/101482/88442616-0b022800-cdca-11ea-91d1-5dab59f390b2.png)

## Item show page with a sidebar containing an application-specific sidebar box
![Blacklight - with sidebar column](https://user-images.githubusercontent.com/101482/88442623-12293600-cdca-11ea-8ef3-8457a49402db.png)

## "md" (tablet) viewport width
I think the tools will still fit at this width, so no adjustment needed.

<img width="766" alt="Screen Shot 2020-07-24 at 4 25 12 PM" src="https://user-images.githubusercontent.com/101482/88442691-50265a00-cdca-11ea-96ad-1c45ce99061d.png">

## "sm" viewport width 
At the `sm` viewport width, the buttons should be collapsed:

<img width="574" alt="Screen Shot 2020-07-24 at 4 26 11 PM" src="https://user-images.githubusercontent.com/101482/88442797-b4e1b480-cdca-11ea-88cc-84066225017c.png">

## "sm" viewport width - expanded
And when they are expanded:

- Add `bg-light` to give the expanded section a light gray background so it's more clear to the user what the expand action has done
- Left-align the buttons in a vertical list

<img width="574" alt="Screen Shot 2020-07-24 at 4 27 08 PM" src="https://user-images.githubusercontent.com/101482/88442997-6c76c680-cdcb-11ea-9df0-760faf123bc0.png">

**Comment by hackmastera** [comment]
👍  from Princeton; we've done this in our catalog in response to usability testing.

**Comment by dnoneill** [comment]
How attached are you to the hamburger menu? We are implementing this design so I am working on this right now and we are just stacking the show tools below the prev/next 
![Screenshot 2024-08-14 at 5 35 39 PM](https://github.com/user-attachments/assets/a3626b35-d6ab-46c9-a773-5a554058a3e7)
