### ISSUE TITLE
Sprockets in Icon

### ISSUE THREAD

**Issue by cdmo** [projectblacklight/blacklight#2324]
The class [Icon](https://github.com/projectblacklight/blacklight/blob/c771e597df4fcf5bd700019f2a7157616e60a9af/app/models/blacklight/icon.rb#L74) relies on Sprockets. Not sure if it's a goal to make the application not rely on Sprockets in any way, but if it is I thought I'd bring this issue up. I don't have a solution really. We use FontAwesome locally for our application and are just using that for our search button icon as a replacement.

**Comment by barmintor** [comment]
See also #2670

**Comment by cbeer** [comment]
Closing this; I think #2670 is probably the sprockets-less way forward.
