### ISSUE TITLE
Update npm/yarn pakage blacklight-frontend

### ISSUE THREAD

**Issue by cdmo** [projectblacklight/blacklight#2325]
Looks like the current version of [blacklight-frontend](https://classic.yarnpkg.com/en/package/blacklight-frontend) is at 7.7. Can we get the latest release (7.10) pushed there? It has some scss changes. How does this get updated again? `npm-publish`? Thanks.

**Comment by cdmo** [comment]
The version is updated via https://github.com/projectblacklight/blacklight/pull/2311, not seeing it in yarn or npm yet though, must be another step.

**Comment by mejackreed** [comment]
The instructions are here: https://github.com/projectblacklight/blacklight/wiki/How-to-release-a-version

**Comment by cdmo** [comment]
All set now after #2327 👍
