### ISSUE TITLE
rails server -e production error

### ISSUE THREAD

**Issue by EkaX** [projectblacklight/blacklight#2328]
Hi

When i run rails server -e production i got error 
rails server -e production
=> Booting Puma
=> Rails 6.0.3.2 application starting in production 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 4.3.5 (ruby 2.7.1-p83), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/cache.rb:330: warning: Passing the keyword argument as the last hash parameter is deprecated
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/cache.rb:710: warning: The called method `get_entry_value' is defined here

**Comment by jcoyne** [comment]
That's not an error, that's the message that says the server is working.  There's also a warning message in activesupport (an upstream dependency) that you can ignore.   You can also set an environment variable to suppress warnings: `RUBYOPT="-W0"`
