### ISSUE TITLE
Error when run Quickstart

### ISSUE THREAD

**Issue by ghost** [projectblacklight/blacklight#2330]
Hello blacklight team, I meet with errors when running Quickstart-creating app in hard way. Basically, it's RSolr::Error::Http - 404 Not Found Error.

My OS: win10
Ruby version: 2.5.8
Rails: 6.0.3
Java: 1.8.0_112

No error shows up during the process of creating new app. When I begin to run:
1. `$bundle exec solr_wrapper`: solr is able to run and listening at port 8983
2. `$rake solr:marc:index_test_data`: 404 Not found error.
3. `$ rails server`: 
Completed 500 Internal Server Error in 84ms (ActiveRecord: 0.0ms | Allocations: 10772) Blacklight::Exceptions::InvalidRequest (RSolr::Error::Http - 404 Not Found Error: <html>...
4. `http://localhost:3000/catalog`: 
Blacklight::Exceptions::InvalidRequest in CatalogController#index RSolr::Error::Http - 404 Not Found Error: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>

I guess the blacklight core isn't running but I don't know the solution. Most ways to this problem are out-dated and something related to sunspot.yaml (currently sunspot gem does not need to install) and jetty. If you need more info on debug page feel free to let me know. I'm struggling for the solution to this problem. Thanks!

**Comment by fjorba** [comment]
I confirm that I found the same issue, following the same steps, on a Debian 10.6 Buster (stable).

**Comment by mejackreed** [comment]
@fjorba Were you able to run `rake solr:marc:index_test_data` after keeping `bundle exec solr_wrapper` running in another terminal? And before running the index process could you confirm that `http://127.0.0.1:8983/solr/blacklight-core/select?q=*%3A*` is available?

**Comment by fjorba** [comment]
Sorry, I'm not sure; as I didn't know whether to take the easy way or the hard way, and a the same time I was fighting with the #2384, I have not insisted on it.  While searching the buglist, I found this one and my purpose was to say that it does not only happen on Windows (as it would be so easy to point to).

Let my go back to the previous environment to answer your question.

**Comment by fjorba** [comment]
Oh, yes, I know!  No, I could not run `rake solr:marc:index_test_data` because of the #2384 bug, as I was using the Debian supplied Ruby 2.5.5:

```
$ rake solr:marc:index_test_data                                                                           
rake aborted!                                                                                                                                                                                         
TypeError: superclass mismatch for class Command                                                                                                                                                      
[...]/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:2:in `<class:Thor>'            
[...]/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:1:in `<top (required)>'           
[...]
$ ruby --version
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
```

**Comment by CoWerk** [comment]
Hi, 

I just ran in the same issue as @ghost. And regarding to your question, @mejackreed, I tried accessing http://127.0.0.1:8983/solr/blacklight-core/select?q=*%3A* and it does not work: I get a 404 Not found error.
Btw: I am using Ruby 2.7 as suggested in your Quickstart.

What can I do now? Thanks!

**Comment by mejackreed** [comment]
@CoWerk what is the output you receive when you run `bundle exec solr_wrapper` ?

**Comment by CoWerk** [comment]
It says 
`
Starting solr 8.8.0 on port 8983 ...
` 
and I can access http://localhost:8983/solr/#/blacklight-core/query. However, there is no blacklight core in the solr.
Thanks for getting back to me, @mejackreed!

**Comment by mejackreed** [comment]
Great.. so do you have a `.solr_wrapper.yml` file at the root of your application's directory?

**Comment by CoWerk** [comment]
Yes, I do. 
```
# Place any default configuration for solr_wrapper here
# port: 8983
collection:
  dir: solr/conf/
  name: blacklight-core
```

**Comment by mejackreed** [comment]
Great! So try running the following:

`bundle exec solr_wrapper clean` - this should clean up anything left behind for a fresh install
 and then `bundle exec solr_wrapper`

**Comment by CoWerk** [comment]
I get a message saying I need to stop solr first. But it seems `bundle exec solr_wrapper stop` is not a valid command.

**Comment by mejackreed** [comment]
Got it.. so maybe search for the solr_wrapper process and kill it `ps aux | grep solr_wrapper` then clean, then run `solr_wrapper`

**Comment by CoWerk** [comment]
Did that. But it doesn't change anything. Solr is still starting like before, but without any cores.
I also tried it from scratch, the easy and the hard way. Still the same result.

**Comment by mejackreed** [comment]
solr_wrapper using the `.solr_wrapper.yml` to configure its setup. Can you confirm the output of `ls ./solr` ? I'm wondering if those configurations did not come over somehow

**Comment by CoWerk** [comment]
There is a directory named "conf" and in there are schema, solrconfig etc. Also another directory named xslt. 

But /solr is not where the core is created, right?

**Comment by mejackreed** [comment]
Correct. It is the directory that solr_wrapper should pick up the config from. solr_wrapper is a convenience that many use to setup a disposable solr instance with Blacklight.

If you have a different way of starting up a solr instance you are welcome to do that, and use the config and schema from solr/conf. Others  use Docker to do this, but I usually end up using solr_wrapper.

**Comment by barmintor** [comment]
All the issues raised in this ticket appear to be resolved.
