### ISSUE TITLE
Drop IE11 support

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2332]
Microsoft itself is dropping IE11 support for Teams in November 2020 and in the rest of Microsoft 365 in Aug 2021. https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

Can blacklight do the same?  

This would allow us to use modern javascript without requiring Babel (e.g. https://github.com/projectblacklight/blacklight/pull/2161#discussion_r331052190)

**Comment by cdmo** [comment]
For what it's worth IE11 accounts for 1.3% of browser traffic according to StatCounter (viz at [Can I Use](https://caniuse.com/usage-table)). I am comfortable with dropping support. I'll add that it'd be fine with me to drop support across all projectblacklight gems and engines.

**Comment by seanaery** [comment]
Thanks for raising this issue, @jcoyne . Related: ES6 transpiling issues are biting ArcLight at the moment, so it's unusable in IE11 without more setup around Babel, etc., that is unclear to me how to do (See https://github.com/projectblacklight/arclight/issues/1010 & https://github.com/projectblacklight/arclight/issues/995). I support officially dropping IE11 support. IE accounts for a small percentage of visits to our ArcLight (1.4%), catalog (2.1%), and Samvera digital repository (1.0%). Seems like implementers could choose whether or not to take on the added complexity of transpiling for backward compatibility (using whatever tools suit their environment).

**Comment by cbeer** [comment]
I guess we've effectively done this with #2490, as arrow methods and optional chaining both won't work in IE.

**Comment by jcoyne** [comment]
@cbeer we probably could change that by configuring babel differently.
