### ISSUE TITLE
Bug introduced with configuration on index_actions

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#2368]
Introduced in ff8458f19bb6d8a3cff8da072ccf8a2f54db0082

When configuring index actions like this:

```ruby
    config.index.document_actions << :containers
```

These key only actions will not pass through the partial path or context to the `Blacklight::Document::ActionsComponent` as they are stripped of this information here:

https://github.com/projectblacklight/blacklight/blob/master/app/helpers/blacklight/component_helper_behavior.rb#L45

I would fix, but I'm not sure what the "right" thing to do here is.

**Comment by cbeer** [comment]
🤷‍♂️ ; the old code silently mutated the resulting action, which.. uh.. wasn't great.

I think downstream applications ought to use, e.g. `config.add_results_document_tool :containers ` and we should probably deprecate `<<`.

In the meantime... I guess we should fix the regression at least?
