### ISSUE TITLE
nil action_view.logger causes exceptions

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2379]
The [Rails documentation suggests](https://guides.rubyonrails.org/configuring.html#configuring-action-view):

> config.action_view.logger accepts a logger conforming to the interface of Log4r or the default Ruby Logger class, which is then used to log information from Action View. Set to nil to disable logging.

But if you set `config.action_view.logger = nil`, it causes exceptions to be raised from within Blacklight, `NoMethodError: undefined method `debug' for nil:NilClass`, from: 

https://github.com/projectblacklight/blacklight/blob/master/app/helpers/blacklight/render_partials_helper_behavior.rb#L176

The `logger.debug`. That's actually only one of many `logger.debug` in that file (and possibly other files) though. I'm not totally sure what pattern an engine like Blacklight is supposed to be using to not conflict with that Rails guide documentation about setting it to nil -- are they really expecting you to change every single `logger` call in an actionview-related area to eg `logger && logger.debug`? 

Don't really know what the right way to fix this is (if any? is it a bug in Rails or Rails docs?), but leaving this issue here in case someone else wants to research what's going on and figure out the right best practice, or failing that so if someone else runs into the problem in Blacklight, they might find this record searching and save themselves some time. 

Myself, I may try experimenting with this third-party null-logger gem, https://github.com/karafka/null-logger, and setting the logger to that instead of `nil`. I will report back how that works.

**Comment by jcoyne** [comment]
@jrochkind in rails they almost always check that logger is not nil before using it.

**Comment by jrochkind** [comment]
@jcoyne cool, so y'all think Blacklight should do the same? That's a pain, and probably hard to keep a regression from happening, unless you test everything with a nil logger!

In the meantime, for the release of Blacklight I am using, I a going with a much hackier way of disabling actionview logging, from  https://stackoverflow.com/questions/12984984/how-to-prevent-rails-from-action-view-logging-in-production/61893582

**Comment by jcoyne** [comment]
@jrochkind yes, "when in Rome..."

**Comment by jrochkind** [comment]
Thanks for quick resolution!
