### ISSUE TITLE
Blacklight 7.0.0 dependency on Thor 1.0.1 may require Ruby 2.7

### ISSUE THREAD

**Issue by fjorba** [projectblacklight/blacklight#2384]
I've tried to follow the https://github.com/projectblacklight/blacklight/wiki/Quickstart guide (_the hard way_), and I got an error in this step:

```
$ rails generate blacklight:install --devise --marc --solr_version=latest
[...]
[...]/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:2:in `<class:Thor>': superclass mismatch for class Command (TypeError)
```

According to the original bug report (https://github.com/erikhuda/thor/issues/721) this should be an incompatibility with the system supplied (Debian, in my case) Thor 0.19.4-1 version. However, even after upgrading the system Thor to 1.0.1 (see https://github.com/erikhuda/thor/issues/721#issuecomment-731988462), the error still appears.

But it turns out that, in another Debian computer, where I followed the https://github.com/projectblacklight/intro-to-blacklight-2020 steps and, thus, having a custom Ruby 2.7.1, this error does not appear.  The thor requirement appears in the Gemfile.lock due to some chained requirement, but I'm not sure to make a good diagnostic.

So it seems that the easy solution would be to require Ruby 2.7.  I'd love to know a better way, but I haven't found it.

**Comment by mejackreed** [comment]
Thanks for raising this issue @fjorba . Looking at the thread it seems like there are some issues with Debian / bundler that we may not be able to solve here.

I would recommend installing Ruby for development using a Ruby version manager ([example](https://gorails.com/setup/ubuntu/19.10#ruby-rbenv)) for local development purposes. This may help alleviate bundler issues and Ruby version mismatch errors and easily switch between different Ruby environments.

**Comment by fjorba** [comment]
But not only for development, right @mejackreed?  I mean, if my tests (=development) run fine and I put my first pure Blacklight in production (in this case it will be for librarians internal use, to easily browse, search and discover oai harvested records), I will have to use Ruby 2.7, and thus I'll have to use some Ruby version manager as you suggest.

Do you confirm that Blacklight can run, as described, with  Ruby as old as 2.2.2? There is also the #2383 issue, that implies Ruby 2.5+; I'm rising it.

**Comment by jcoyne** [comment]
Ruby 2.4 and earlier are past EOL, so we don't support Blacklight on those versions: http://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/

**Comment by mejackreed** [comment]
> thus I'll have to use some Ruby version manager as you suggest

Yes, this would be the recommended practice in a deployment scenario for a Ruby on Rails application. Whether the application is hosted in a container or on a server, using a Ruby version manager (often rvm or rbenv) would allow you to deploy your application on a specified version of Ruby rather than tied to the system itself.

> Do you confirm that Blacklight can run, as described, with Ruby as old as 2.2.2? There is also the #2383 issue, that implies Ruby 2.5+; I'm rising it.

I cannot confirm this, however we do run continuous integration tests for Ruby 2.5 and there are recent successful builds against Ruby 2.5.8 https://github.com/projectblacklight/blacklight/runs/1366303635?

**Comment by fjorba** [comment]
Thanks, I've updated https://github.com/projectblacklight/blacklight/wiki/Quickstart to change the requirement to 2.5 and recomending 2.7, so newcomers like me have less headaches.
