### ISSUE TITLE
Are nodejs and yarn hard Blacklight dependencies?

### ISSUE THREAD

**Issue by fjorba** [projectblacklight/blacklight#2385]
After several failed tests, I've come to the conclusion that nodejs and yarn are needed, at least, to follow the https://github.com/projectblacklight/blacklight/wiki/Quickstart Blacklight instructions.  I'm unsure yet if they are hard dependencies.  Are them?

I would update the Quickstart guide with something like the follow paragraphs, but I don't dare to write it on the wiki because there may be errors in my instructions, as I'm not familiar with the Javascript ecosystem either.  If my instructions are obvious for experienced Rails developers, please forgive me, but after some Rails exposure in the last year, I failed to know that both nodejs and yarn are part of the pack.

Please feel free to reuse and/or this text to update the wiki or, if it are correct, I'll happily add it myself.

### Got nodejs?

```console
$ node --version
v10.21.0
$ nodejs --version
v10.21.0
```

You may install node, a Javascript runtime library,  from your OS packaging system, if available, or following the https://nodejs.org/  instructions. Node and Nodejs are synonyms and often one symlinks the other.

### Got yarn?

```console
$ yarn --version
1.22.5
```

Yarn is needed to install Javascript packages and its dependencies, as part of the Rails Webpacker gem.  Please follow the https://yarnpkg.com/en/docs/install instructions.  Yarn is very sensible to being up to date, so unless your OS package is the same than upstream, you'll get errors.  To avoid them, better use upstream version.

**Comment by jcoyne** [comment]
A javascript runtime (not necessarily, but most commonly "nodejs") is required by the Rails asset pipeline.  See https://guides.rubyonrails.org/asset_pipeline.html

Yarn is optional. You may choose to use it, but some people prefer to use the asset pipeline that delivers javascript libraries as gems.

**Comment by fjorba** [comment]
Until I installed yarn I've had many mysterious errors, including duplicated requirements in the Gemfile, with different software versions, and other strange situations that, for a Rails newcomer like me, looked like insurmountable difficulties.  They mysteriously disappeared after I installed yarn, but from upstream, not the Debian package, because it was not up to date.

I'm trying to improve the documentation to help other newcomers like me.  Experienced Rails developers probably don't need this help, but I do.  Maybe preceding them with a sentence like this one would be better?

> If you are not familiarized with different javascript runtimes or don't have an opinion about the different Rails asset pipelines options, installing nodejs and yarn will make your Blacklight installation easier

On the other hand, I also got another error:

> ActionView::Template::Error (Your ExecJS runtime therubyracer (V8) isn't supported by autoprefixer-rails, please switch to Node.js (V8) or mini_racer (V8)

I overcame it changing the Gemfile this way:

```
-gem 'therubyracer'
+gem 'mini_racer'
```

I'd happily add the error and the solution to the Quickstart page, if you think that it is correct.

**Comment by jcoyne** [comment]
@fjorba I understand your frustration.  Part of the problem here is that blacklight is software on top of Rails, which is undergoing a transition in how it handles assets. That means there is more than one "right way".  The Blacklight team is not entirely in agreement about the best way to do this, and so we attempt to allow the implementer to make these choices for themselves.

Personally, I like using webpacker, yarn and nodejs.   I believe that some of the other implementers (even at my institution, Stanford) like using sprockets + nodejs.   So for me, your original suggestions were right on, but I'm trying to be considerate of other opinions on this.

**Comment by fjorba** [comment]
Of course. And if I write the sentence in an even more conditional mood, reusing some of your words, like:

> Blacklight is built on top of Rails, which is undergoing a transition in how it handles assets. That means there is more than one "right way".  If you are not familiarized with different javascript runtimes or don't have an opinion about the different Rails asset pipelines options, installing nodejs and yarn will make your Blacklight installation easier. However, Blacklight allows other choices, like using sprockets and nodejs.

And then the two got this, got that? Do you thing that this would make everybody satisfied enough?  I do think that a friendly hand is needed for newcomers.

**Comment by jcoyne** [comment]
That is a wonderful change.  It's fantastic to have someone looking at the docs with a critical eye and a beginners perspective. Feel free to add that to the wiki.

**Comment by fjorba** [comment]
Done, thanks for your support: https://github.com/projectblacklight/blacklight/wiki/Quickstart
