### ISSUE TITLE
Docker-compose container exiting with code 0

### ISSUE THREAD

**Issue by CoWerk** [projectblacklight/blacklight#2389]
Hi,

I tried setting up Blacklight by using Docker (since I'm working on Windows and nothing else seemed to work). 
But when I run
`docker-compose up`
both containers are started and then the blacklight_app container just exits again:

`docker-compose up --build
WARNING: The PWD variable is not set. Defaulting to a blank string.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Building app
Step 1/10 : ARG ALPINE_RUBY_VERSION
Step 2/10 : FROM ruby:${ALPINE_RUBY_VERSION}-alpine
 ---> 59d4ec426ed6
Step 3/10 : RUN apk add --update --no-cache   bash   build-base   git   libxml2-dev   libxslt-dev   nodejs   sqlite-dev   tzdata
 ---> Using cache
 ---> c35e8e6ea3ef
Step 4/10 : RUN mkdir /app
 ---> Using cache
 ---> 4c8bade9edc9
Step 5/10 : WORKDIR /app
 ---> Using cache
 ---> 539c52983a64
Step 6/10 : RUN gem update --system &&   gem install bundler &&   bundle config build.nokogiri --use-system-libraries
 ---> Using cache
 ---> 84a59a566f9b
Step 7/10 : COPY . .
 ---> 7770700c3088
Step 8/10 : EXPOSE 3000
 ---> Running in 5a10dd4879f2
Removing intermediate container 5a10dd4879f2
 ---> bdbe62d5b778
Step 9/10 : CMD [".docker/app/entrypoint.sh"]
 ---> Running in 81e17f1c1db2
Removing intermediate container 81e17f1c1db2
 ---> d476b8cd39be
Step 10/10 : HEALTHCHECK CMD curl --fail http://localhost:3000 || exit 1
 ---> Running in 00e6aaaae1bd
Removing intermediate container 00e6aaaae1bd
 ---> 66c68550f421

Successfully built 66c68550f421
Successfully tagged blacklight_app:latest
Starting blacklight_solr_1 ... done                                                                                                                                                          Recreating blacklight_app_1 ... done                                                                                                                                                         Attaching to blacklight_solr_1, blacklight_app_1
solr_1  | Executing /opt/docker-solr/scripts/solr-precreate blacklight-core /opt/solr/conf -Xms256m -Xmx512m
solr_1  | Executing /opt/docker-solr/scripts/precreate-core blacklight-core /opt/solr/conf -Xms256m -Xmx512m
solr_1  | Core blacklight-core already exists
solr_1  | Starting Solr latest
solr_1  | The currently defined JAVA_HOME (/usr/local/openjdk-11) refers to a location
solr_1  | where java was found but jstack was not found. Continuing.
app_1   |
app_1   | rm -f /app/.internal_test_app/tmp/pids/server.pid
app_1   | bundle install
app_1   | exec bundle
app_1   | exec rake blacklight:server["-p 3000 -b 127.0.0.1"]
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
solr_1  | 2020-12-07 09:10:17.481 INFO  (main) [   ] o.e.j.u.log Logging initialized @1540ms to org.eclipse.jetty.util.log.Slf4jLog
blacklight_app_1 exited with code 0`

I already tried attaching the line `command: tail -f /dev/null` to the app in my docker-compose file. Then the container didn't exit, but I still couldn't access it on localhost:3000. Solr is started correctly and works, however.

Any help is welcome.
Thanks!

**Comment by CoWerk** [comment]
Hi,

so, I tried to fix this myself, but up until now, I have not finally succeeded. I temporarily added the line 
`ENTRYPOINT ["tail", "-f", "/dev/null"] `
instead of
`CMD [".docker/app/entrypoint.sh"]` 
to my Dockerfile, so the docker container would be up and running, which gave me the chance to enter the container.
So, then I tried entering the lines of entrypoint.sh one by one in the docker bash of the container blacklight_app_1.
![image](https://user-images.githubusercontent.com/75610512/102094020-1d850880-3e22-11eb-8f71-9398ca0b79ab.png)

In my Gemfile.lock there are sometimes problems with the version of deprecation, but I could fix that.
Also, I had to change my docker-compose.yml, because the path for the solr volume was not set correctly. Instead of 
`$PWD/lib/generators/blacklight/templates/solr/conf:/opt/solr/conf `
I had to use the line
`$PWD/lib/generators/blacklight/templates/solr/conf:/var/solr/data/blacklight-core/conf`
and thus, I also had to change the entrypoint in the docker-compose.yml.

Next, I needed to edit the paths in .internal_test_app/config/blacklight.yml to `http://127.0.0.1:8983/solr/#/blacklight-core`.

After all of that, the server is now up and tells me it is listening on port 3000.

But STILL Blacklight is not really working for me. Its been more than a week of work for me now, and the only route which seems to be working is localhost:3000/search_history 
I have never worked with ruby before, and I am at my wits end now. I see that the only route defined in my routes.rb is the route for search_history. But how can I define others? It seems I need the right controllers, but having to understand the whole code base is a lot if you just want to set up a test case.

If anyone knows how I can fix the routes, please, any help is appreciated very much!
Thanks!

**Comment by barmintor** [comment]
It looks like, from https://github.com/projectblacklight/blacklight/issues/2330, that you were able to get things running, so I will close. It is also relevant to this ticket that there are fixes for docker-compose in `main` since #2559
