### ISSUE TITLE
bookmars.json bookmarks/format=json endpoint fails with server error.

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#2390]
I was doing some qa-ing of our bookmarks implementation and got the following error when I went to

http://localhost:3000/bookmarks?format=json

> undefined local variable or method `render_search_results_as_json' for #<BookmarksController:0x00007f8d20d1a470> Did you mean? render_search_bar

I checked to see if the blacklight demo site has a similar issue and it does: 

https://demo.projectblacklight.org/bookmarks?format=json

> {"status":500,"error":"Internal Server Error"}

**Comment by cbeer** [comment]
It looks like we removed `render_search_results_as_json` in Blacklight 6.0:

https://github.com/projectblacklight/blacklight/pull/1317

The replacement is not appropriate in this context, because it renders urls for pagination, search fields, facets, etc that won't work in the bookmark context.

**Comment by dkinzer** [comment]
I guess we can close this then.
