### ISSUE TITLE
Using custom logic for displaying record titles doesn't work as documented

### ISSUE THREAD

**Issue by vstollen** [projectblacklight/blacklight#2424]
I've tried to use custom logic to display document titles in the index and show views. Therefore I tried setting my own `IndexPresenter` and `ShowPresenter` by setting `config.index.document_presenter_class` and overriding the `label` method, as described in [the wiki](https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#add-custom-logic-for-displaying-record-titles-in-search-results).

Overriding the `heading` method on the other hand worked for me. If the wiki entry is indeed incorrect and overriding `heading` is the intended way for doing this, I'd be happy to improve the wiki entry.

**Comment by jcoyne** [comment]
Which documentation is showing a method that doesn't work? What does it show?

**Comment by vstollen** [comment]
The wiki entry I linked called "Configuration Results View", under the Headline "Add custom logic for displaying record titles in search results".

If I understand it correctly it suggests overriding the `label` method and using a custom `IndexPresenter` to modify the title displayed for the documents. This is shown in their code example:
```rb
# app/presenters/my_presenter.rb
class MyPresenter < Blacklight::IndexPresenter
  def label(field_or_string_or_proc, opts = {})
    # Assuming that :main_title and :sub_title are field names on the Solr document.
    document.first(:main_title) + " - " + document.first(:sub_title)
  end
end

# app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  ...
  configure_blacklight do |config|
    ...
    config.index.document_presenter_class = MyPresenter
    ...
  end
  ...
end
```

Overriding the `label` method changed nothing for me. In fact my `label` method wasn't even called while rendering the catalog index.

**Comment by barmintor** [comment]
The versions in scope for this ticket -- in January 2021 -- were v7.14.1 and v6.24.0

v7.14.1
=====
In v7.14.1 the document component uses (by default) the presenter `heading` method either directly or indirectly via `html_title`:
https://github.com/projectblacklight/blacklight/blob/v7.14.1/app/components/blacklight/document_component.rb#L69
https://github.com/projectblacklight/blacklight/blob/v7.14.1/app/presenters/blacklight/document_presenter.rb#44

v6.24.0
======
In v6.24.0 (before ViewComponent was introduced) the index presenter's `label` method was used for the html title:
https://github.com/projectblacklight/blacklight/blob/v6.24.0/app/presenters/blacklight/document_presenter.rb#L62

The wiki was updated in April of 2021 to describe the two major version branches' approaches: https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View/_compare/efacf1ababfc3203d4ef3ca0080fcd0ef3a554d1...44caada4929f7e8ef5070a3eeb80902f7c5b17a6
