### ISSUE TITLE
Secondary faceting looses original facet query when sorting A-Z in facet window

### ISSUE THREAD

**Issue by nomadicoder** [projectblacklight/blacklight#2426]
Given faceted search results, switching facet sort from Numerical to A-Z shows shows all items instead of the searched results.

**Steps to reproduce**

1. Visit to PA Digital Funnelcake app: https://funnelcake.padigital.org/
2. Apply primary facet or basic search query. Two examples given:

ex. Intermediate Provider: https://funnelcake.padigital.org/?f[intermediateProvider_ssim][]=POWER+Library+as+sponsor+and+HSLC+as+maintainer

ex. Basic search: https://funnelcake.padigital.org/?utf8=✓&search_field=all_fields&q=philadelphia

3. Go to a secondary facet option and open up facet window

4. Switch to A-Z view 

**Expected behavior**

Facet functionality should allows for multiple filters and use of the A-Z sort view. 

**Actual behavior**

When one switches to the A-Z sort view, it displays all facet values for that field in the index, rather than subset within the primary filter.

**Analysis**:

The original facet query is not carried over to the A-Z button link.

In the basic query example, after expanding the Language facet, the more link is 

https://funnelcake.padigital.org/catalog/facet/language_ssim?f[intermediateProvider_ssim][]=POWER+Library+as+sponsor+and+HSLC+as+maintainer

Clicking on this ink reveals the full list of facets for the query. The A-Z button link is 

https://funnelcake.padigital.org/catalog/facet/language_ssim?facet.sort=index

However, it should be similar to

https://funnelcake.padigital.org/catalog/facet/language_ssim?facet.sort=index&f[intermediateProvider_ssim][]=POWER+Library+as+sponsor+and+HSLC+as+maintainer

**Comment by mejackreed** [comment]
It is possible this is resolved in https://github.com/projectblacklight/blacklight/pull/2425 ?

**Comment by cbeer** [comment]
Yes, I think it is fixed by #2425.

**Comment by nomadicoder** [comment]
Confirmed, #2425 fixes. Closing! Thanks @cbeer and @mejackreed!
