### ISSUE TITLE
Instance upgrade from 7.16.0 to 7.17.0 and upwards fails to load facets.

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#2465]
We're running into an issue upgrading our  local instance to any version after 7.16.0.  All versions after 7.16.0 do not render our facets as expected.

Expected:
<img src="https://user-images.githubusercontent.com/444215/119831206-09fac500-becb-11eb-9c61-d35c265810a7.png" width="400" alt="Image of expected rendered facets"/>

Actual:
<img src="https://user-images.githubusercontent.com/444215/119831012-d4ee7280-beca-11eb-8aea-26d380393aaa.png" alt="Image of actual rendered facets" width="400"/>

**Comment by jcoyne** [comment]
Are you using blacklight-hierarchy here?  What version?

**Comment by dkinzer** [comment]
@jcoyne we are not using blacklight-hierarchy here.

**Comment by cbeer** [comment]
Can you replicate this in the blacklight test app or demo app?

**Comment by dkinzer** [comment]
The issue was caused because we were overriding a facet field component and I guess a recent upgrade updates how that works and we needed to incorporate that change into our override:

https://github.com/tulibraries/tul_cob/pull/2650/files#diff-3944ade5b0be86324ad6ca8248d0a446aaa99574decae53578eb25c3ff48dafcL5
