### ISSUE TITLE
Add facet.missing support

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#2480]
Recently we added `facet.missing` support to one of our BL instances.  Basically this allows the user to filter for documents that are missing values for specific fields.

![image](https://user-images.githubusercontent.com/444215/125514125-fa413284-24f0-4279-8972-45c9e00217a7.png)

I wasn't sure if at some point BL supported this feature and then it got dropped because I noticed that there are some references to facet.missing in the current codebase; i.e. https://github.com/projectblacklight/blacklight/blob/8aec662334dfdd3eefcfd7628971051ae9569f3d/lib/blacklight/solr/response/facets.rb#L173

But, I also read in an old ticket that `facet.missing` is not supported in BL (https://github.com/projectblacklight/blacklight/issues/1130#issuecomment-77307264).

Is this is a feature that makes sense to have in BL?

I am willing to work on a PR to port the changes I made to our instance to get the feature working.  It would be nice to not have to maintain that customization on our local instance.

Is this something that appeals to others?

**Comment by jrochkind** [comment]
I'm not sure what's going on here in current BL code, but this is a current spec that seems to suggest BL handles facet.missing already? 

https://github.com/projectblacklight/blacklight/blob/9a82fe4e26e6278d7acf686544b99c69336cc0ac/spec/models/blacklight/solr/response/facets_spec.rb#L144-L169

If it's not working, is that a bug?  I'm confused what's going on -- what makes you think it's not working, @dkinzer, in what way does it not work for you?

Here is the other hit in source code I got for grep "facet.missing".

https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/solr/response/facets.rb#L171-L176

Not sure why the comment calls it "legacy"?  This commit from @cbeer added the word "legacy" to that comment: 433d25f . Maybe @cbeer has more context about this feature?

If it isn't meant to be supported, I don't know why there's a spec for it?  But if there's a spec for it, I don't know why it's not working?  I also don't know why this feature would be removed if it were previously there!

**Comment by dkinzer** [comment]
OK, I think I remembering that maybe the implementation is missing something.  I'll try spinning up an fresh instance and locally and update this issue.

**Comment by dkinzer** [comment]
@jrochkind OK, I've spun up a local fresh instance of blacklight.  I updated one of the fixture documents by deleting the language fields. There are 30 documents and only 29 of them have language fields.  I do not see a facet.missing link for the the language facet.

Does there need to be some kind of configuration to enable showing that?  So as far as I can tell this feature is broken.

**Comment by dkinzer** [comment]
> I'm not sure what's going on here in current BL code, but this is a current spec that seems to suggest BL handles facet.missing already?

I think the code is misleading.  The spec is testing some conditional that is somehow not actually met in the out of the box code and there doesn't seem to be a configuration for enabling enabling this feature.

**Comment by dkinzer** [comment]
OK, I'm going to close this issue.  The real issue is that the feature is currently not working as expected.  I will submit a separate ticket.
