### ISSUE TITLE
How to generate a tree structure based on the file directory  as a facet field

### ISSUE THREAD

**Issue by ukoyi** [projectblacklight/blacklight#2484]
hi,guys
  I have used solr to index the file system and use the returned file diectory as a facet field.
  I would like to generate a tree structure based on the file directory . How ? Have any experience in this?
  Thank you in advance！

**Comment by cbeer** [comment]
https://github.com/sul-dlss/blacklight-hierarchy has information about indexing + faceting by a hierarchically constructed field.
