### ISSUE TITLE
Can't run tests locally

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2485]
I am trying to run tests locally from instructions at: https://github.com/projectblacklight/blacklight/wiki/Testing-and-Developing-Blacklight#getting-started

I can't get tests to run locally. I would be really curious if anyone else can, if even someone can confirm or deny if they can get tests to run locally -- starting from a fresh `rm -rf Gemfile.lock .internal_test_app/` situation -- that would be useful information!

* ruby 2.7.4
* bundler 2.1.4 (or 2.2.27, same result)
* engine_cart 2.3.0
* master checkout with no local modifications, at 9a82fe4e26e627

I go through the steps in Testing/Getting Started, and when I get to `rake`, this is the output:

```
$ rake
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      minitest (>= 5.1)
      Available/installed versions of this gem:
      - 5.14.4
      - 5.13.0
      rails-html-sanitizer (~> 1.0, >= 1.2.0, ~> 1.1)
      Available/installed versions of this gem:
      - 1.4.2
      - 1.4.1
      - 1.3.0
      nokogiri (>= 1.6)
      Available/installed versions of this gem:
      - 1.12.4
      - 1.12.3
      - 1.11.7
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
You must `gem install bundler` and `bundle install` to run rake tasks
rake aborted!
LoadError: cannot load such file -- engine_cart/rake_task
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
tasks/blacklight.rake:3:in `<top (required)>'
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:326:in `load'
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:326:in `block in load'
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/jrochkind/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:326:in `load'
/Users/jrochkind/code/blacklight/Rakefile:13:in `<top (required)>'
/Users/jrochkind/.gem/ruby/2.7.4/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by jrochkind** [comment]
When I try the ["Step by step with more control"]() directions, error happens at early step `rake engine_cart:generate`, same error. So that's where the error is happening... still no idea how to get past it.

**Comment by jrochkind** [comment]
If I follow the "step by step with more control" directions, and use `bundle exec` everywhere... I can get tests to run! and pass! Hooray!

(There are *lots* of deprecation warnings printed out by blacklight's own test suite -- both Blacklight and ViewConfig deprecations -- but that's a different issue).

**Comment by edsu** [comment]
I had the same issue (Ruby 3.1.1) following along in the Testing and Developing docs: `rake` failed but `bundle exec rake` worked.

**Comment by barmintor** [comment]
@jrochkind given that the wiki page mentions `bundle exec`, albeit somewhat opaquely, and the test suite runs for you, can this issue be closed? Or edited to reflect a requested documentation change?
