### ISSUE TITLE
Update references to "master" in the wiki.

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#2514]
I've created the following patch to address issue.  It can be applied directly to the wiki repo at https://github.com/projectblacklight/blacklight.wiki.git by a committer:

https://gist.github.com/dkinzer/045b6de39174774407b1673127520657

You'll need to clone the repo first apply the patch and then push up.  Wiki's are still using "master" branches.

**Comment by jcoyne** [comment]
I completed these edits.
