### ISSUE TITLE
Assignment to undeclared variable Blacklight

### ISSUE THREAD

**Issue by vstollen** [projectblacklight/blacklight#2540]
With version [v7.21.0](https://github.com/projectblacklight/blacklight/releases/tag/v7.21.0) I get the following error in the browser console:

```
Uncaught ReferenceError: assignment to undeclared variable Blacklight
```

The error points to [line 3 of blacklight.js](https://github.com/projectblacklight/blacklight/blob/fa8435060d077e4c2223eb5c2c4701853d2357ef/app/assets/javascripts/blacklight/blacklight.js#L3):
https://github.com/projectblacklight/blacklight/blob/fa8435060d077e4c2223eb5c2c4701853d2357ef/app/assets/javascripts/blacklight/blacklight.js#L1-L5

I believe this is the result of the addition of `use strict` in the new update. As a result, our `show_tool`s now open in a separate page, instead of a modal:

#### Expected:
![grafik](https://user-images.githubusercontent.com/14787415/142635107-05d566a4-aea6-4f6f-84ac-bbb88458d983.png)

#### Result:
![grafik](https://user-images.githubusercontent.com/14787415/142635512-40427b1d-34de-4090-bebf-013887e5d068.png)

**Comment by jcoyne** [comment]
@vstollen the code you are looking at on the main branch is for 8.x, not for 7.21

You want to look at this code: https://github.com/projectblacklight/blacklight/blame/v7.21.0/app/assets/javascripts/blacklight/blacklight.js#L3

I suspect we need a `const` here: https://github.com/projectblacklight/blacklight/blob/v7.21.0/app/javascript/blacklight/core.js#L1

**Comment by vstollen** [comment]
Can confirm, that adding that const, fixed it for me.

**Comment by jcoyne** [comment]
@vstollen can you try v7.21.1 ?

**Comment by vstollen** [comment]
@jcoyne sorry for the late answer. Just tested it out, everything seems to work as expected again. Thanks for the quick fix!
