### ISSUE TITLE
Resolve view components deprecation of `require "view_component/engine"

### ISSUE THREAD

**Issue by hackartisan** [projectblacklight/blacklight#2619]
When blacklight pins view component to 2.46 or higher (in the course of regular maintenance or feature work requiring a later version of view component) it will be good to resolve this deprecation.

This deprecation was introduced in 2.46. https://viewcomponent.org/CHANGELOG.html#2460

The require is here https://github.com/projectblacklight/blacklight/blob/31a3990ccf9e389a0962876b09b6ff31f5e3fd77/lib/blacklight/engine.rb#L3

Currently Blacklight requires view component 2.43. https://github.com/projectblacklight/blacklight/blob/31a3990ccf9e389a0962876b09b6ff31f5e3fd77/blacklight.gemspec

**Comment by hackartisan** [comment]
Yes! And that should fix it. It just hasn't been released I guess. Should it be backported to 7.x?

**Comment by jcoyne** [comment]
Yeah, I don't believe there is a release for this.  Backporting seems like a good idea to me.

**Comment by hackartisan** [comment]
I can do a backport PR. I can't apply the label or assign myself, though, because of permissions.
