### ISSUE TITLE
Deprecation - Blacklight v7 - constraint_query_label helper method

### ISSUE THREAD

**Issue by ewlarson** [projectblacklight/blacklight#2620]
We're seeing a deprecation warning for the `constraint_query_label` helper method running GeoBlacklight with Blacklight v7.22.2:
https://github.com/geoblacklight/geoblacklight/issues/1146

Will there be a future Blacklight v7 release that back ports the component-based equivalent?

Related work:
https://github.com/projectblacklight/blacklight/commit/08f6dff56a81f8e2837cca540137406aa6a5433d

**Comment by barmintor** [comment]
Fixed by implementation of the FilterField API downstream in https://github.com/geoblacklight/geoblacklight/pull/1163
