### ISSUE TITLE
Alter Handing of errors from Solr

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2660]
Per discussion at Committer's Call 2/19/22. 

## Context

Blacklight currently (and for a long history) turns any error from Rsolr connection into a redisplay of search page with the message "Sorry, I don't understand your search"

* RSolr turns every HTTP 4xx or 5xx (at least) into raised RSolr::Error::Http https://github.com/rsolr/rsolr/blob/master/lib/rsolr/client.rb#L219-L220
* Blacklight turns every RSolr::Error::Http into a Blacklight::Exceptions::InvalidRequest https://github.com/projectblacklight/blacklight/blob/main/lib/blacklight/solr/repository.rb#L82-L83
* Blacklight rescues every InvalidRequest by re-displaying catalog home, with a message “Sorry, I don't understand your search” https://github.com/projectblacklight/blacklight/blob/main/app/controllers/concerns/blacklight/catalog.rb 

Things that could cause this chain include an HTTP 404 or 500 response from solr being *entirely down*, a temporary network or Solr server error, or a misconfiguration mismatch between Blacklight configuration and Solr schema/configuration. 

As far as we can tell, the historical motivation for this behavior was that when using the `lucene` query parser (Blacklgiht was written back before dismax existed/was so universal), a user could enter something that would be a query parser syntax error.  However, probably few if any installations are currently using the `lucene` query parser. Using the current standard `dismax`/`edismax` parser, as far as we know there's nothing a user can enter that would result in a Solr error response that could be corrected by changing user entry. 

## Why it's a problem

* First, it's just very bad UX to tell the user "Sorry, I don't understand your search" when the error is actually unrelated to their search entry, and nothing they do to change their search entry will resolve the error. (If it goes away on a subsequent search, that was not related to them changing their input). 

Also, it hides the error from developers/operators in several ways. Compare to an analogous database error, under Blacklight an Rsolr error:

* It does not show up logs as a fatal uncaught exception. What does show up is dependent on custom Blacklight code, and relies on Blacklight logic to make sure you have exception message and same relevant context you'd get from standard Rails error logging, which sometimes doesn't happen. 
* Does not end up caught by error monitoring services like HoneyBadger etc
* Results in a 200 HTTP response, so also isn't caught by a monitoring service checking for 200 HTTPs -- Solr could be entirely down, with any search resulting in an error -- and to the monitoring service, everything is just fine. 
* In development mode, normally you'd get Exception message details in the browser window, which would help you understand the problem -- whether Solr is just down or your blacklight configuration is wrong can often be apparent from the Solr exception message, but because it's been rescued as a non-error, you don't get any of that in the browser window in development, you have to go searching through logs to try and understand why you are getting an error. 

In my actual app, before I locally disabled this error rescuing, I had multiple occasions where my production Solr was down for all users for a long time, and my error reporting and monitoring failed to alert me to this.  I think this is.a bad "gotcha" for less expert operators running a BL instance. 

## Original proposal

I proposed that Blacklight simply *stop* doing this.  The original motivation for this behavior (lucene parser syntax errors) is gone, so what it's doing is no longer what was originally intended, it's applying to unintended behavior. 

Solr errors are analagous to database errors, there is no reason for Blacklight to treat them specially. Different apps may likely have different desires of how to handle this and other errors. A local app can easily implement it's own `rescue_from` to handle RSolr errors, database errors, or general errors how it wants. Many production apps already do implement their own general logic for exceptions, how they are displayed to the user and reported to ops -- which this BL logic interferes with. 

Some people at the discussion agreed, but there was not consensus.  The main reason not to agree, I believe, was that in their experience  Solr errors were especially common/likely in production, so they thought BL needed to have out of the box behavior handling them in a customized and more user-friendly way. 

Another option would be to make this custom error-handling configurable, but perhaps default configured "off" (or to be so in a future major release). But this also didn't have consensus. 

## Future possiiblities?

It's still pretty clear to me the existing behavior is very broken, and I personally don't know why we'd even want to offer it as a configuration option, it seems just wrong. But I guess others disagree and like the current behavior, or something similar to it?

It was suggested that there might be a way to  continue having a built-in custom error page for Solr errors, while no longer exhibiting any of the problems noted in bullets above:

> Configure ActionDispatch to handle the error and draw a certain page. Honeybadger will still get the error, and you can have a pretty handler.

It was suggested that @jcoyne knew something about this and could provide more info.  

I'm not sure what the desired error message would be, presumably *not* "Sorry I don't understand your search".

**Comment by jrochkind** [comment]
If anyone finds this issue annoyed at this behavior, and would like to simply disable this error-rescuing behavior from your local Blacklight app, you can do so at least in current Blacklight versions I have used (7.x, but probably also previous), by adding this method override in your CatalogController (and/or any other controllers you are using with 'catalog' behavior):

```ruby
private def handle_request_error(exception)
  raise exception
end
```

**Comment by tpendragon** [comment]
Blacklight committer's call on 3/16/2022 consensus seems to be to stop capturing this error. We support a PR for that. The committers may put it behind a configuration option - we'll discuss that and build on that PR when it happens.
