### ISSUE TITLE
Bookmark create method does not check for invalid input

### ISSUE THREAD

**Issue by sandbergja** [projectblacklight/blacklight#2665]
I am trying to add a custom validator to our Bookmark model.  With the validator in place on the model, when I send invalid input to the BookmarkController#create, nothing persists to the database (as expected), but the controller still considers it a success, so I can't notify the user about the validation issue.  The issue is on this line: https://github.com/projectblacklight/blacklight/blob/3c204022a278bab6e4fad4d17422627b63f28d06/app/controllers/concerns/blacklight/bookmarks.rb#L83-L85

`current_or_guest_user.bookmarks.create(bookmark)` will return bookmark [whether or not validations pass](https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-create) -- so, a truthy value even if nothing got persisted to the database.

I think checking `current_or_guest_user.bookmarks.create(bookmark).valid?` instead should do the trick.  PR coming up.

**Comment by tpendragon** [comment]
@sandbergja I think if you do `create!` it'll throw an error on invalid params, if that's helpful.
