### ISSUE TITLE
Blacklight 8 should require Solr 8+

### ISSUE THREAD

**Issue by barmintor** [projectblacklight/blacklight#2779]
With the release of Solr 9 in May 2022, all versions of Solr < 8.11 are outside of [official support]( https://solr.apache.org/downloads.html#about-versions-and-support). As of Blacklight 8, the engine should require Solr 8+, and be able to rely on Solr 8 features in its query builders, etc. This should be reflected in the README and wiki.

**Comment by hackartisan** [comment]
Why?

@barmintor wrote: "With the release of Solr 9 in May, all versions of Solr < 8.11 are outside of official support: https://solr.apache.org/downloads.html#about-versions-and-support"

**Comment by cbeer** [comment]
Updated https://github.com/projectblacklight/blacklight/wiki.
