### ISSUE TITLE
solr port problem Please help

### ISSUE THREAD

**Issue by nassdoc** [projectblacklight/blacklight#2806]
Starting Solr 9.0.0 on port 8983 ... bundler: failed to load command: solr_wrapper (/home/biblio-database/.rbenv/versions/3.1.2/bin/solr_wrapper)
/home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solr_wrapper-4.0.2/lib/solr_wrapper/instance.rb:324:in `exec': Failed to execute solr start: *** [WARN] *** Your open file limit is currently 1024.   (RuntimeError)
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
*** [WARN] ***  Your Max Processes Limit is currently 30834. 
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh

Port 8983 is already being used by another process (pid: 4494)
Please choose a different port using the -p option.

. Further information may be available in /tmp/solr-9.0.0/server/logs
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solr_wrapper-4.0.2/lib/solr_wrapper/instance.rb:75:in `start'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solr_wrapper-4.0.2/lib/solr_wrapper/instance.rb:64:in `wrap'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solr_wrapper-4.0.2/exe/solr_wrapper:113:in `<top (required)>'
	from /home/biblio-database/.rbenv/versions/3.1.2/bin/solr_wrapper:25:in `load'
	from /home/biblio-database/.rbenv/versions/3.1.2/bin/solr_wrapper:25:in `<top (required)>'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:58:in `load'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:23:in `run'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/cli.rb:485:in `exec'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/cli.rb:31:in `dispatch'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/cli.rb:25:in `start'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/exe/bundle:48:in `block in <top (required)>'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /home/biblio-database/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/exe/bundle:36:in `<top (required)>'
	from /home/biblio-database/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /home/biblio-database/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'

**Comment by cjcolvar** [comment]
The error message says you already have a process using port 8983. It may be another solr already running.  Stop the other process and try again.

**Comment by nassdoc** [comment]
Actually sir my knowledge is weak on this area please help how to stop this
process.

**Comment by cjcolvar** [comment]
You should be able to run `lsof -ti :8983` to get the process id and then use that to stop it with `kill <processid>`.  All together this would be: ```kill `lsof -ti :8983` ```  If that all works correctly then it should stop the other process.  If that doesn't work then you could try restarting your computer.

**Comment by nassdoc** [comment]
Ok thank you sir

**Comment by nassdoc** [comment]
Sir please help how to install vufind.

**Comment by jcoyne** [comment]
This repository is for Blacklight.   We don't have any experience with vufind.

**Comment by bess** [comment]
Closing this issue. User is looking for help with vufind, not blacklight.

**Comment by nassdoc** [comment]
Ok sir if  any suggestions for vufind please tell me.
