### ISSUE TITLE
Using forward and back buttons causes more bookmark controls

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2860]
<img width="337" alt="Screenshot 2022-10-31 at 4 53 32 PM" src="https://user-images.githubusercontent.com/92044/199117643-9297431d-ff55-40f6-ab1a-9e22b05a7513.png">

Only the last one added actually works to create the bookmark.

**Comment by dkinzer** [comment]
I can't reproduce this on the demo site so issue must only be introduced to the main branch.

**Comment by jcoyne** [comment]
yes, the demo site runs BL 7
