### ISSUE TITLE
ViewComponent 2.75.0 breaks blacklight

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2867]
<img width="677" alt="Screen Shot 2022-11-02 at 3 04 28 PM" src="https://user-images.githubusercontent.com/92044/199613845-d84e650b-e41a-448c-9e1c-5a980fed6a10.png">

**Comment by jcoyne** [comment]
<img width="859" alt="Screenshot 2022-11-02 at 5 23 35 PM" src="https://user-images.githubusercontent.com/92044/199613967-f4bb9183-df65-4e42-96bb-94305246ba59.png">

**Comment by jcoyne** [comment]
@barmintor do you have any insights into this?  It looks like the problem is around Blacklight::Component.

**Comment by barmintor** [comment]
Is this not the #2816 issue?

**Comment by barmintor** [comment]
Hmm - the error suggests that `Arclight::SearchResultComponent.view_component_path` returns `nil`?

**Comment by barmintor** [comment]
I think it's https://github.com/ViewComponent/view_component/commit/22dbe8f648b44cc73d9663082a3e5024345b28ee

The component doesn't have default `config` yet.

**Comment by barmintor** [comment]
It looks like the default config in 2.75.0 is set up in a load hook on `view_component`, but the initializer that sets that hook up requires `config.view_component.instrumentation_enabled = true` to be in your Rails Application.

**Comment by jcoyne** [comment]
It looks like https://github.com/ViewComponent/view_component/issues/1565

**Comment by barmintor** [comment]
Yep. Did setting `instrumentation_enabled` have an effect?

**Comment by jcoyne** [comment]
> Did setting instrumentation_enabled have an effect?

No, I see the same problem with or without.

**Comment by jcoyne** [comment]
<img width="310" alt="Screenshot 2022-11-03 at 8 22 34 AM" src="https://user-images.githubusercontent.com/92044/199731971-deb60de5-eadf-4ba8-a701-08d5772ae3e9.png">

**Comment by jcoyne** [comment]
This PR fixes the CI build for the main branch.
