### ISSUE TITLE
Vernacular scripts (utf8) must display properly

### ISSUE THREAD

**Issue by MrDys** [projectblacklight/blacklight#29]
CODEBASE-2: concerned about display of UTF8 due to Ruby being less UTF8 friendly.   

Latest Ruby is supposed to make this easier in some way ...

We know Bob got the searching working (yay bob!) with solrmarc.

It's a deal breaker for us if we don't get the non-latin stuff displaying well.  Our librarians have already tested our vufind searchworks for at least the following:

chinese
hebrew
arabic
russian
cyrillic
all sorts of diacritics

right to left issues for hebrew arabic (and whatever else)
-  we have "display" fields in our index and can hammer this stuff into submission, but does ruby have any cool built in stuff to do it (or gems or something)

There is already some example data in the solrmarc svn project.  It's currently in the 2.0 branch, under test/data

  unicornWHoldings
  hebrew
  diacriticTests
  non-latin <--  I didn't put that there, so I don't know what's in it.

If we need more examples, I can certainly get them.  I'm only confident there's already hebrew and chinese in there, and lots of diacritics.  I was trying to write tests for the diacritics, but I couldn't get them to pass and fail at the right times.  
- Naomi

**Comment by RobertaDoros** [comment]
It’s important that you know about [Ultram dosages](http://www.tramapills.com) before you start taking the medicine. Once you know about the dosage follow it strictly and sincerely on regular basis. In case of any confusion regarding the dose kindly contact the doctor and ask for help.
