### ISSUE TITLE
Error in log : FATAL --ActionView::Template::Error (Could not find table 'users'):

### ISSUE THREAD

**Issue by ftheeten** [projectblacklight/blacklight#2931]
Dear all,

I'm installing and evaluating Blacklight 7.0.4 for a project (while being not very familiar with Rails). I can run it by manually starting it from Rails server on port 3000, and I'm currently trying to bind to Apache via Passenger.
I had several errors in the Apache logs related to privilege escalation with Passengers, and one error in the Blacklight log as I forgot to manually deploy the asset.
 
Currently the app fails with this error :

    [2022-12-13T11:06:28.568390 #1518] FATAL -- : [cec3f8a6-2ccb-4ba8-a404-6cfa871c8b9c]
    [cec3f8a6-2ccb-4ba8-a404-6cfa871c8b9c] ActionView::Template::Error (Could not find table 'users'):
    [cec3f8a6-2ccb-4ba8-a404-6cfa871c8b9c]     1: <ul class="navbar-nav">
    [cec3f8a6-2ccb-4ba8-a404-6cfa871c8b9c]     2:   <%= render_nav_actions do |config, action|%>
    [cec3f8a6-2ccb-4ba8-a404-6cfa871c8b9c]     3:     <li class="nav-item"><%= action %></li>
    [cec3f8a6-2ccb-4ba8-a404-6cfa871c8b9c]     4:   <% end %>
    [cec3f8a6-2ccb-4ba8-a404-6cfa871c8b9c]     5:

I probably missed a step when initializing the SQLite database, but which one ?

**Comment by dkinzer** [comment]
I'm not sure what you have tried or if the project is new or already has a populated database.  If it's completely new you may have forgotten to run the database init step `bundle exec rails db:init` (i think).   And if the project already had a database then you might have forgotten to run the migrations `bundle exec rails db:migrate`.

**Comment by ftheeten** [comment]
Hi,

Thanks for your reply. I indeed to forgot to initialize the SQLite database.
    bundle exec rails db:migrate
was giving errors though....
I reinstalled the Rail environment of project, without devise and, and at some point I had to run  
     bin/rails db:environment:set RAILS_ENV=development
To have 
    bundle exec rails db:migrate
Running without error. Blacklight is running now

**Comment by jcoyne** [comment]
keep in mind that SQLite is only appropriate for testing and development. you want to install a real RDBMS in production.  If you had to switch environments on the database, this is likely because you were using the same instance for more than on environment(development, test, production). You should avoid doing this.
