### ISSUE TITLE
Create deprecation around show_fields_for when the parameter is a scalar

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2934]
In BL 8 the passed value  must be an enumerable.

https://github.com/projectblacklight/blacklight/commit/21d16ebf059e75fd2a8979cf0e31f9e39a810de4#diff-861527298e7fd89776954e6197d054200aca67452da7e2f4296334e3f746b6ccR413

**Comment by sandbergja** [comment]
Closed by #2938
