### ISSUE TITLE
Bug on demo.projectblacklight.org - emailing bookmarks

### ISSUE THREAD

**Issue by maxkadel** [projectblacklight/blacklight#2958]
### Summary
When trying to email a bookmark, the application hits an error, which it displays in the modal, which you then cannot close using the "X" button. Refreshing the page dismisses the modal. 

### How to reproduce error
0. Create new account for https://demo.projectblacklight.org/ (I don't know if this is necessary, but is what I had done)
1. Log in to https://demo.projectblacklight.org/
2. Do an empty search
3. Click the "Bookmark" checkmark next to the first result
4. Click "Bookmarks" in the top toolbar (should have a "1" next to it)
5. Click "Email"
6. Fill out form with email associated with your account, and some kind of message-looking message (I used "Possible book for project")
7. Click "Send"
8. You will see error message (see below)

### Screenshot
![image](https://user-images.githubusercontent.com/45948126/213211058-70b86b9e-7ac2-4c69-a869-54798b61eb8e.png)
#### Image description
Screenshot of modal with error messages. 
- The header has the message "There was a problem with your request"
- The body has the message "Expected a successful response from the server, but got an error" and then the code snippet:
```
POST /bookmarks/email
500: Internal Server Error
```
- On the top right there are two different "X" buttons superimposed on each other (they do not work to close the modal)

### System information
- MacOS Version 13.1 (22C65)
- Apple M1 Pro
- Google Chrome Version 108.0.5359.124 (Official Build) (arm64)

**Comment by cbeer** [comment]
I think the demo site isn't configured to send email:

![Screen Shot 2023-01-18 at 09 47 41](https://user-images.githubusercontent.com/111218/213256266-97ff2f2c-6531-4651-8cea-a4b55d8ac7e6.png)

**Comment by maxkadel** [comment]
I'd be ok with closing this, since it seems unlikely that we want to configure it to send email.
