### ISSUE TITLE
7.x - Success flash messages from modals display twice

### ISSUE THREAD

**Issue by maxkadel** [projectblacklight/blacklight#2960]
For actions like emailing bookmarks or sending a record via SMS that open in a modal, when the action is successful the modal is closed and the flash message is displayed on the main page. If you dismiss this message and then reload the page (or go to a different page, or open a modal), the flash message is displayed again. 

As a user, I would expect not to see the message again after dismissing it the first time. 

Since the Blacklight 8 uses a different implementation for flash messages (turbo-streams), this fix is not needed on the main branch

### On initial submit
![Bookmark page displays success flash message](https://user-images.githubusercontent.com/45948126/214407029-97dd7378-7187-4561-948f-2afddfb5b87a.png)

### After dismissing first modal
![Bookmark page with no flash message](https://user-images.githubusercontent.com/45948126/214407139-db934500-2208-4b8d-812f-7e1c80fbf68e.png)

### After dismissing and doing a new search
![Search results page with success flash message](https://user-images.githubusercontent.com/45948126/214407301-9ed7ee21-c258-43df-aba0-107cc02470c0.png)

**Comment by sandbergja** [comment]
closed by #2961
