### ISSUE TITLE
Cannot use button to close modals with Bootstrap 4

### ISSUE THREAD

**Issue by christinach** [projectblacklight/blacklight#2971]
1. Create an internal_test_app. 
2. Change the bootstrap version in the Gemfile to '~> 4.6'.
3. `bundle install`
4. `bundle exec rails s`
5. Open the email modal.

Option 1. When using the mouse to click the close button. The modal will not close.

Option 2. When using the tab key to navigate to the close button and 'enter' then the modal will close.

In the first option we (@maxkadel, @sandbergja, @rladdusaw, @regineheberlein, @christinach) noticed that the event 'target' is looking for the span class 'visually-hidden' and not the button class 'blacklight-modal-close btn-close close'.

**Comment by jcoyne** [comment]
It sounds like this code will have to be updated to look for this markup on an ancestor rather than the target itself. https://github.com/projectblacklight/blacklight/blob/main/app/javascript/blacklight/modal.js#L144-L145
