### ISSUE TITLE
Importmap exposes assets that are not precompiled

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#3024]
```
"blacklight/bookmark_toggle"=>#<struct Importmap::Map::MappedFile name="blacklight/bookmark_toggle", path="blacklight/bookmark_toggle.js", preload=false>
```

Here we add the items to the importmap: https://github.com/projectblacklight/blacklight/blob/main/config/importmap.rb#L3

But this results in:

Sprockets::Rails::Helper::AssetNotPrecompiledError in Spotlight::Catalog#show

Showing /Users/jcoyne85/workspace/sul-dlss/dlme/app/views/layouts/spotlight/base.html.erb where line #21 raised:

Asset `blacklight/bookmark_toggle.js` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link blacklight/bookmark_toggle.js

**Comment by jcoyne** [comment]
It appears that I was just missing: https://github.com/projectblacklight/blacklight/blob/9e517006cf8373af1d623c2664276038a2258b2e/lib/generators/blacklight/assets/importmap_generator.rb#L25

**Comment by ygorg** [comment]
I solved this issue by executing `rails generate blacklight:install` from https://github.com/projectblacklight/blacklight/issues/3031#issuecomment-1499416786.
And adding an extra line in `app/assets/config/manifest.js`
