### ISSUE TITLE
rails g blacklight:install error 

### ISSUE THREAD

**Issue by jamesmichiemo** [projectblacklight/blacklight#3041]
The rails g blacklight:install script is encountering backslashes that Bundler doesn't seem to like. Do I need to find a Bundler version that reads backslashes inside of gem versions?
 
```
[!] There was an error parsing `Gemfile`: Illformed requirement ["\\~\\>\\ 5.1"]. Bundler cannot continue.

 #  from /Users/jmichiem/projects/special-collections/Gemfile:78
 #  -------------------------------------------
 #  gem 'rsolr', '>= 1.0', '< 3'
 >  gem 'bootstrap', '\~\>\ 5.1'
 #  -------------------------------------------
```

**Comment by jcoyne** [comment]
I think this is a result of https://github.com/projectblacklight/blacklight/commit/f491661ad0a7e105c80e66a7625725c38072dff8  I'm not sure why that is not unescaping for you.  Can you give it a try  with `BOOTSTRAP_VERSION=5.2.3 bin/rails g blacklight:install`?
