### ISSUE TITLE
Built-in advanced search is not actually searching

### ISSUE THREAD

**Issue by sandbergja** [projectblacklight/blacklight#3042]
When using the advanced search form, all the results in the entire index are returned, rather than just the relevant ones.

For what it's worth, it seems that installing the latest alpha release of `blacklight_advanced_search` gem allows this to work.

### Steps to recreate on the demo site

1. Go to https://demo.projectblacklight.org/catalog/advanced
2. In the "All fields" field on the advanced search form, type "snakes"
3. Submit your search
4. Note that you get every record in the index, few of which have to do with snakes.

### Steps to recreate locally

1. docker-compose up -d solr
1. rake engine_cart:generate
1. cd .internal_test_app
1. bundle exec rake blacklight:index:seed
1. bundle exec rails s
1. In your browser, go to http://localhost:3333/catalog/advanced
1. In the "All fields" field on the advanced search form, type "Strong"
1. Submit your search
1. Note that all 30 results in the index appear.

**Comment by sandbergja** [comment]
@maxkadel and I investigated this today, and found that the `adv_search_clause` method is expecting a key in the blacklight config called `clause_params`:

https://github.com/projectblacklight/blacklight/blob/883e0cd343f7d596299ef0c3f38a47704a579d39/lib/blacklight/solr/search_builder_behavior.rb#L110-L112

There is a test for this behavior, and it mocks this config like so:

https://github.com/projectblacklight/blacklight/blob/883e0cd343f7d596299ef0c3f38a47704a579d39/spec/models/blacklight/solr/search_builder_spec.rb#L827-L831

Is this feature intended to work if you haven't configured this value for each field?  If not, do we set it in the catalog controller, and are there any example configurations we could consult?

**Comment by dkinzer** [comment]
@cbeer, from the commit history for this  feature it looks like you introduced it around BL v7.15.0. I'm wondering if it's still a work in progress or is the fhe fact it currently doesn't work out of the box is a regression of some sort?

**Comment by barmintor** [comment]
Moving conversation here from Slack:
- The `clause_params` configuration has to be done per-field; it has to have a key for the query type (edismax by default)
- The configuration is done in the controller's blacklight config block
- The advanced search form displays UI for all search fields that don't explicitly disable advanced search, and so may include unconfigured fields that do not result in search clauses
- if no configured fields have query values, the default search (q.alt: *:*) will match all records

**Comment by dkinzer** [comment]
If you are using Solr9 instead of Solr8 the feature does not work even if `clause_params` are configured per-field.

**Comment by barmintor** [comment]
The queries appear to work in Solr 9 if the top-level `defType` is specified as "lucene"; this is the case in Solr defaults, but not the Blacklight default schema.
