### ISSUE TITLE
Document the steps needed to get advanced search working

### ISSUE THREAD

**Issue by carolyncole** [projectblacklight/blacklight#3060]
The steps outlined by @barmintor in slack here https://code4lib.slack.com/archives/C54TB5WDQ/p1687452502967029
 were tested by @sandbergja.

These should be converted into some actual documentation

**Comment by sandbergja** [comment]
I filled out the [configuration section of the wiki page](https://github.com/projectblacklight/blacklight/wiki/Advanced-Search#configuration) that @mksndz started, based on the testing from @barmintor, @dkinzer, @maxkadel, @christinach, and myself.
