### ISSUE TITLE
Unsupported ViewComponent slots in SMS and Email tools

### ISSUE THREAD

**Issue by body-clock** [projectblacklight/blacklight#3102]
The gemspec for Blacklight specifies a version of ViewComponent that is `'>= 2.66', '< 4'`. In my project, with ViewComponent 3.0, the SMS and Email tools were not rendering correctly. Per the [ViewComponent changelog](https://viewcomponent.org/CHANGELOG.html#300rc1), ViewComponent 3.0 contains the following breaking changes:
- BREAKING: Remove deprecated slots setter methods. Use with_SLOT_NAME instead.
- BREAKING: Remove deprecated SlotsV1 in favor of current SlotsV2.

The SMS and Email tools are still rendered using the deprecated setter methods. Here's the SMS code for example:
```erb
<%= render Blacklight::System::ModalComponent.new do |component| %>
  <% component.title { t('blacklight.sms.form.title') } %>

  <% component.body do %>
    <%= render 'sms_form' %>
  <% end %>
<% end %>
```
This code can be fixed by updating it to the following:
```erb
<%= render Blacklight::System::ModalComponent.new do |component| %>
  <% component.with_title { t('blacklight.sms.form.title') } %>

  <% component.with_body do %>
    <%= render 'sms_form' %>
  <% end %>
<% end %>
```
The alternative solution is to limit the ViewComponent version to something < 3.0, but it seems like transition to the newer setter methods has been started.

**Comment by jrochkind** [comment]
Can you say what version of Blacklight you are using please? What version this is broken with, and what version you were previously using that it worked with?

It sounds like maybe we don't have tests covering those components. :(

**Comment by jrochkind** [comment]
As a workaround until this is fixed, you can probably get things to work by continuing to use `view_component` 2.x in your app.  If the version of BL you are using supports both 2.x and 3.x, you can use 2.x in your app simply by adding this to your local app Gemfile:

    gem "view_component", "~> 2.0"

**Comment by body-clock** [comment]
I'm using Blacklight 8.0.1. I don't have previous experience with Blacklight, so that's all the info I have. I was able to fix this temporarily by adding the following to my gemfile:
```
gem 'view_component', '~> 2.66'
```
Thanks for your quick reply.
