### ISSUE TITLE
Please release 8.2.1

### ISSUE THREAD

**Issue by dchandekstark** [projectblacklight/blacklight#3165]
We also need the fix in 5f847ecff11a91bc7aad5e0ff783faee9832ff20.  (Thanks and hi, @corylown !)

Thanks,
David

**Comment by marlo-longley** [comment]
Hi @dchandekstark -- we are hoping to do this today on my Stanford team. Can update here when completed.

**Comment by marlo-longley** [comment]
This has been published to npm and rubygems. Thank you.
