### ISSUE TITLE
Devise - Views not Bootstrap'd

### ISSUE THREAD

**Issue by ewlarson** [projectblacklight/blacklight#3264]
Default Devise views do not have bootstrap classes/styling applied, causing them to render awkwardly in the application. As a Bootstrap-based project, it would be best to ship bootstrap'd versions of these views.

### Log in
![Screenshot 2024-08-08 at 3 09 21 PM](https://github.com/user-attachments/assets/84405b2a-5c4f-4acc-8960-b66975b0b432)

### Sign up
![Screenshot 2024-08-08 at 3 09 30 PM](https://github.com/user-attachments/assets/20357fb8-7af8-41d7-8915-0d4c483ea0dc)

### Edit user
![Screenshot 2024-08-08 at 3 09 57 PM](https://github.com/user-attachments/assets/cc354ab3-c155-431c-9a61-0d2d75dec8fe)
 
### Forgot password
![Screenshot 2024-08-08 at 3 10 09 PM](https://github.com/user-attachments/assets/1a6d245c-ccf3-430a-a0ff-2a400c7f2e84)

### Related
https://github.com/geoblacklight/geoblacklight/issues/1373

**Comment by jcoyne** [comment]
I recommend this is left as an exercise for the implementer.  We don't require devise. Many implementations don't use it.  Since Rails is adding a [sessions generator in Rails 8](https://github.com/rails/rails/pull/52328), we should explore whether Devise is still worthwhile.

**Comment by ewlarson** [comment]
Closing. Yeah, that makes a lot of sense for BL as Devise is optional. We'll discuss whether to add these views directly to GBL's repo.
