### ISSUE TITLE
When viewing a show page, the @show = false and it is trying to get the translation for blacklight.search.index..label

### ISSUE THREAD

**Issue by dnoneill** [projectblacklight/blacklight#3303]
This line seems to be false
https://github.com/projectblacklight/blacklight/blob/69373f202753f04ec6aca179fdf8fa01248a9edf/app/components/blacklight/metadata_field_component.rb#L14

which means this line https://github.com/projectblacklight/blacklight/blob/69373f202753f04ec6aca179fdf8fa01248a9edf/app/components/blacklight/metadata_field_component.rb#L19 never gets hit

**Comment by jcoyne** [comment]
Do we need to pass `show:` here perhaps? https://github.com/projectblacklight/blacklight/blob/main/app/components/blacklight/document_component.rb#L130C1-L130C83

**Comment by jcoyne** [comment]
And possibly here; https://github.com/projectblacklight/blacklight/blob/69373f202753f04ec6aca179fdf8fa01248a9edf/app/views/catalog/_document.html.erb#L4

**Comment by dnoneill** [comment]
That is what I was looking for, thanks.

**Comment by dnoneill** [comment]
It worked just in https://github.com/projectblacklight/blacklight/blob/main/app/components/blacklight/document_component.rb#L130C1-L130C83. PR for fix is open
