### ISSUE TITLE
Make the bookmark counter badge work for multiple elements

### ISSUE THREAD

**Issue by kirkkwang** [projectblacklight/blacklight#3350]
Currently, if we want to add another element that displays the bookmark count, it doesn't tick up or down when the bookmark is checked or unchecked.  It would be nice to have the ability to add more than one bookmark count element and have the same functionality.

![bl-bookmark](https://github.com/user-attachments/assets/afa2f6be-1336-4dd2-b0af-b05ae1d327e2)

**Comment by cbeer** [comment]
Was this fixed by #3351?

**Comment by kirkkwang** [comment]
@cbeer ah yes it was, i can close
