### ISSUE TITLE
Default Blacklight Solr schema should be generic, wildcard field-based

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight#407]
@jronallo: "i like what sunspot does with dynamic fields--very generic: https://github.com/sunspot/sunspot/blob/master/sunspot_solr/solr/solr/conf/schema.xml.  i think the way that Sunspot does it could work. lots of options for dynamic fields based on a short suffix. then anyone would need to map their data to the short suffix form to get it indexed"

**Comment by barmintor** [comment]
https://github.com/projectblacklight/blacklight/commit/ea7895d50cf5a3558d41f9cebda30e2f7f50adf7#diff-b2e69a0948ae7f88362c249c11bd2244
