### ISSUE TITLE
Admin interface/wizard for configuring Blacklight by introspecting a solr schema

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight#409]
@jronallo: "i've also thought about a wizard-type interface that would allow you to define your fields and then have solr and blacklight config generated for you"

@jkeck: "Well, it wasn't about a wizard specifically, but an admin interface that could accomplish something similar."

I'm inclined to assume the Solr index is properly configured, and try to use the /luke endpoint to try to extract enough information to do the Blacklight-side of things.. store the data in the database or yaml config, and setup the controller configuration to read it in.

**Comment by atz** [comment]
This ticket probably can be closed as overly broad wishlist.  It discusses both several different directions for overhaul: 
- generating the catalog controller
- generating the solr schema
- realtime configuration of solr via API

While I would love to see these features explored, no initiative having been taken in the intervening 3.5 years suggests this ticket is not actionable.

**Comment by cbeer** [comment]
I suspect we're closer than it might appear. We have support for wildcard field definitions, and Spotlight offers most of an admin interface for these actions.

**Comment by epugh** [comment]
Have you seen the new Solr Schema editor that is in Solr 9?  It's part of the Solr Admin, and looks pretty robust for changing the schema without accessing `schema.xml`.
