### ISSUE TITLE
undefined method `gsub' for nil:NilClass in bookmark_control.html.erb

### ISSUE THREAD

**Issue by RockShaz** [projectblacklight/blacklight#417]
Hi,

Showing D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/blacklight-3.2.2/app/views/catalog/_bookmark_control.html.erb where line #10 raised: 

undefined method `gsub' for nil:NilClass
Extracted source (around line #10): 

7:   -%>  
8:   <% unless existing_bookmark %>  
9: 
10:       <%= form_tag( bookmark_path( document ), :method => :put, :class => "bookmark_toggle", "data-doc-id" => document.id, :title=> document[document_show_link_field] ) do %>        
11:         <%= hidden_field(:bookmark, :title, :value => document[document_show_link_field] ) %>
12:         <%= submit_tag("Bookmark", :id => "bookmark_toggle_#{document.id.to_s.parameterize}", :class => "bookmark_add") %>
13:       <% end %>

Trace of template inclusion: D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/blacklight-3.2.2/app/views/catalog/_document_list.html.erb, D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/blacklight-3.2.2/app/views/catalog/index.html.erb

I am not getting what's going wrong here.

Please help me.

**Comment by cbeer** [comment]
I'm not sure we've ever reproduced this, and it's possibly fixed in newer versions of Blacklight regardless.
