### ISSUE TITLE
support for elasticsearch

### ISSUE THREAD

**Issue by nicolasfranck** [projectblacklight/blacklight#564]
Are you planning for supporting elasticsearch? 
I had a quick look in the BlackLight code, and
saw that Solr deeply wired into the core system.

Could it be possible to make this support more
modular, making it possible for third party
developers to plug other search engines to it?

Thanks in advance

**Comment by eranhirs** [comment]
I arrived to this message looking for blacklight support for elasticsearch.
I guess I am not the only one, so I think it will help others to know there are some alternatives for elasticsearch:
https://github.com/searchkit/searchkit
https://opensource.appbase.io/reactivesearch/
https://www.itemsapi.com/
