### ISSUE TITLE
Blacklight with Sunspot

### ISSUE THREAD

**Issue by Seaborg** [projectblacklight/blacklight#568]
I am trying to use Sunspot for indexing and Blacklight like suggested here:
https://github.com/projectblacklight/blacklight/wiki/Sunspot-for-indexing
I think that's a great idea but I can't work it out. All I can retrieve from solr is Class name and id:
My solr query:
  [http://0.0.0.0:8982/solr/select?&q=an&qf=keywords_tags_text&defType=dismax&rows=100&fq=type:Work&fl=*](http://0.0.0.0:8982/solr/select?&q=an&qf=keywords_tags_text&defType=dismax&rows=100&fq=type:Work&fl=*)

It searches solr correctly but can ouput anything more than model + id

-   sunspot (2.0.0)
-   sunspot_rails (2.0.0)
-   sunspot_solr (2.0.0)
-   blacklight (4.2.1)

My request handler:
```xml
<requestHandler name="dismax" class="solr.SearchHandler">
    <lst name="defaults">
      <str name="defType">dismax</str>
      <str name="echoParams">explicit</str>
      <float name="tie">0.01</float>
      <str name="qf">
        text^0.5 features^1.0 name^1.2 sku^1.5 id^10.0 manu^1.1 cat^1.4 author_name_text^2.2
     </str>
      <str name="pf">
        text^0.2 features^1.1 name^1.5 manu^1.4 manu_exact^1.9 author_name_text^2.2
     </str>
      <str name="bf">
        popularity^0.5 recip(price,1,1000,1000)^0.3
     </str>
     <str name="fl">
        id,name,price,score, keywords_tags_text
     </str>
      <str name="mm">
        2&lt;-1 5&lt;-2 6&lt;90%
     </str>
      <int name="ps">100</int>
      <str name="q.alt">_:_</str>
      <!-- example highlighter config, enable per-query with hl=true -->
      <str name="hl.fl">text features name</str>
      <!-- for this field, we want no fragmenting, just highlighting -->
      <str name="f.name.hl.fragsize">0</str>
      <!-- instructs Solr to return the field itself if no query terms are
          found -->
      <str name="f.name.hl.alternateField">name</str>
      <str name="f.text.hl.fragmenter">regex</str>
      <!-- defined below -->
    </lst>
  </requestHandler>
```

**Comment by atz** [comment]
Propose to close this as an out of date ticket.  Also this is a question of solr configuration without any direct concern to blacklight.  

Or maybe @Seaborg, you can give it a try with the current release?

**Comment by atz** [comment]
Closing, @Seaborg re-open if you still want to pursue this.

**Comment by Seaborg** [comment]
you can close that one now. thanks
