### ISSUE TITLE
should #query_has_constraints? and #has_search_parameters? be the same thing?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#768]
`query_has_constraints?` helper method: https://github.com/projectblacklight/blacklight/blob/58bcd0098c664a211410186789ace2e529caf651/app/helpers/blacklight/render_constraints_helper_behavior.rb#L15

`has_search_parameters?` helper method: https://github.com/projectblacklight/blacklight/blob/58bcd0098c664a211410186789ace2e529caf651/app/helpers/blacklight/catalog_helper_behavior.rb#L119

They aren't defined exactly the same -- but should they be? Is there any difference between a set of query params that has constraints in it, and a set of query params that has search parameters?

Right now, if params[:search_field] is defined but nothing else, that counts as `has_search_params?`, but not `query_has_constraints?`

If that's intentional (**option 1**), than it should be redefined as:

~~~
def has_search_params?(params = params)
   query_has_constraints?(params) || params[:search_field].present?
end
~~~

To be DRY, instead of repeating logic. 

But if it's not intentional/meaningful that they're different at all (**option 2**), we should mark one as deprecated and define it in terms of the other until we remove it. 

This came up because a plugin had to over-ride to redefine what it meant for params to include search criteria, and I had to override both of these in a non-DRY matter. 

option1 or option2?  @cbeer or @jcoyne?

**Comment by cbeer** [comment]
Looks like we removed `has_search_params?`, at least in `master` if not earlier.
