### ISSUE TITLE
fix improper manual use of html_escape in title i18n with substitution

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#800]
https://github.com/projectblacklight/blacklight/pull/793/files#r10090825

**Comment by atz** [comment]
This doesn't seem to be an issue anymore, or has moved to be the difference between these two (start and end of the block) lines:
https://github.com/projectblacklight/blacklight/blob/dee8d794125306ec8d4ab834a6a45bcf9671c791/app/helpers/blacklight/blacklight_helper_behavior.rb#L133-L155

**Comment by barmintor** [comment]
Closing as the PR was merged.
