### ISSUE TITLE
Dynamic fields not working

### ISSUE THREAD

**Issue by simonlamb** [projectblacklight/blacklight#803]
My Solr index has the following facets:-

test_a_facet
test_b_facet 

Adding a dynamic field to catalog_controller.rb, for example..
```ruby
    config.add_facet_field '*_facet'
```

Doesn't display the facets as expected.  

In my instance, :blacklight_solr  key returns nil. See - https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/configuration/fields.rb#L121  

Hacking the fields code to use Blacklight.solr object to get solr instance enables the dynamic fields to work, e.g.

```ruby
  @table[:luke_fields] ||= begin
    if Blacklight.solr
      Blacklight.solr.get('admin/luke', params: { fl: '*', 'json.nl' => 'map' })['fields']
    end
  rescue
    false
   end
```

However I'm assuming this is only a hack and not solution! 

Am I missing a configuration, or is this a genuine bug? 

Cheers,
Simon Lamb

**Comment by cbeer** [comment]
Fixed in #1166
