### ISSUE TITLE
Blacklight::Solr::Request broken with regard to merge

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#827]
Apparently Blacklight::Solr::Request is a hash-like class. It mostly masquerades as a Hash. 

But real Hashes have a #merge method which optionally takes a block to provide custom merge behavior. 

Blacklight::Solr::Request#merge seems to ignore a block argument. 

A part of BlacklightAdvancedSearch, a solr_search_params_logic method with the usual `solr_params, user_params` args,  assumes it can call merge with a block on `solr_params`. But `solr_params` are a Blacklight::Solr::Request, and it doesn't work. (It used to in older versions of BL)

Demonstrate with a stupid example:

``` ruby
real_hash = {"a" => [1]}

# silly custom merge logic that replaces everything with "FORCED"
real_hash.merge({"a" => "new"}) {|key, old, new| "FORCED" }
# => {"a"=>"FORCED"}

bl_hash = Blacklight::Solr::Request.new({"a" => [1]})
# => {"a"=>[1], "facet.field"=>[], "facet.query"=>[], "facet.pivot"=>[], "fq"=>[], "hl.fl"=>[]}
# Again with the silly logic
bl_hash.merge({"a" => "new"}) {|key, old, new| "FORCED" }
# But our silly logic was ignored, it is the same result as if we had not supplied
# a block argument. 
# => {"a"=>"new", "facet.field"=>[], "facet.query"=>[], "facet.pivot"=>[], "fq"=>[], "hl.fl"=>[]}
```

**Comment by atz** [comment]
FYI, I added HWIA testing and reworked deep_merge in https://github.com/projectblacklight/blacklight_advanced_search/pull/59

For the most part I don't think we have to worry about rails 3 anymore.
