### ISSUE TITLE
solr_path & qt

### ISSUE THREAD

**Issue by bcail** [projectblacklight/blacklight#930]
In configuration.rb, the default qt is "search" and the default solr_path is "select". Should the solr_path be changed to "search" to match qt? I have a solr instance that doesn't use the search handler if the path is select...

**Comment by mejackreed** [comment]
Is this something that we are still looking at for 6.0.0 release?

**Comment by cbeer** [comment]
I think for 6.0, we should change the default to not use `qt` and to use paths to request handler paths.

**Comment by jcoyne** [comment]
+1
