### ISSUE TITLE
Use #delete_all when clearing out old searches?

### ISSUE THREAD

**Issue by jronallo** [projectblacklight/blacklight#987]
It looks like #destroy_all instantiates each record which will be much slower when clearing out lots of searches compared to #delete_all which uses a single SQL query and does not in instantiate the records. There might be some reason why (associations?) #delete_all is the wrong choice in this case, though. Anyone know?

http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-delete_all

https://github.com/projectblacklight/blacklight/blob/1b0fd9f80efea73f5a4833e45092a5c10567a2b2/app/models/search.rb#L23

**Comment by cjcolvar** [comment]
Duplicated by #2062.
