### ISSUE TITLE
Facet code blocks *adding* facet queries to facet fields

### ISSUE THREAD

**Issue by atz** [projectblacklight/blacklight#995]
If a facet field has a query, then it doesn't facet by field values, according to:
https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/facet.rb#L44

But what I want to do is both.  For example, in the context of my administrative application, it is super useful to expose when a required/expected field is NOT present.  Detecting malformed or missing data is core to the app.  Consider how simple it is to do this in Solr:

```
https://localhost/solr/select?q=*:*facet=true&facet.query=-has_model_s:*&facet.field=has_model_s
```

The response includes:

``` json
  "facet_counts": {
    "facet_queries": {
      "-has_model_s:*": 2
    },
    "facet_fields": {
      "has_model_s": [
        "info:fedora/afmodel:Dor_Item",
        500768,
        ...
      ]
    }
```

Via Blacklight, I can already create both facets separately, but I cannot get them to display together.  So this could also be seen as directly related to other tickets about facet **grouping**.

**Comment by cbeer** [comment]
Solr and Blacklight support `facet.missing`, which should solve the simple case.
