### ISSUE TITLE
Drop support for Solr 3.1 and earlier

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight#999]
Solr 3.2 introduced several nice features, including `{!term}`, which would help with e.g. #993.

**Comment by mejackreed** [comment]
Solr 3.2 was released 6/3/2011... and now we are two major version releases away. Should this be moved up to 4.1?

Can does anything need to be done here (besides saying we don't support it)?

**Comment by cbeer** [comment]
:+1: 

There could be work here dropping work-arounds for older Solr versions, or taking advantage of new solr features (e.g. `{!term}` which can clean up some of the facet value escaping we're doing).

I can't remember when it was introduced, but using real-time get by default for single-document lookup might be nice.
